#ifdef _WIN32

namespace fibjs {
const wchar_t* g_console_js = L"!function(w){function f(t){return t<10?\"0\"+t:t}function quote(t){return escapabl"
"e.lastIndex=0,escapable.test(t)?\'\"\'+t.replace(escapable,function(t){var e=meta[t"
"];return\"string\"==typeof e?e:\"\\\\u\"+(\"0000\"+t.charCodeAt(0).toString(16)).slice(-"
"4)})+\'\"\':\'\"\'+t+\'\"\'}function str(t,e){var n,r,o,f,i,u=gap,a=e[t];switch(a&&\"objec"
"t\"==typeof a&&\"function\"==typeof a.toJSON&&(a=a.toJSON(t)),\"function\"==typeof re"
"p&&(a=rep.call(e,t,a)),typeof a){case\"string\":return quote(a);case\"number\":retur"
"n isFinite(a)?String(a):\"null\";case\"boolean\":case\"null\":return String(a);case\"ob"
"ject\":if(!a)return\"null\";if(gap+=indent,i=[],\"[object Array]\"===Object.prototype"
".toString.apply(a)){for(f=a.length,n=0;n<f;n+=1)i[n]=str(n,a)||\"null\";return o=0"
"===i.length?\"[]\":gap?\"[\\n\"+gap+i.join(\",\\n\"+gap)+\"\\n\"+u+\"]\":\"[\"+i.join(\",\")+\"]\","
"gap=u,o}if(rep&&\"object\"==typeof rep)for(f=rep.length,n=0;n<f;n+=1)\"string\"==typ"
"eof(r=rep[n])&&(o=str(r,a))&&i.push(quote(r)+(gap?\": \":\":\")+o);else for(r in a)O"
"bject.hasOwnProperty.call(a,r)&&(o=str(r,a))&&i.push(quote(r)+(gap?\": \":\":\")+o);"
"return o=0===i.length?\"{}\":gap?\"{\\n\"+gap+i.join(\",\\n\"+gap)+\"\\n\"+u+\"}\":\"{\"+i.join"
"(\",\")+\"}\",gap=u,o}}w.JSON||(w.JSON={}),\"function\"!=typeof Date.prototype.toJSON&"
"&(Date.prototype.toJSON=function(t){return isFinite(this.valueOf())?this.getUTCF"
"ullYear()+\"-\"+f(this.getUTCMonth()+1)+\"-\"+f(this.getUTCDate())+\"T\"+f(this.getUTC"
"Hours())+\":\"+f(this.getUTCMinutes())+\":\"+f(this.getUTCSeconds())+\"Z\":null},Strin"
"g.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(t){"
"return this.valueOf()});var cx=new RegExp(\"[\\\\u0000\\\\u00ad\\\\u0600-\\\\u0604\\\\u070f"
"\\\\u17b4\\\\u17b5\\\\u200c-\\\\u200f\\\\u2028-\\\\u202f\\\\u2060-\\\\u206f\\\\ufeff\\\\ufff0-\\\\ufff"
"f]\",\"g\"),escapable=new RegExp(\'[\\\\\\\\\\\\\"\\\\x00-\\\\x1f\\\\x7f-\\\\x9f\\\\u00ad\\\\u0600-\\\\u0"
"604\\\\u070f\\\\u17b4\\\\u17b5\\\\u200c-\\\\u200f\\\\u2028-\\\\u202f\\\\u2060-\\\\u206f\\\\ufeff\\\\uf"
"ff0-\\\\uffff]\',\"g\"),re1=new RegExp(\"^[\\\\],:{}\\\\s]*$\"),re2=new RegExp(\'\\\\\\\\(?:[\"\\\\"
"\\\\\\\\/bfnrt]|u[0-9a-fA-F]{4})\',\"g\"),re3=new RegExp(\'\"[^\"\\\\\\\\\\\\n\\\\r]*\"|true|false|"
"null|-?\\\\d+(?:\\\\.\\\\d*)?(?:[eE][+\\\\-]?\\\\d+)?\',\"g\"),re4=new RegExp(\"(?:^|:|,)(?:\\\\"
"s*\\\\[)+\",\"g\"),gap,indent,meta={\"\\b\":\"\\\\b\",\"\\t\":\"\\\\t\",\"\\n\":\"\\\\n\",\"\\f\":\"\\\\f\",\"\\r\":"
"\"\\\\r\",\'\"\':\'\\\\\"\',\"\\\\\":\"\\\\\\\\\"},rep;\"function\"!=typeof JSON.stringify&&(JSON.string"
"ify=function(t,e,n){var r;if(gap=\"\",indent=\"\",\"number\"==typeof n)for(r=0;r<n;r+="
"1)indent+=\" \";else\"string\"==typeof n&&(indent=n);if(rep=e,e&&\"function\"!=typeof "
"e&&(\"object\"!=typeof e||\"number\"!=typeof e.length))throw new Error(\"JSON.stringi"
"fy\");return str(\"\",{\"\":t})}),\"function\"!=typeof JSON.parse&&(JSON.parse=function"
"(text,reviver){function walk(t,e){var n,r,o=t[e];if(o&&\"object\"==typeof o)for(n "
"in o)Object.hasOwnProperty.call(o,n)&&(void 0!==(r=walk(o,n))?o[n]=r:(delete o[n"
"],o[n]=null));return reviver.call(t,e,o)}var j;if(text=String(text),cx.lastIndex"
"=0,cx.test(text)&&(text=text.replace(cx,function(t){return\"\\\\u\"+(\"0000\"+t.charCo"
"deAt(0).toString(16)).slice(-4)})),re1.test(text.replace(re2,\"@\").replace(re3,\"]"
"\").replace(re4,\"\")))return j=eval(\"(\"+text+\")\"),\"function\"==typeof reviver?walk("
"{\"\":j},\"\"):j;throw new SyntaxError(\"JSON.parse\")})}(this),function(t){function e"
"(t){return null!==t&&\"object\"==typeof t&&\"function\"!=typeof t.toJSON&&r(t,\"\",[],"
"null),JSON.stringify(t)}function n(t,e,n){this.val=t,this.k=e,this.parent=n,this"
".count=1}function r(t,e,o,f){if(\"object\"==typeof t&&null!==t)if(t instanceof n)t"
".count++;else if(\"function\"!=typeof t.toJSON||t.toJSON.forceDecirc)if(f&&~o.inde"
"xOf(t))f[e]=new n(t,e,f);else{o.push(t);for(var e in t)r(t[e],e,o,t);o.pop()}}fu"
"nction o(t,n){void 0===n&&(n=\"\"),n=n.toString();var r=/(%?)(%([jds]))/g,o=Array."
"prototype.slice.call(arguments,2);o.length&&(n=n.replace(r,function(t,n,r,f){var"
" i=o.shift();switch(f){case\"s\":i=\"object\"==typeof i&&\"function\"!=typeof i.toJSON"
"?e(i):\"\"+i;break;case\"d\":i=Number(i);break;case\"j\":i=e(i)}return n?(o.unshift(i)"
",t):i}));for(var f=0;f<o.length;f++){var i=o[f];\"object\"==typeof i&&\"function\"!="
"typeof i.toJSON?n+=\" \"+e(i):n+=\" \"+i}n=n.replace(/%{2,2}/g,\"%\"),external.log(t,\""
"\"+n)}function f(t){return function(){var e=[t].concat(Array.prototype.slice.call"
"(arguments,0));return o.apply(this,e)}}n.prototype.toJSON=function(){return 0==-"
"-this.count&&(this.parent[this.k]=this.val),\"[Circular]\"},t.console={debug:f(7),"
"log:f(6),notice:f(5),warn:f(4),error:f(3),crit:f(2),alert:f(1),fatal:f(0)}}(this"
");";
}

#endif