#ifdef _WIN32

namespace fibjs {
const wchar_t* g_console_js = L"!function(w){function f(t){return t<10?\"0\"+t:t}w.JSON||(w.JSON={}),\"function\"!=t"
"ypeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(t){return isFinite("
"this.valueOf())?this.getUTCFullYear()+\"-\"+f(this.getUTCMonth()+1)+\"-\"+f(this.get"
"UTCDate())+\"T\"+f(this.getUTCHours())+\":\"+f(this.getUTCMinutes())+\":\"+f(this.getU"
"TCSeconds())+\"Z\":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.p"
"rototype.toJSON=function(t){return this.valueOf()});var cx=new RegExp(\"[\\\\u0000\\"
"\\u00ad\\\\u0600-\\\\u0604\\\\u070f\\\\u17b4\\\\u17b5\\\\u200c-\\\\u200f\\\\u2028-\\\\u202f\\\\u2060-"
"\\\\u206f\\\\ufeff\\\\ufff0-\\\\uffff]\",\"g\"),escapable=new RegExp(\'[\\\\\\\\\\\\\"\\\\x00-\\\\x1f\\\\"
"x7f-\\\\x9f\\\\u00ad\\\\u0600-\\\\u0604\\\\u070f\\\\u17b4\\\\u17b5\\\\u200c-\\\\u200f\\\\u2028-\\\\u20"
"2f\\\\u2060-\\\\u206f\\\\ufeff\\\\ufff0-\\\\uffff]\',\"g\"),re1=new RegExp(\"^[\\\\],:{}\\\\s]*$\")"
",re2=new RegExp(\'\\\\\\\\(?:[\"\\\\\\\\\\\\/bfnrt]|u[0-9a-fA-F]{4})\',\"g\"),re3=new RegExp(\'\""
"[^\"\\\\\\\\\\\\n\\\\r]*\"|true|false|null|-?\\\\d+(?:\\\\.\\\\d*)?(?:[eE][+\\\\-]?\\\\d+)?\',\"g\"),re"
"4=new RegExp(\"(?:^|:|,)(?:\\\\s*\\\\[)+\",\"g\"),gap,indent,meta={\"\\b\":\"\\\\b\",\"\\t\":\"\\\\t\""
",\"\\n\":\"\\\\n\",\"\\f\":\"\\\\f\",\"\\r\":\"\\\\r\",\'\"\':\'\\\\\"\',\"\\\\\":\"\\\\\\\\\"},rep;function quote(t){r"
"eturn escapable.lastIndex=0,escapable.test(t)?\'\"\'+t.replace(escapable,function(t"
"){var e=meta[t];return\"string\"==typeof e?e:\"\\\\u\"+(\"0000\"+t.charCodeAt(0).toStrin"
"g(16)).slice(-4)})+\'\"\':\'\"\'+t+\'\"\'}function str(t,e){var n,r,o,f,u,i=gap,a=e[t];sw"
"itch(a&&\"object\"==typeof a&&\"function\"==typeof a.toJSON&&(a=a.toJSON(t)),\"functi"
"on\"==typeof rep&&(a=rep.call(e,t,a)),typeof a){case\"string\":return quote(a);case"
"\"number\":return isFinite(a)?String(a):\"null\";case\"boolean\":case\"null\":return Str"
"ing(a);case\"object\":if(!a)return\"null\";if(gap+=indent,u=[],\"[object Array]\"===Ob"
"ject.prototype.toString.apply(a)){for(f=a.length,n=0;n<f;n+=1)u[n]=str(n,a)||\"nu"
"ll\";return o=0===u.length?\"[]\":gap?\"[\\n\"+gap+u.join(\",\\n\"+gap)+\"\\n\"+i+\"]\":\"[\"+u."
"join(\",\")+\"]\",gap=i,o}if(rep&&\"object\"==typeof rep)for(f=rep.length,n=0;n<f;n+=1"
")\"string\"==typeof(r=rep[n])&&(o=str(r,a))&&u.push(quote(r)+(gap?\": \":\":\")+o);els"
"e for(r in a)Object.hasOwnProperty.call(a,r)&&(o=str(r,a))&&u.push(quote(r)+(gap"
"?\": \":\":\")+o);return o=0===u.length?\"{}\":gap?\"{\\n\"+gap+u.join(\",\\n\"+gap)+\"\\n\"+i+"
"\"}\":\"{\"+u.join(\",\")+\"}\",gap=i,o}}\"function\"!=typeof JSON.stringify&&(JSON.string"
"ify=function(t,e,n){var r;if(indent=gap=\"\",\"number\"==typeof n)for(r=0;r<n;r+=1)i"
"ndent+=\" \";else\"string\"==typeof n&&(indent=n);if((rep=e)&&\"function\"!=typeof e&&"
"(\"object\"!=typeof e||\"number\"!=typeof e.length))throw new Error(\"JSON.stringify\""
");return str(\"\",{\"\":t})}),\"function\"!=typeof JSON.parse&&(JSON.parse=function(te"
"xt,reviver){var j;function walk(t,e){var n,r,o=t[e];if(o&&\"object\"==typeof o)for"
"(n in o)Object.hasOwnProperty.call(o,n)&&(void 0!==(r=walk(o,n))?o[n]=r:(delete "
"o[n],o[n]=null));return reviver.call(t,e,o)}if(text=String(text),cx.lastIndex=0,"
"cx.test(text)&&(text=text.replace(cx,function(t){return\"\\\\u\"+(\"0000\"+t.charCodeA"
"t(0).toString(16)).slice(-4)})),re1.test(text.replace(re2,\"@\").replace(re3,\"]\")."
"replace(re4,\"\")))return j=eval(\"(\"+text+\")\"),\"function\"==typeof reviver?walk({\"\""
":j},\"\"):j;throw new SyntaxError(\"JSON.parse\")})}(this),function(t){function u(t)"
"{return null!==t&&\"object\"==typeof t&&\"function\"!=typeof t.toJSON&&function t(e,"
"n,r,o){{if(\"object\"!=typeof e||null===e)return;if(e instanceof f)return void e.c"
"ount++;if(\"function\"==typeof e.toJSON&&!e.toJSON.forceDecirc)return;if(o&&~r.ind"
"exOf(e))return void(o[n]=new f(e,n,o))}r.push(e);for(var n in e)t(e[n],n,r,e);r."
"pop()}(t,\"\",[],null),JSON.stringify(t)}function f(t,e,n){this.val=t,this.k=e,thi"
"s.parent=n,this.count=1}function e(e){return function(){var t=[e].concat(Array.p"
"rototype.slice.call(arguments,0));return function(t,e){void 0===e&&(e=\"\"),e=e.to"
"String();var f=Array.prototype.slice.call(arguments,2);f.length&&(e=e.replace(/("
"%?)(%([jds]))/g,function(t,e,n,r){var o=f.shift();switch(r){case\"s\":o=\"object\"=="
"typeof o&&\"function\"!=typeof o.toJSON?u(o):\"\"+o;break;case\"d\":o=Number(o);break;"
"case\"j\":o=u(o)}return e?(f.unshift(o),t):o}));for(var n=0;n<f.length;n++){var r="
"f[n];\"object\"==typeof r&&\"function\"!=typeof r.toJSON?e+=\" \"+u(r):e+=\" \"+r}e=e.re"
"place(/%{2,2}/g,\"%\"),external.log(t,\"\"+e)}.apply(this,t)}}f.prototype.toJSON=fun"
"ction(){return 0==--this.count&&(this.parent[this.k]=this.val),\"[Circular]\"},t.c"
"onsole={debug:e(7),log:e(6),info:e(6),notice:e(5),warn:e(4),error:e(3),crit:e(2)"
",alert:e(1),fatal:e(0)}}(this);";
}

#endif