#!/bin/bash

if [ $# -lt 1 ]; then
	echo ""
	echo "build [Release | Release32 | Debug | Debug32 | clean]"
	echo ""
	exit 0
fi

if [ $1 = 'clean' ]; then
	if [ -e "out" ]; then
		rm -r -f "out"
	fi

	exit 0
fi

if [ $1 != 'Release' ] && [ $1 != 'Release32' ] && [ $1 != 'Debug' ] && [ $1 != 'Debug32' ]; then
	echo ""
	echo "build [Release | Release32 | Debug | Debug32 | clean]"
	echo ""
	exit 0
fi

OS=`uname`

if [ ! -e "out" ]; then
	mkdir "out"
fi

if [ ! -e "out/${OS}_$1" ]; then
	mkdir "out/${OS}_$1"
fi

echo "${OS}_$1"
cd "out/${OS}_$1"
cmake -DBUILD_TYPE=$1 ../../tools
make

cd ../..
