#!/bin/bash

if [ $# -lt 1 ]; then
	echo ""
	echo "build [Release | Release32 | Debug | Debug32 | clean]"
	echo ""
	exit 0
fi

if [ $1 = 'clean' ]; then
	if [ -e "Release" ]; then
		rm -r -f "Release"
	fi

	if [ -e "Release32" ]; then
		rm -r -f "Release32"
	fi

	if [ -e "Debug" ]; then
		rm -r -f "Debug"
	fi

	if [ -e "Debug32" ]; then
		rm -r -f "Debug32"
	fi

	exit 0
fi

if [ $1 != 'Release' ] && [ $1 != 'Release32' ] && [ $1 != 'Debug' ] && [ $1 != 'Debug32' ]; then
	echo ""
	echo "build [Release | Release32 | Debug | Debug32 | clean]"
	echo ""
	exit 0
fi

if [ ! -e "$1" ]; then
	mkdir "$1"
fi

cd "$1"
cmake -DBUILD_TYPE=$1 ..
find . -name "*.c" -delete
find . -name "*.cpp" -delete
make

cd ..
