#pragma once

#define NODE_API_SUPPORTED_VERSION_MAX 9
#define NODE_API_SUPPORTED_VERSION_MIN 1

#define NODE_API_DEFAULT_MODULE_API_VERSION 8

#define NODE_MAJOR_VERSION 8
#define NODE_MINOR_VERSION 0
#define NODE_PATCH_VERSION 0

#ifndef NODE_RELEASE
#define NODE_RELEASE "node"
#endif
