/*! @brief 信息摘要对象 */
interface Digest : object
{
    /*! @brief 更新二进制摘要信息
     @param data 二进制数据块
     @return 返回信息摘要对象本身
     */
    Digest update(Buffer data);

    /*! @brief 计算并返回摘要
     @param codec 指定编码格式，允许值为："hex", "base64", "utf8", 或者系统支持的字符集
     @return 返回摘要的字符串表示
     */
    Value digest(String codec);

    /*! @brief 计算并返回摘要
      @return 返回摘要的二进制数据
     */
    Value digest();

    /*! @brief 查询当前信息摘要算法的摘要字节数 */
    readonly Integer size;
};
