/*! @brief 事件源接口，用于服务器推送事件

  引用方式：
  ```JavaScript
    const http = require('http');
    
    const es = new http.EventSource('http://localhost:8080');
  ```
*/
interface EventSource : EventEmitter
{
    /*! @brief 构造函数

     options 包含请求的附加选项，支持的内容如下：
     ```JavaScript
     {
         "method": "GET", // specify the http request method: GET, POST, etc, default: GET.
         "protocol": "http",
         "slashes": true,
         "username": "",
         "password": "",
         "hostname": "",
         "port": "",
         "pathname": "",
         "keepAlive": unknown, // If not specified, the default settings of the client will be used.
         "query": {},
         "body": SeekableStream | Buffer | String | {},
         "json": {},
         "pack": {},
         "headers": {}
     }
     ```

      @param url 服务器地址
      @param options 选项
    */
    EventSource(String url, Object options = {});

    /*! @brief 关闭连接 */
    close() async;

    /*! @brief 发送事件到客户端

     options 包含请求的附加选项，支持的内容如下：
     ```JavaScript
     {
         "event": "message", // 指定事件类型，默认为 message
         "id": "", // 事件 ID
         "retry": 0 // 重试时间间隔，单位为毫秒
     }
     ```

     @param data 事件数据
     @param options 选项
     @return 返回发送的字节数
    */
    Integer send(String data, Object options = {}) async;

    /*! @brief 事件源状态，取值为 CONNECTING、OPEN、CLOSED */
    readonly Integer readyState;

    /*! @brief 服务器地址 */
    readonly String url;

    /*! @brief 是否携带凭证 */
    readonly Boolean withCredentials;

    /*! @brief http 响应对象 */
    readonly HttpResponse response;

    /*! @brief 打开事件回调 */
    event open();

    /*! @brief 错误事件回调 */
    event error();

    /*! @brief 消息事件回调 */
    event message();

    /*! @brief 关闭事件回调 */
    event close();
};
