/*!
 * FTModel fasttext 模型对象
 *
 */
interface FTModel : object
{
    /*! @brief 查询当前模型是否是量化模型
     @return 返回是否是量化模型
     */
    Boolean isQuantized();

    /*! @brief 获取当前模型的维度
     @return 返回模型维度
     */
    Integer getDimension();

    /*! @brief 获取给定词的词向量
     @param word 词
     @return 返回词向量
     */
    Array getWordVector(String word);

    /*! @brief 获取给定句子的句向量
     @param text 句子
     @return 返回句向量
     */
    Array getSentenceVector(String text);

    /*! @brief 获取给定词的近义词
     @param word 词
     @param k 返回前 k 个近义词
     @return 返回近义词结果
     */
    Array getNearestNeighbors(String word, Integer k = 10);

    /*! @brief 返回操作 wordA - wordB + wordC 的最近k个邻居
     @param wordA 词A
     @param wordB 词B
     @param wordC 词C
     @param k 返回前 k 个近义词
     @return 返回近义词结果
     */
    Array getAnalogies(String wordA, String wordB, String wordC, Integer k = 10);

    /*! @brief 给定一个单词，获取该单词在词典中的词ID
     @param word 词
     @return 返回词ID
     */
    Integer getWordId(String word);

    /*! @brief 给定一个子词，获取该子词在词典中的词ID
     @param subword 子词
     @return 返回子词ID
     */
    Integer getSubwordId(String subword);

    /*! @brief 给定一个索引，获取输入矩阵对应的向量
     @param id 索引
     @return 返回输入矩阵对应的向量
     */
    Array getInputVector(Integer id);

    /*! @brief 返回子单词及其索引
     @param word 词
     @return 返回子单词及其索引
     */
    (Array subwords, Array ngrams) getSubwords(String word);

    /*! @brief 预测文本的分类
     @param text 文本
     @param k 返回前 k 个分类
     @return 返回分类结果
     */
    NArray predict(String text, Integer k = 3, Number threshold = 0.0) async;

    /*! @brief 预测文本的分类
     @param texts 文本数组
     @param k 返回前 k 个分类
     @param threshold 阈值
     @return 返回分类结果
     */
    NArray predict(Array texts, Integer k = 3, Number threshold = 0.0) async;

    /*! @brief 量化模型，减小模型的大小和内存占用
     @param trainFile 训练文件
     @param args 量化参数
     */
    quantize(String trainFile, Object args = {}) async;

    /*! @brief 获取当前模型的词典及词频
     @return 返回词典及词频
     */
    (Array vocabs, Array freqs) getWords();

    /*! @brief 获取当前模型的标签及标签频率
     @return 返回标签及标签频率
     */
    (Array labels, Array freqs) getLabels();

    /*! @brief 保存当前模型
     @param filename 模型文件名
     */
    saveModel(String filename);
};
