
/*! @brief http 请求消息对象 */
interface HttpRequest : HttpMessage
{
    /*! @brief HttpRequest 构造函数，创建一个新的 HttpRequest 对象 */
    HttpRequest();

    /*! @brief 获取响应消息对象*/
    readonly HttpResponse response;

    /*! @brief 查询和设置请求方法 */
    String method;

    /*! @brief 查询和设置请求地址 */
    String address;

    /*! @brief 查询和设置请求查询字符串 */
    String queryString;

    /*! @brief 获取包含消息 cookies 的容器*/
    readonly HttpCollection cookies;

    /*! @brief 获取包含消息 form 的容器*/
    readonly HttpCollection form;

    /*! @brief 获取包含消息 query 的容器*/
    readonly HttpCollection query;
};
