
/*! @brief http 协议转换处理器

  用以将数据流转换为 http 协议消息，创建方式：
  ```JavaScript
  var hdlr = new mq.HttpHandler(...);
  ```
  或者：
  ```JavaScript
  var hdlr = new http.Handler(...);
  ```
 */
interface HttpHandler : HandlerEx
{
    /*! @brief 创建一个 http 协议处理器对象，将流对象的数据转变为 http 消息对象
    @param hdlr 内置消息处理器，处理函数，链式处理数组，路由对象，详见 mq.Handler
    */
    HttpHandler(Handler hdlr);

    /*! @brief 查询和设置是否允许跨域请求，缺省为 false */
    Boolean crossDomain;

    /*! @brief 查询和设置是否允强制使用 gzip 压缩输出，缺省为 false */
    Boolean forceGZIP;

    /*! @brief 查询和设置最大请求头个数，缺省为 128 */
    Integer maxHeadersCount;

    /*! @brief 查询和设置最大上传尺寸，以字节为单位，缺省为 67108864(64M) */
    Integer maxUploadSize;

    /*! @brief 查询和设置服务器名称，缺省为：fibjs/0.x.0 */
    String serverName;
};
