/*! @brief 基础对象，所有对象均继承于此*/
interface object
{
    /*! @brief 强制回收对象，调用此方法后，对象资源将立即释放*/
    dispose();

    /*! @brief 比较当前对象与给定的对象是否相等
     @param expected 制定比较的目标对象
     @return 返回对象比较的结果
    */
    Boolean equals(object expected);

    /*! @brief 返回对象的字符串表示，一般返回 "[Native Object]"，对象可以根据自己的特性重新实现
     @return 返回对象的字符串表示
    */
    String toString();

    /*! @brief 返回对象的 JSON 格式表示，一般返回对象定义的可读属性集合
     @param key 未使用
     @return 返回包含可 JSON 序列化的值
     */
    Value toJSON(String key = "");

    /*! @brief 返回对象本身的数值
     @return 返回对象本身的数值
    */
    Value valueOf();
};
