/*! @brief odbc 数据库连接对象

 使用 db.open 或 db.openOdbc 创建，创建方式：
 ```JavaScript
 var slite = db.openOdbc("odbc://user:pass@host/db?driver=PostgreSQL%20ANSI");
 ```
*/
interface Odbc : DbConnection
{
    /*! @brief 选择当前数据库连接的缺省数据库
	 @param dbName 指定数据库名
	 */
    use(String dbName) async;
};
