/*! @brief os_constants priority 子模块，包含进程优先级常量

 引用方法：
 ```JavaScript
 var priority = require('os').constants.priority
 ```
 */
module os_constants_priority
{
    /**/
    const PRIORITY_LOW = 19;

    /**/
    const PRIORITY_BELOW_NORMAL = 10;

    /**/
    const PRIORITY_NORMAL = 0;

    /**/
    const PRIORITY_ABOVE_NORMAL = -7;

    /**/
    const PRIORITY_HIGH = -14;

    /**/
    const PRIORITY_HIGHEST = -20;
};
