/*! @brief os_constants signals 子模块，包含 POSIX 信号常量

 引用方法：
 ```JavaScript
 var signals = require('os').constants.signals
 ```
 */
module os_constants_signals
{
    /**/
    const SIGHUP = 1;

    /**/
    const SIGINT = 2;

    /**/
    const SIGQUIT = 3;

    /**/
    const SIGILL = 4;

    /**/
    const SIGTRAP = 5;

    /**/
    const SIGABRT = 6;

    /**/
    const SIGIOT = 6;

    /**/
    const SIGBUS = 7;

    /**/
    const SIGFPE = 8;

    /**/
    const SIGKILL = 9;

    /**/
    const SIGUSR1 = 10;

    /**/
    const SIGSEGV = 11;

    /**/
    const SIGUSR2 = 12;

    /**/
    const SIGPIPE = 13;

    /**/
    const SIGALRM = 14;

    /**/
    const SIGTERM = 15;

    /**/
    const SIGSTKFLT = 16;

    /**/
    const SIGCHLD = 17;

    /**/
    const SIGCONT = 18;

    /**/
    const SIGSTOP = 19;

    /**/
    const SIGTSTP = 20;

    /**/
    const SIGTTIN = 21;

    /**/
    const SIGTTOU = 22;

    /**/
    const SIGURG = 23;

    /**/
    const SIGXCPU = 24;

    /**/
    const SIGXFSZ = 25;

    /**/
    const SIGVTALRM = 26;

    /**/
    const SIGPROF = 27;

    /**/
    const SIGWINCH = 28;

    /**/
    const SIGIO = 29;

    /**/
    const SIGPOLL = 29;

    /**/
    const SIGPWR = 30;

    /**/
    const SIGSYS = 31;
};
