/*! @brief PerformanceObserver 接口用于观察性能记录的接口

 PerformanceObserver 接口用于观察性能记录的接口。它允许你注册一个回调函数，当一个新的性能记录被添加到浏览器的性能缓冲区时，这个回调函数会被调用。你可以使用 PerformanceObserver 接口来观察特定类型的性能记录，比如资源加载时间、用户输入延迟等。
*/
interface PerformanceObserver : object
{
    /*! @brief 构造函数

     @param callback 当一个新的性能记录被添加到浏览器的性能缓冲区时，这个回调函数会被调用
    */
    PerformanceObserver(Function callback);

    /*! @brief 注册观察的资源类型 

     options 为一个对象，包含以下属性：
       - type: 观察的资源类型
       - entryTypes: 观察的资源类型列表

     @param options 观察的资源类型
    */
    observe(Object options);

    /*! @brief 取消观察的资源类型 */
    disconnect();

    /*! @brief 获取观察的资源类型的记录
     @return 返回观察的资源类型的记录
    */
    NArray takeRecords();
};
