/*! @brief tls 安全上下文对象，用于多个 tls 连接共享基础配置

  SecureContext 对象是一个安全上下文对象，用于多个 tls 连接共享基础配置。SecureContext 对象可以通过 tls.createSecureContext 方法创建。
  ```JavaScript
    const tls = require('tls');
    const fs = require('fs');

    const options = {
      key: fs.readFileSync('server-key.pem'),
      cert: fs.readFileSync('server-cert.pem')
    };

    const context = tls.createSecureContext(options);
  ```
 */
interface SecureContext : object
{
    /*! @brief 查询安全上下文的受信任的 CA 证书 */
    readonly X509Certificate ca;

    /*! @brief 查询安全上下文连接的私钥 */
    readonly KeyObject key;

    /*! @brief 查询安全上下文连接的证书 */
    readonly X509Certificate cert;

    /*! @brief 查询安全上下文允许的最大 TLS 版本 */
    readonly String maxVersion;

    /*! @brief 查询安全上下文允许的最小 TLS 版本 */
    readonly String minVersion;

    /*! @brief 查询安全上下文使用的 TLS 协议版本*/
    readonly String secureProtocol;

    /*! @brief 查询安全上下文是否拒绝任何未经所提供 CA 列表授权的连接 */
    readonly Boolean rejectUnauthorized;

    /*! @brief 查询安全上下文回话超时 */
    readonly Integer sessionTimeout;
};
