/*! @brief 网络套接口对象

 Socket 属于 net 模块，创建方法
 ```JavaScript
 var s = new net.Socket();
 ```
 */
interface Socket : Stream
{
    /*! @brief Socket 构造函数，创建一个新的 Socket 对象
     @param family 指定地址集，缺省为 AF_INET，ipv4
     */
    Socket(Integer family = net.AF_INET);

    /*! @brief 查询当前 Socket 对象的地址集 */
    readonly Integer family;

    /*! @brief 查询当前连接的对方地址 */
    readonly String remoteAddress;

    /*! @brief 查询当前连接的对方端口 */
    readonly Integer remotePort;

    /*! @brief 查询当前连接的本地地址 */
    readonly String localAddress;

    /*! @brief 查询当前连接的本地端口 */
    readonly Integer localPort;

    /*! @brief 查询和设置超时时间 单位毫秒*/
    Integer timeout;

    /*! @brief 建立一个 tcp 连接
     @param port 指定对方端口
     @param host 指定对方地址或主机名，缺省为 localhost
     @param timeout 指定超时时间，单位是毫秒，默认为 0
     @return 返回连接的 Socket 对象
     */
    Stream connect(Integer port, String host = "localhost", Integer timeout = 0) async;

    /*! @brief 建立一个 unix socket 或 Windows pipe 连接
     @param path 指定 unix socket 或 Windows pipe 路径
     @param timeout 指定超时时间，单位是毫秒，默认为 0
     @return 返回连接的 Socket 对象
     */
    Stream connect(String path, Integer timeout = 0) async;

    /*! @brief 建立一个连接

     options 参数可以包含以下属性：
      - port: 指定对方端口
      - host: 指定对方地址或主机名
      - timeout: 指定超时时间，单位是毫秒，默认为 0

     @param options 指定连接选项对象，可以包含以下属性：
     @return 返回连接的 Socket 对象
    */
    Stream connect(Object options) async;

    /*! @brief 建立一个连接，并在连接建立后触发 connect 事件
     @param port 指定对方端口
     @param connectListener 指定 once 的 connect 事件监听器
     @return 返回连接的 Socket 对象
     */
    Stream connect(Integer port, Function connectListener) async;

    /*! @brief 建立一个连接，并在连接建立后触发 connect 事件
     @param port 指定对方端口
     @param host 指定对方地址或主机名，缺省为 localhost
     @param connectListener 指定 once 的 connect 事件监听器
     @return 返回连接的 Socket 对象
     */
    Stream connect(Integer port, String host, Function connectListener) async;

    /*! @brief 建立一个连接，并在连接建立后触发 connect 事件
     @param port 指定对方端口
     @param host 指定对方地址或主机名，缺省为 localhost
     @param timeout 指定超时时间，单位是毫秒，默认为 0
     @param connectListener 指定 once 的 connect 事件监听器
     @return 返回连接的 Socket 对象
     */
    Stream connect(Integer port, String host, Integer timeout, Function connectListener) async;

    /*! @brief 建立一个连接，并在连接建立后触发 connect 事件
     @param path 指定 unix socket 或 Windows pipe 路径
     @param connectListener 指定 once 的 connect 事件监听器
     @return 返回连接的 Socket 对象
     */
    Stream connect(String path, Function connectListener) async;

    /*! @brief 建立一个连接，并在连接建立后触发 connect 事件
     @param path 指定 unix socket 或 Windows pipe 路径
     @param timeout 指定超时时间，单位是毫秒，默认为 0
     @param connectListener 指定 once 的 connect 事件监听器
     @return 返回连接的 Socket 对象
     */
    Stream connect(String path, Integer timeout, Function connectListener) async;

    /*! @brief 建立一个连接，并在连接建立后触发 connect 事件
     @param options 指定连接选项对象，可以包含以下属性：
     @param connectListener 指定 once 的 connect 事件监听器
     @return 返回连接的 Socket 对象
     */
    Stream connect(Object options, Function connectListener) async;

    /*! @brief 将当前 Socket 绑定至本地所有地址的指定端口
     @param port 指定绑定的端口
     @param allowIPv4 指定是否接受 ipv4 连接，缺省为 true。本参数在 ipv6 时有效，并依赖于操作系统
     */
    bind(Integer port, Boolean allowIPv4 = true);

    /*! @brief 将当前 Socket 绑定至指定地址的指定端口
     @param addr 指定绑定的地址，也可以指向 unix socket 和 Windows pipe 路径
     @param port 指定绑定的端口，绑定 unix socket 和 Windows pipe 时，忽略此参数
     @param allowIPv4 指定是否接受 ipv4 连接，缺省为 true。本参数在 ipv6 时有效，并依赖于操作系统
     */
    bind(String addr, Integer port = 0, Boolean allowIPv4 = true);

    /*! @brief 开始监听连接请求
     @param backlog 指定请求队列长度，超出的请求将被拒绝，缺省为 120
     */
    listen(Integer backlog = 120);

    /*! @brief 等待并接受一个连接
     @return 返回接收到得连接对象
     */
    Socket accept() async;

    /*! @brief 启用或禁用 TCP 保持活动机制
     @param enable 指定是否启用保持活动机制，缺省为 false
     @param initialDelay 指定初始延迟时间，单位为秒，缺省为 0
     */
    setKeepAlive(Boolean enable = false, Integer initialDelay = 0);

    /*! @brief 启用或禁用 Nagle 算法
     @param noDelay 指定是否禁用 Nagle 算法，缺省为 true
     */
    setNoDelay(Boolean noDelay = true);

    /*! @brief 从连接读取指定大小的数据，不同于 read 方法，recv 并不保证读完要求的数据，而是在读取到数据后立即返回
     @param bytes 指定要读取的数据量，缺省读取任意尺寸的数据
     @return 返回从连接读取的数据
     */
    Buffer recv(Integer bytes = -1) async;

    /*! @brief 将给定的数据写入连接，此方法等效于 write 方法
     @param data 给定要写入的数据
     @return 返回实际写入的字节数
     */
    Integer send(Buffer data) async;

    /*! @brief 中止当前 socket 上所有正在进行的操作
     
     此方法会取消所有正在等待的异步操作（connect, recv, send 等），
     被取消的操作会返回错误。socket 本身不会被关闭，可以继续使用。
     */
    abort();
};
