/*! @brief TextEncoder 编码对象

 创建方法
 ```JavaScript
 var textEncoder = new util.TextEncoder('utf8');
 ```
 */
interface TextEncoder : object
{
    /*! @brief TextEncoder 对象构造函数，使用参数构造
	 @param codec 指定编码字符集
 	 @param opts 指定编码选项
     */
    TextEncoder(String codec = "utf8", Object opts = {});

    /*! @brief 将文本转换为二进制数据
	 @param data 要转换的文本
 	 @param opts 指定编码选项
	 @return 返回编码的二进制数据
	 */
    Buffer encode(String data = "", Object opts = {});

    /*! @brief 查询当前的编码字符集 */
    readonly String encoding;
};
