/*! @brief url 处理模块 */
module url
{
    /*! @brief 参数构造 UrlObject 对象
     @param args 指定构造参数的字典对象，支持的字段有：protocol, slashes, username, password, hostname, port, pathname, query, hash
     @return 返回构造成功的字符串
     */
    static String format(Object args);

    /*! @brief 解析一个 url 字符串
     @param url 指定需要解析的 url 字符串
     @param parseQueryString 指定是否解析 query
     @return 返回包含解析数据的对象
     */
    static UrlObject parse(String url, Boolean parseQueryString = false);
};
