
/*! @brief WebSocket 包协议转换处理器

  用以将 Http 协议转换为 WebSocket 包协议消息。创建方式：
  ```JavaScript
  var ws = require("ws");

  var pkghdlr = new ws.WebSocketHandler(...);
  ```
 */
interface WebSocketHandler : HandlerEx
{
    /*! @brief WebSocket 包处理器构造函数
     @param hdlr 内置消息处理器，处理函数，链式处理数组，路由对象，详见 mq.Handler
     */
    deprecated WebSocketHandler(Handler hdlr);

    /*! @brief 查询和设置最大包尺寸，以 MB 为单位，缺省为 64 */
    Integer maxSize;
};
