/*! @brief worker 基础模块

 引用方法：
 ```JavaScript
 var worker_threads = require('worker_threads');
 ```
 */
module worker_threads
{
    /*! @brief 独立线程工作对象，参见 Worker */
    static Worker;

    /*! @brief 查询当前 Worker 是不是主线程 */
    static readonly Boolean isMainThread;

    /*! @brief 查询当前 Worker 的父线程 */
    static readonly Worker parentPort;

    /*! @brief 查询父线程通过 Worker 构造函数传给该线程的的数据的克隆 */
    static readonly Value workerData;
};
