if(${OS} STREQUAL "Linux")
	if(zlib_found)
		message(STATUS "*** Use system wide installed zlib. ***")
		set(flags "${flags} ${zlib_cflags}")
		set(link_flags "${link_flags} ${zlib_ldflags}")
	else()
		message(STATUS "*** Use our provided zlib. ***")
		include_directories(BEFORE SYSTEM "${PROJECT_SOURCE_DIR}/../../vender/include/zlib")
	endif()
else()
	message(STATUS "*** Use our provided zlib. ***")
	include_directories(BEFORE SYSTEM "${PROJECT_SOURCE_DIR}/../../vender/include/zlib")
endif()
