#!/usr/bin/env fibjs
/**
 * check.js — the type checker behind `fibjs --check`.
 *
 * The driver is hand-written: it requires the trimmed TypeScript compiler and
 * the lib.*.d.ts data from `internal/tsc-libs` (generated by tools/gen_tsc.js)
 * and owns every fibjs specific behavior:
 *
 *   - the fibjs built-in types (the @fibjs/types corpus embedded as
 *     `internal/fibjs-types`) are attached to every program as root files and
 *     served through the compiler host; their own diagnostics are dropped (the
 *     types ship with the runtime and are not the project's to fix);
 *   - the default lib is es-only: lib.dom would shadow WebSocket, URL, fetch,
 *     console, ... with browser types that do not match the runtime. A project
 *     that lists DOM in its tsconfig `lib` is a browser project and keeps the
 *     browser types: the built-in types are not attached to it;
 *   - @types/node never joins a checked program: a dependency's `/// <reference
 *     types="node" />` (undici-types carries one), a `types` entry naming node,
 *     and a `types: ["*"]` type-roots scan that finds the package are all
 *     refused - the program runs against its environment (the built-in types,
 *     or the browser types of a DOM project) and node-only globals (process,
 *     Buffer, ...) do not type-check. A node-targeted project checks with
 *     stock tsc instead (--no-builtin-types);
 *   - a tsconfig with `references` is checked project by project, each with its
 *     own tsconfig (the `tsc -b --noEmit` equivalent, usable as the monorepo
 *     root check);
 *   - --no-builtin-types turns the built-in types off, giving stock tsc
 *     behavior (including the default lib with lib.dom);
 *   - --allowJs and --allowImportingTsExtensions are always on and emit is
 *     always off.
 *
 * The compiler module is only *trimmed* (no emit code) and keeps one behavior
 * change, the same-name .js/.ts shadowing rule; see tools/gen_tsc.js.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const compiler = require('internal/tsc-libs');
const ts = compiler.tsc;
const libFiles = compiler.libs;
const builtinTypeFiles = require('internal/fibjs-types').files;

// The built-in types are attached under the package name: the corpus is the
// @fibjs/types package, and its relative `/// <reference path="..." />` lines
// resolve inside this virtual directory. The label is the same string from any
// working directory, so nothing is anchored to the project layout.
const BUILTIN_ROOT = '@fibjs/types';
// Where the (virtual) lib.*.d.ts files live.
const LIB_ROOT = '@fibjs/lib';

const EXIT_SUCCESS = 0;
const EXIT_USAGE = 1;
const EXIT_DIAGNOSTICS = 2;

// The compiler's pseudo containing file for `types` entries (named ones and
// the `"*"` type-roots scan): the checker tells those refusals apart from the
// `/// <reference types="node" />` directives in files by it (see createHost).
const INFERRED_TYPES_FILE = '__inferred type names__.ts';

const USAGE = [
    'Usage: fibjs --check [options] <files...>',
    '',
    'Run the TypeScript compiler in check-only mode on the given .ts/.js files,',
    'or on the project when no files are given.',
    '',
    'Options:',
    '  -h, --help                  print this message, then the compiler option',
    '                              list tsc documents for itself',
    '',
    'fibjs differences from tsc:',
    '  --allowJs and --allowImportingTsExtensions are always enabled, so .js files',
    '  are checked too; the lib.d.ts files and the types of the fibjs built-in',
    '  modules (http, fs, ...) are embedded in the binary; the same-name',
    '  shadowing rule is patched out (stock tsc drops a .js file when a',
    '  same-named .ts file exists in the project).',
    '',
    '  --no-builtin-types          do not attach the embedded fibjs built-in',
    '                              runtime types to the program; stock tsc',
    '                              defaults apply then, lib.dom included',
    '',
    '  --pretty                    colorize diagnostics (default: when stdout is',
    '                              a terminal)',
    '',
    '  the default lib of a checked project is es-only (`lib.es2020.d.ts`, not',
    '  `lib.es2020.full.d.ts`): lib.dom would shadow WebSocket, URL, fetch,',
    '  console, ... with browser types that do not match the runtime.',
    '',
    '  a project that lists DOM in its `lib` is a browser project: the built-in',
    '  types are skipped for it (the browser types are the ones it runs',
    '  against). A repository that has both keeps them apart with one tsconfig',
    '  per area - the front-end directory lists DOM, the back end does not and',
    '  keeps the runtime types.',
    '',
    '  a checked program never carries @types/node: a `/// <reference',
    '  types="node" />` in a dependency (undici-types carries one), a `types`',
    '  entry naming node, and a `types: ["*"]` type-roots scan that finds the',
    '  package are all refused - the program runs against its environment (the',
    '  built-in types, or the browser types of a DOM project), so node-only',
    '  globals (process, Buffer, ...) do not type-check. A node-targeted',
    '  project checks with stock tsc instead: --no-builtin-types, or "fibjs":',
    '  { "builtinTypes": false } in its tsconfig.',
    '',
    '  a project opts out of the built-in types with "fibjs": { "builtinTypes":',
    '  false } in its tsconfig; the --no-builtin-types flag does the same for',
    '  every project.',
    '',
    '  a tsconfig with `references` is checked project by project, each with its',
    '  own tsconfig (the `tsc -b --noEmit` equivalent); `-b` itself is not',
    '  supported.',
    '',
    'Run `fibjs --help` for the global options.',
];

// ---------------------------------------------------------------------------
// small helpers

function write(text) {
    ts.sys.write(text);
}

function hasArg(args, names) {
    return args.some(arg => names.indexOf(arg) >= 0);
}

function normalizeSlashes(fileName) {
    return String(fileName).replace(/\\/g, '/');
}

function optionsFrom(args) {
    // the CLI options, without the fibjs specific flags (consumed here)
    const pass = [];
    let useBuiltinTypes = true;

    args.forEach(arg => {
        if (arg === '--no-builtin-types')
            useBuiltinTypes = false;
        else
            pass.push(arg);
    });

    return { args: pass, useBuiltinTypes };
}

// ---------------------------------------------------------------------------
// diagnostics

/**
 * Program diagnostics the way getPreEmitDiagnostics() does it: config file
 * diagnostics, then syntax, then options/global, then semantics - the later
 * groups only when the earlier ones are empty, so a file with syntax errors
 * does not also report the semantics it broke.
 */
function preEmitDiagnostics(program) {
    const diagnostics = program.getConfigFileParsingDiagnostics().slice();
    const configCount = diagnostics.length;

    diagnostics.push(...program.getSyntacticDiagnostics());

    if (diagnostics.length === configCount) {
        diagnostics.push(...program.getOptionsDiagnostics());
        diagnostics.push(...program.getGlobalDiagnostics());

        if (diagnostics.length === configCount)
            diagnostics.push(...program.getSemanticDiagnostics());
    }

    return diagnostics;
}

function isBuiltinTypeFile(fileName) {
    return normalizeSlashes(fileName).startsWith(BUILTIN_ROOT + '/');
}

// The compiler reports an unresolved type reference directive as TS2688
// ("Cannot find type definition file for 'node'"). When the checker refused
// the node types on purpose, the diagnostic is misleading - the package is
// usually installed, the program simply does not carry it - and the refusal
// note is the one to read; every other TS2688 (a genuinely missing package)
// stays.
function isRefusedNodeTypesDiagnostic(diagnostic) {
    return diagnostic.code === 2688 &&
        ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n').indexOf("'node'") >= 0;
}

// ---------------------------------------------------------------------------
// where an unlisted file comes from

/**
 * A project checks the files it lists, but the program reaches more: whatever
 * those files import, plus whatever their dependencies reference. When a
 * diagnostic lands in such a file - a front-end module pulled into the back
 * end, a generated file, a dependency's .d.ts - the path is not in the tsconfig
 * and the file name alone does not say who brought it in.
 *
 * The graph is the compiler's own: `resolveModuleNameLiterals` is the host hook
 * the compiler resolves through, and the callback hands every resolution to
 * `ts.resolveModuleName` with the mode `ts.getModeForUsageLocation` derives -
 * the compiler's resolver and the compiler's rule. The program therefore
 * resolves exactly what the graph records; nothing is re-scanned by hand and no
 * second resolver can drift from the first.
 *
 * The chain is the shortest path found by a breadth-first walk from the listed
 * files, each hop with the line that imports the next one.
 */
const IMPORTED_CHAIN_MAX_FILES = 12;
const IMPORTED_CHAIN_MAX_DEPTH = 8;

function importChainsFor(edges, rootNames, targets) {
    const outgoing = new Map();

    edges.forEach(edge => {
        const list = outgoing.get(edge.from);

        if (list)
            list.push(edge);
        else
            outgoing.set(edge.from, [edge]);
    });

    const wanted = new Set(targets);
    const parent = new Map();
    const queue = [];

    rootNames.map(normalizeSlashes).forEach(fileName => {
        if (!parent.has(fileName)) {
            parent.set(fileName, null);
            queue.push(fileName);
        }
    });

    for (let head = 0; head < queue.length && wanted.size; head++) {
        const fileName = queue[head];
        const depth = parent.get(fileName) ? parent.get(fileName).depth + 1 : 0;

        if (depth >= IMPORTED_CHAIN_MAX_DEPTH)
            continue;

        (outgoing.get(fileName) || []).forEach(edge => {
            if (parent.has(edge.to))
                return;

            parent.set(edge.to, { from: fileName, line: edge.line, depth: depth });
            queue.push(edge.to);
            wanted.delete(edge.to);
        });
    }

    const chains = new Map();

    targets.forEach(target => {
        if (!parent.has(target))
            return;

        const hops = [];

        for (let at = target; parent.get(at); at = parent.get(at).from)
            hops.push(parent.get(at));

        chains.set(target, hops.reverse());
    });

    return chains;
}

function reportImportedFiles(graph, rootNames, diagnostics) {
    const listed = new Set(rootNames.map(normalizeSlashes));
    const targets = [];

    diagnostics.forEach(diagnostic => {
        if (!diagnostic.file)
            return;

        const fileName = normalizeSlashes(diagnostic.file.fileName);

        if (listed.has(fileName) || isBuiltinTypeFile(fileName) || fileName.startsWith(LIB_ROOT + '/'))
            return;

        if (targets.indexOf(fileName) < 0)
            targets.push(fileName);
    });

    if (!targets.length)
        return;

    const chains = importChainsFor(graph, rootNames, targets.slice(0, IMPORTED_CHAIN_MAX_FILES));

    write('\nthe files below are not listed in the project - what is listed reaches them through imports:\n');

    targets.slice(0, IMPORTED_CHAIN_MAX_FILES).forEach(target => {
        const hops = chains.get(target);

        if (!hops || !hops.length) {
            write(`  ${target}\n    (no import path found: a reference or an explicit \`types\` entry pulls it in)\n`);
            return;
        }

        write(`  ${target}\n`);
        write('    ' + hops.map(hop => hop.from + ':' + hop.line).join('\n      -> ') +
            '\n      -> ' + target + '  (here)\n');
    });

    if (targets.length > IMPORTED_CHAIN_MAX_FILES)
        write(`  ... and ${targets.length - IMPORTED_CHAIN_MAX_FILES} more unlisted files\n`);
}

/**
 * The plain (non pretty) diagnostic form tsc prints:
 *   path(line,col): error TS1234: message
 * Category values come from the DiagnosticCategory enum, whose numeric values
 * are stable public API (0 warning, 1 error, 2 suggestion, 3 message).
 */
function formatDiagnostic(diagnostic) {
    let text = '';

    if (diagnostic.file && typeof diagnostic.start === 'number') {
        const position = ts.getLineAndCharacterOfPosition(diagnostic.file, diagnostic.start);
        text += diagnostic.file.fileName + '(' + (position.line + 1) + ',' + (position.character + 1) + '): ';
    }

    const category = diagnostic.category === 1 ? 'error'
        : diagnostic.category === 0 ? 'warning'
            : diagnostic.category === 2 ? 'suggestion'
                : 'message';

    text += category + ' TS' + diagnostic.code + ': ';
    text += ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n');

    return text + '\n';
}

function report(diagnostics, pretty) {
    if (!diagnostics.length)
        return;

    if (pretty) {
        write(ts.formatDiagnosticsWithColorAndContext(diagnostics, {
            getCanonicalFileName: fileName => fileName,
            getCurrentDirectory: () => ts.sys.getCurrentDirectory(),
            getNewLine: () => '\n',
        }));
    } else {
        diagnostics.forEach(diagnostic => write(formatDiagnostic(diagnostic)));
    }

    const files = new Set();
    diagnostics.forEach(diagnostic => {
        if (diagnostic.file)
            files.add(diagnostic.file.fileName);
    });

    const errors = diagnostics.filter(d => d.category === 1).length;
    write('\nFound ' + diagnostics.length + ' error' + (diagnostics.length === 1 ? '' : 's') +
        (files.size === 1 ? ' in the same file' : files.size ? ' in ' + files.size + ' files' : '') + '.\n');
}

// ---------------------------------------------------------------------------
// the compiler host

/**
 * The host serves three layers: the fibjs built-in types and the bundled lib
 * files (both virtual, keyed by path / by file name) and the real file system.
 */
function createHost(options, virtual, graph, blockNodeTypeReferences) {
    const host = ts.createCompilerHost(options, /* setParentNodes */ true);
    const served = host.getSourceFile.bind(host);
    const fileExists = host.fileExists.bind(host);
    const readFile = host.readFile.bind(host);

    // The bundled libs are served under the lib root only
    // (`@fibjs/lib/lib.es2020.d.ts`). Matching by base name would hijack any
    // file that happens to share a lib's name - `lib.d.ts` is a common name
    // inside node_modules, and the TypeScript default lib of that name pulls
    // in lib.dom through its own reference directives, so a dependency would
    // silently be replaced by the browser lib.
    function virtualText(fileName) {
        const normalized = normalizeSlashes(fileName);

        if (virtual[normalized] !== undefined)
            return virtual[normalized];

        if (!normalized.startsWith(LIB_ROOT + '/'))
            return undefined;

        return libFiles[normalized.slice(LIB_ROOT.length + 1)];
    }

    host.fileExists = fileName => virtualText(fileName) !== undefined || fileExists(fileName);

    host.readFile = fileName => {
        const text = virtualText(fileName);
        return text !== undefined ? text : readFile(fileName);
    };

    host.getSourceFile = (fileName, languageVersion, onError, shouldCreateNewSourceFile) => {
        const text = virtualText(fileName);

        if (text !== undefined)
            return ts.createSourceFile(fileName, text, languageVersion, true);

        return served(fileName, languageVersion, onError, shouldCreateNewSourceFile);
    };

    host.getDefaultLibLocation = () => LIB_ROOT;
    host.getDefaultLibFileName = opts => LIB_ROOT + '/' + ts.getDefaultLibFileName(opts);

    // @types/node does not belong to a checked program: the built-in types are
    // the environment of a fibjs program, the browser types the ones of a DOM
    // project, and the node globals would fight either set. Every route is
    // refused here: a dependency's `/// <reference types="node" />`
    // (undici-types, reached through @anthropic-ai/sdk, is the known source -
    // it resolves against the type roots, primary and secondary, and ignores
    // the project's `types` list), a `types` entry naming node, and a
    // `types: ["*"]` type-roots scan; every other directive goes through the
    // compiler's own resolver, and the refused ones are reported after the
    // program is built.
    //
    // The callback is the plural `...References` form: the compiler binds it
    // as-is and hands it the program's own file references, so the delegate
    // result (the resolver's `{ resolvedTypeReferenceDirective, ... }`) is
    // returned untouched; the names-only form would wrap the entries a second
    // time and the program would read the file name off the wrapper.
    if (blockNodeTypeReferences) {
        host.refusedNodeTypeReferences = [];
        host.refusedNodeTypeAutoIncludes = [];

        host.resolveTypeReferenceDirectiveReferences = (entries, containingFile, redirectedReference, compilerOptions, containingSourceFile) =>
            entries.map(entry => {
                const name = typeof entry === 'string' ? entry : entry.fileName;

                if (name !== 'node' && name.indexOf('node/') !== 0)
                    return ts.resolveTypeReferenceDirective(name, containingFile, compilerOptions,
                        host, redirectedReference, /* cache */ undefined,
                        containingSourceFile && containingSourceFile.impliedNodeFormat);

                // the `types` entries resolve with the compiler's pseudo
                // file as the containing file; a directive resolves with the
                // file that wrote it. One entry is enough for the note below.
                const refused = normalizeSlashes(containingFile).indexOf(INFERRED_TYPES_FILE) >= 0
                    ? host.refusedNodeTypeAutoIncludes
                    : host.refusedNodeTypeReferences;

                if (!refused.length)
                    refused.push(normalizeSlashes(containingFile));

                return { resolvedTypeReferenceDirective: undefined };
            });
    }

    // the compiler resolves through this callback; recording every result
    // there is what makes the reported import chain the checked one
    const resolutions = new Map();

    host.resolveModuleNameLiterals = (literals, containingFile, redirectedReference, compilerOptions, containingSourceFile) => {
        const from = normalizeSlashes(containingFile);

        return literals.map(literal => {
            const key = from + '\u0000' + literal.text;
            let resolution = resolutions.get(key);

            if (resolution === undefined) {
                let mode;

                try {
                    mode = ts.getModeForUsageLocation(containingSourceFile || literal.getSourceFile(), literal, compilerOptions);
                } catch (e) {
                    mode = undefined;
                }

                resolution = ts.resolveModuleName(literal.text, containingFile, compilerOptions, host, undefined, redirectedReference, mode);
                resolutions.set(key, resolution);
            }

            const resolvedFile = resolution && resolution.resolvedModule && resolution.resolvedModule.resolvedFileName;

            if (resolvedFile && graph) {
                // the compiler does not hand the containing source file to the
                // callback in every version: the literal knows it (the host
                // parses with parent nodes), and the line is a nicety - a hop
                // without one is still a hop
                let line = 1;

                try {
                    line = ts.getLineAndCharacterOfPosition(literal.getSourceFile(), literal.getStart()).line + 1;
                } catch (e) {
                    line = 1;
                }

                graph.push({
                    from: from,
                    to: normalizeSlashes(resolvedFile),
                    line: line,
                });
            }

            return resolution;
        });
    };

    return host;
}

// ---------------------------------------------------------------------------
// project handling

function configFileIn(dir) {
    for (const name of ['tsconfig.json', 'jsconfig.json']) {
        const candidate = path.join(dir, name);

        if (ts.sys.fileExists(candidate))
            return candidate;
    }

    return undefined;
}

function projectConfigPath(projectPath) {
    const resolved = path.resolve(projectPath);

    if (ts.sys.fileExists(resolved))
        return resolved;

    return configFileIn(resolved);
}

/**
 * @returns {{options, fileNames, configPath?, references?, errors}}
 */
function loadProject(configPath, cliOptions, configDiagnostics) {
    const parseHost = Object.assign({}, ts.sys, {
        onUnRecoverableConfigFileDiagnostic: diagnostic => configDiagnostics.push(diagnostic),
    });

    const parsed = ts.getParsedCommandLineOfConfigFile(configPath, cliOptions, parseHost);

    if (!parsed)
        return undefined;

    return {
        options: parsed.options,
        fileNames: parsed.fileNames.slice(),
        configErrors: parsed.errors.slice(),
        references: (parsed.projectReferences || []).map(reference => reference.path),
        raw: parsed.raw,
    };
}

/**
 * Whether the project's effective `lib` names DOM: those are the types a
 * browser project runs against, so the fibjs built-in types stay off for it
 * (see the `projectBuiltinTypes` rule in checkProject).
 *
 * Only an explicit `lib` counts: a project without one gets the es-only
 * default lib, which the runtime types complete. A tsconfig that spells DOM
 * out is a browser project by choice.
 */
function projectTargetsBrowser(options) {
    return Array.isArray(options.lib) &&
        options.lib.some(lib => /^lib\.dom(\.|$)/i.test(lib));
}

/**
 * The lib list a project without an explicit `lib` runs with: the es-only
 * variant of the target's default (`lib.es2020.d.ts` in place of
 * `lib.es2020.full.d.ts`). lib.dom would otherwise come in with the compiler
 * defaults and collide with the built-in globals; a project that wants the
 * browser types lists DOM in its `lib` like any browser project.
 */
function defaultLibFor(options) {
    const name = ts.getDefaultLibFileName(options);

    if (name === 'lib.d.ts')
        return ['lib.es5.d.ts'];

    return [name.replace(/\.full\.d\.ts$/, '.d.ts')];
}

// ---------------------------------------------------------------------------
// checking one project

function checkProject(request) {
    const { cliOptions, cliFiles, useBuiltinTypes, visited, pretty } = request;

    // a project given explicitly, or the current directory when no files are
    const projectPath = request.projectPath !== undefined ? request.projectPath : process.cwd();
    const configPath = request.projectPath !== undefined
        ? projectConfigPath(projectPath)
        : cliFiles.length ? undefined : configFileIn(projectPath);

    const configDiagnostics = [];
    let project;

    if (configPath) {
        const key = path.resolve(configPath);

        if (visited[key])
            return EXIT_SUCCESS;
        visited[key] = true;

        project = loadProject(configPath, cliOptions, configDiagnostics);

        if (!project) {
            report(configDiagnostics, pretty);
            return EXIT_USAGE;
        }
    }

    const options = Object.assign({}, project ? project.options : cliOptions, {
        // fibjs --check never emits, and always checks .js files too
        noEmit: true,
        allowJs: true,
        allowImportingTsExtensions: true,
    });
    const fileNames = project ? project.fileNames : cliFiles;

    // tsconfig.json is present but the command line lists files: tsc reports
    // this warning (same wording) and keeps going with the command line only
    const extraDiagnostics = [];

    if (!project && cliFiles.length && !cliOptions.ignoreConfig && configFileIn(process.cwd()))
        extraDiagnostics.push(ts.createCompilerDiagnostic(
            ts.Diagnostics.tsconfig_json_is_present_but_will_not_be_loaded_if_files_are_specified_on_commandline_Use_ignoreConfig_to_skip_this_error
        ));

    // project references: check each referenced project with its own tsconfig
    if (project && project.references && project.references.length && !cliFiles.length) {
        let status = EXIT_SUCCESS;

        project.references.forEach(projectPath => {
            const code = checkProject(Object.assign({}, request, { projectPath }));

            if (code !== EXIT_SUCCESS && status === EXIT_SUCCESS)
                status = code;
        });

        return status;
    }

    const virtual = {};
    const rootNames = fileNames.slice();

    // A project opts out of the built-in types in its own tsconfig:
    //
    //   "fibjs": { "builtinTypes": false }
    //
    // Front-end directories use it to keep the browser types. A project that
    // spells DOM out in its `lib` is a browser project too: the built-in
    // types are not attached then - the browser types are the ones it runs
    // against, and the two global sets would conflict. The CLI flag
    // --no-builtin-types turns the built-in types off for every project.
    const fibjsConfig = project && project.raw && project.raw.fibjs;
    const explicitBuiltinTypes = fibjsConfig && typeof fibjsConfig.builtinTypes === 'boolean'
        ? fibjsConfig.builtinTypes
        : undefined;
    const browserProject = projectTargetsBrowser(options);
    const projectBuiltinTypes = useBuiltinTypes &&
        explicitBuiltinTypes !== false && !browserProject;

    if (browserProject && useBuiltinTypes && explicitBuiltinTypes !== false)
        write('note: the project lists DOM in `lib` - the fibjs built-in types are not attached\n');

    // @types/node never joins a checked program. Whenever the driver supplies
    // the program's type environment (the fibjs built-in types, or the browser
    // types of a DOM project), every route to it is refused: a dependency's
    // `/// <reference types="node" />` (undici-types carries one - it resolves
    // against the type roots and ignores the project's `types` list), a
    // `types` entry naming node, and a `types: ["*"]` type-roots scan. The node
    // globals would otherwise join the built-in ones (a class mismatch on
    // every Buffer, WebSocket, ...) or leak node-only globals (process,
    // Buffer, ...) into browser code. A node-targeted project checks with
    // stock tsc instead (--no-builtin-types, or "fibjs": { "builtinTypes":
    // false } in its tsconfig).
    const blockNodeTypeReferences = useBuiltinTypes && explicitBuiltinTypes !== false;

    // a fibjs project without an explicit `lib` gets the es-only default lib:
    // lib.dom must not slip in through the compiler defaults and collide with
    // the built-in globals (see defaultLibFor)
    if (projectBuiltinTypes && options.lib === undefined)
        options.lib = defaultLibFor(options);

    if (projectBuiltinTypes) {
        Object.keys(builtinTypeFiles).forEach(rel => {
            virtual[normalizeSlashes(path.join(BUILTIN_ROOT, rel))] = builtinTypeFiles[rel];
        });

        Object.keys(virtual).forEach(root => rootNames.push(root));
    }

    if (cliOptions.showConfig) {
        write(JSON.stringify({
            compilerOptions: options,
            files: rootNames,
            references: project ? project.references : undefined,
        }, null, 2) + '\n');
        return EXIT_SUCCESS;
    }

    const graph = [];
    const host = createHost(options, virtual, graph, blockNodeTypeReferences);
    const program = ts.createProgram({
        rootNames,
        options,
        host,
        projectReferences: project ? project.references : undefined,
        configFileParsingDiagnostics: project ? project.configErrors : [],
    });

    if (options.listFilesOnly || options.listFiles) {
        program.getSourceFiles().forEach(sourceFile => write(sourceFile.fileName + '\n'));

        if (options.listFilesOnly)
            return EXIT_SUCCESS;
    }

    if (host.refusedNodeTypeReferences && host.refusedNodeTypeReferences.length)
        write('note: the program references the node types (`/// <reference types="node" />`) - ' +
            'the reference is not resolved; a checked program does not carry @types/node\n');

    if (host.refusedNodeTypeAutoIncludes && host.refusedNodeTypeAutoIncludes.length)
        write('note: the project\'s `types` would load @types/node (a named entry or the "*" scan) - ' +
            'not loaded; a checked program does not carry @types/node (use --no-builtin-types ' +
            'for a node-targeted project)\n');

    // lib.dom can be pulled into the program by a `/// <reference lib="dom" />`
    // even when the tsconfig does not list it; the browser globals then fight
    // the built-in ones in the same program and the visible errors are
    // confusing (setTimeout typed as the browser one, ...). Say it instead of
    // leaving the mix unexplained.
    if (projectBuiltinTypes &&
        program.getSourceFiles().some(sourceFile => /\/lib\.dom\.d\.ts$/.test(normalizeSlashes(sourceFile.fileName))))
        write('note: lib.dom is in the program (a file references the DOM lib) while the fibjs built-in types are attached - the two global sets conflict; list DOM in `lib` for the browser types, or drop the reference\n');

    const diagnostics = preEmitDiagnostics(program)
        .filter(diagnostic => !(diagnostic.file && isBuiltinTypeFile(diagnostic.file.fileName)))
        .filter(diagnostic => !(blockNodeTypeReferences && isRefusedNodeTypesDiagnostic(diagnostic)));

    const all = extraDiagnostics.concat(diagnostics);

    report(all, pretty);

    // A diagnostic may land in a file the project never listed: whatever the
    // listed files import is checked too, and a front-end module pulled into
    // the back end (or the other way round) reads like a project file. The
    // import chain says who brought it in.
    reportImportedFiles(graph, fileNames, all);

    return all.length ? EXIT_DIAGNOSTICS : EXIT_SUCCESS;
}

// ---------------------------------------------------------------------------
// main

function main(argv) {
    const { args, useBuiltinTypes } = optionsFrom(argv);

    if (hasArg(args, ['-h', '--help'])) {
        write(USAGE.join('\n') + '\n');
        ts.printHelp(ts.sys, ts.parseCommandLine(args, ts.sys.readFile));
        return EXIT_SUCCESS;
    }

    const commandLine = ts.parseCommandLine(args, ts.sys.readFile);

    if (commandLine.errors.length) {
        report(commandLine.errors, false);
        return EXIT_USAGE;
    }

    const options = commandLine.options;

    if (options.version) {
        write('Version ' + ts.version + '\n');
        return EXIT_SUCCESS;
    }

    if (options.init) {
        write('fibjs --check: --init is not supported\n');
        return EXIT_USAGE;
    }

    if (options.build) {
        write('fibjs --check: -b/--build is not supported; run the check on the project\n' +
            '(a tsconfig with `references` is checked project by project automatically)\n');
        return EXIT_USAGE;
    }

    if (options.watch) {
        write('fibjs --check: --watch is not supported\n');
        return EXIT_USAGE;
    }

    const pretty = options.pretty !== undefined
        ? !!options.pretty
        : !!(ts.sys.writeOutputIsTTY && ts.sys.writeOutputIsTTY());

    return checkProject({
        projectPath: options.project,
        cliOptions: options,
        cliFiles: commandLine.fileNames,
        useBuiltinTypes,
        pretty,
        visited: {},
    });
}

process.exit(main(process.argv.slice(2)));
