#!/bin/bash

# This script must be called from the root build script which sets WORK_ROOT
if [[ -z "$WORK_ROOT" ]]; then
    echo "Error: This script must be executed from the root build script."
    echo "Please run: cd $(dirname "$(dirname "$(realpath "$0")")") && ./build [options]"
    exit 1
fi

. ../vender/build_tools/scripts/build
