/*! @brief base58 encoding and decoding module

 `base58` module is a module for Base58 encoding and decoding of data. Base58 is a representation method combining numbers and letters, which does not contain confusing characters such as the number 0, letter O, letter I, letter l, etc., and has the characteristic of being error-resistant.

 This module provides two methods: `encode` and `decode`. The `encode` method is used to perform Base58 encoding on the given data and return the encoded string. The `decode` method is used to decode the given Base58 encoded string and return the decoded binary data.

 Below is the example code for the `base58` module:
 ```JavaScript
 var base58 = require('base58');

 var data = "Hello, World!";
 var encoded = base58.encode(data);
 console.log(encoded); // => 'StV1DL6CwTryKyV'

 var decoded = base58.decode(encoded);
 console.log(decoded.toString()); // => 'hello world'
 ```
 */
module base58
{
    /*! @brief Encode data in base58 way
	 @param data The data to encode
	 @return Return the encoded string
	 */
    static String encode(Buffer data);

    /*! @brief Encode data in base58check way
	 @param data The data to encode
	 @param chk_ver Specify the check version
	 @return Return the encoded string
	 */
    static String encode(Buffer data, Integer chk_ver);

    /*! @brief Decode string to binary data in base58 way
	 @param data The string to decode
	 @return Return the decoded binary data
	 */
    static Buffer decode(String data);

    /*! @brief Decode string to binary data in base58check way
	 @param data The string to decode
	 @param chk_ver Specify the check version
	 @return Return the decoded binary data
	 */
    static Buffer decode(String data, Integer chk_ver);
};