/*! @brief Binary data buffer object for IO read/write data processing

 The Buffer object is a global base class that can be created directly with new Buffer(...) at any time:
 ```JavaScript
 var buf = new Buffer();
 ```
 */
interface Buffer : object
{
    /*! @brief Binary data buffer object for IO read/write data processing */
    static Buffer;

    /*! @brief Buffer object constructor
     @param datas Initialization data array
     */
    Buffer(Array datas);

    /*! @brief Buffer object constructor
     @param datas Initialization data array
     @param byteOffset Specifies the data start position, starting from 0
     @param length Specifies the data length, starting from -1, indicating all remaining data
     */
    Buffer(ArrayBuffer datas, Integer byteOffset = 0, Integer length = -1);

    /*! @brief Buffer object constructor
     @param datas Initialization data array
     @param byteOffset Specifies the data start position, starting from 0
     @param length Specifies the data length, starting from -1, indicating all remaining data
     */
    Buffer(Uint8Array datas, Integer byteOffset = 0, Integer length = -1);

    /*! @brief Buffer object constructor
     @param str Initialization string, the string will be written in utf-8 format, if omitted, an empty object is created
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     */
    Buffer(String str, String codec = "utf8");

    /*! @brief Buffer object constructor
     @param size Initialization buffer size
     */
    Buffer(Integer size = 0);

    /*! @brief Allocates a new buffer of the specified length. If the size is 0, a zero-length buffer is created.
     @param size The desired length of the buffer
     @param fill The value to pre-fill the new buffer with, can use string/buffer/integer value types. Default: 0
     @return The filled new Buffer object
    */
    static Buffer alloc(Integer size, Integer fill = 0);

    /*! @brief Allocates a new buffer of the specified length. If the size is 0, a zero-length buffer is created.
     @param size The desired length of the buffer
     @param fill The value to pre-fill the new buffer with, can use string/buffer/integer value types. Default: 0
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return The filled new Buffer object
    */
    static Buffer alloc(Integer size, String fill = "", String codec = "utf8");

    /*! @brief Allocates a new buffer of the specified length. If the size is 0, a zero-length buffer is created.
     @param size The desired length of the buffer
     @param fill The value to pre-fill the new buffer with, can use string/buffer/integer value types. Default: 0
     @return The filled new Buffer object
    */
    static Buffer alloc(Integer size, Buffer fill);

    /*! @brief Allocates a new buffer of the specified length. If the size is 0, a zero-length buffer is created.
     @param size The desired length of the buffer
     @return The new Buffer object of specified size
    */
    static Buffer allocUnsafe(Integer size);

    /*! @brief Allocates a new buffer of the specified length. If the size is 0, a zero-length buffer is created.
     @param size The desired length of the buffer
     @return The new Buffer object of specified size
    */
    static Buffer allocUnsafeSlow(Integer size);

    /*! @brief Creates a Buffer object from the given array
     @param datas Initialization data array
     @return Returns Buffer instance
     */
    static Buffer from(Array datas);

    /*! @brief Creates a Buffer object from another Buffer
     @param buffer Given Buffer type variable to create Buffer object
     @param byteOffset Specifies the data start position, starting from 0
     @param length Specifies the data length, starting from -1, indicating all remaining data
     @return Returns Buffer instance
     */
    static Buffer from(Buffer buffer, Integer byteOffset = 0, Integer length = -1);

    /*! @brief Creates a Buffer object from another Buffer
     @param datas Initialization data array
     @param byteOffset Specifies the data start position, starting from 0
     @param length Specifies the data length, starting from -1, indicating all remaining data
     @return Returns Buffer instance
     */
    static Buffer from(ArrayBuffer datas, Integer byteOffset = 0, Integer length = -1);

    /*! @brief Creates a Buffer object from another Buffer
     @param datas Initialization data array
     @param byteOffset Specifies the data start position, starting from 0
     @param length Specifies the data length, starting from -1, indicating all remaining data
     @return Returns Buffer instance
     */
    static Buffer from(Uint8Array datas, Integer byteOffset = 0, Integer length = -1);

    /*! @brief Creates a Buffer object from a string
     @param str Initialization string, the string will be written in utf-8 format, if omitted, an empty object is created
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return Returns Buffer instance
     */
    static Buffer from(String str, String codec = "utf8");

    /*! @brief Concatenates data from multiple buffers
     @param buflist Array of Buffers to concatenate
     @param cutLength How many Buffer objects to take
     @return The new Buffer object produced by concatenation
    */
    static Buffer concat(Array buflist, Integer cutLength = -1);

    /*! @brief Checks if the given variable is a Buffer object
     @param v The variable to check
     @return Whether the passed object is a Buffer object
    */
    static Boolean isBuffer(Value v);

    /*! @brief Checks if the encoding format is supported
     @param codec The encoding format to check
     @return Whether it is supported
     */
    static Boolean isEncoding(String codec);

    /*! @brief Returns the actual byte length of the string
     @param str The string to get bytes from, if str is ArrayBuffer/TypedArray/DataView/Buffer object, returns their actual length
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return Returns the actual byte length
     */
    static Integer byteLength(String str, String codec = "utf8");

    /*! @brief Returns the actual byte length of the string
     @param str The string to get bytes from, if str is ArrayBuffer/TypedArray/DataView/Buffer object, returns their actual length
     @return Returns the actual byte length
     */
    static Integer byteLength(ArrayBuffer str);

    /*! @brief Returns the actual byte length of the string
     @param str The string to get bytes from, if str is ArrayBuffer/TypedArray/DataView/Buffer object, returns their actual length
     @return Returns the actual byte length
     */
    static Integer byteLength(Uint8Array str);

    /*! @brief Returns the actual byte length of the string
     @param str The string to get bytes from, if str is ArrayBuffer/TypedArray/DataView/Buffer object, returns their actual length
     @return Returns the actual byte length
     */
    static Integer byteLength(Buffer str);

    /*! @brief Compares buf1 and buf2, often used for sorting between Buffer instances. This is equivalent to buf1.compare(buf2).
    @param buf1 The buf to compare
    @param buf2 The buf to compare
    @return Returns the comparison byte length
     */
    static Integer compare(Buffer buf1, Buffer buf2);

    /*! @brief Gets the size of the buffer object */
    readonly Integer length;

    /*! @brief Writes the specified string to the buffer object, default utf-8, writes partial data if out of bounds
     @param str The string to write
     @param offset Write start position
     @param length Write length (in bytes, default -1), unspecified is the length of the string to write
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return The byte length of the written data
     */
    Integer write(String str, Integer offset = 0, Integer length = -1, String codec = "utf8");

    /*! @brief Writes the specified string to the buffer object, default utf-8, writes partial data if out of bounds
     @param str The string to write
     @param offset Write start position
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return The byte length of the written data
     */
    Integer write(String str, Integer offset = 0, String codec = "utf8");

    /*! @brief Writes the specified string to the buffer object, default utf-8, writes partial data if out of bounds
     @param str The string to write
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return The byte length of the written data
     */
    Integer write(String str, String codec = "utf8");

    /*! @brief Fills the Buffer object with specified content data
     @param v The data to fill, if offset and end are not specified, fills the entire buffer
     @param offset Fill start position
     @param end Fill end position
     @return Returns the current Buffer object
     */
    Buffer fill(Integer v, Integer offset = 0, Integer end = -1);

    /*! @brief Fills the Buffer object with specified content data
     @param v The data to fill, if offset and end are not specified, fills the entire buffer
     @param offset Fill start position
     @param end Fill end position
     @return Returns the current Buffer object
     */
    Buffer fill(Buffer v, Integer offset = 0, Integer end = -1);

    /*! @brief Fills the Buffer object with specified content data
     @param v The data to fill, if offset and end are not specified, fills the entire buffer
     @param offset Fill start position
     @param end Fill end position
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return Returns the current Buffer object
     */
    Buffer fill(String v, Integer offset = 0, Integer end = -1, String codec = "utf8");

    /*! @brief Fills the Buffer object with specified content data
     @param v The data to fill, if offset and end are not specified, fills the entire buffer
     @param offset Fill start position
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return Returns the current Buffer object
     */
    Buffer fill(String v, Integer offset, String codec);

    /*! @brief Fills the Buffer object with specified content data
     @param v The data to fill, if offset and end are not specified, fills the entire buffer
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @return Returns the current Buffer object
     */
    Buffer fill(String v, String codec);

    /*! @brief Copies data from the source buffer area to the target buffer area
     @param targetBuffer Target buffer object
     @param targetStart Target buffer start copy byte position, default 0
     @param sourceStart Source buffer start byte position, default 0
     @param sourceEnd Source buffer end byte position, default -1, indicating source data length
     @return The byte length of copied data
     */
    Integer copy(Buffer targetBuffer, Integer targetStart = 0, Integer sourceStart = 0, Integer sourceEnd = -1);

    /*! @brief Copies data from the source buffer area to the target buffer area
     @param src Target buffer object
     @param start Source buffer start byte position
     @return The byte length of copied data
     */
    Integer set(Buffer src, Integer start);

    /*! @brief Reads an 8-bit unsigned integer value from the buffer object
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Integer readUInt8(Integer offset = 0);

    /*! @brief Reads a 16-bit unsigned integer value from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Integer readUInt16LE(Integer offset = 0);

    /*! @brief Reads a 16-bit unsigned integer value from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Integer readUInt16BE(Integer offset = 0);

    /*! @brief Reads a 32-bit unsigned integer value from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Number readUInt32LE(Integer offset = 0);

    /*! @brief Reads a 32-bit unsigned integer value from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Number readUInt32BE(Integer offset = 0);

    /*! @brief Reads an unsigned integer value up to 48 bits from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @param byteLength Specifies the number of bytes to read, default 6 bytes
     @return Returns the read integer value
     */
    Number readUIntLE(Integer offset = 0, Integer byteLength = 6);

    /*! @brief Reads an unsigned integer value up to 48 bits from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @param byteLength Specifies the number of bytes to read, default 6 bytes
     @return Returns the read integer value
     */
    Number readUIntBE(Integer offset = 0, Integer byteLength = 6);

    /*! @brief Reads a 64-bit integer value from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Long readInt64LE(Integer offset = 0);

    /*! @brief Reads a 64-bit integer value from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Long readInt64BE(Integer offset = 0);

    /*! @brief Reads an 8-bit integer value from the buffer object
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Integer readInt8(Integer offset = 0);

    /*! @brief Reads a 16-bit integer value from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Integer readInt16LE(Integer offset = 0);

    /*! @brief Reads a 16-bit integer value from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Integer readInt16BE(Integer offset = 0);

    /*! @brief Reads a 32-bit integer value from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Integer readInt32LE(Integer offset = 0);

    /*! @brief Reads a 32-bit integer value from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read integer value
     */
    Integer readInt32BE(Integer offset = 0);

    /*! @brief Reads an integer value up to 48 bits from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @param byteLength Specifies the number of bytes to read, default 6 bytes
     @return Returns the read integer value
     */
    Number readIntLE(Integer offset = 0, Integer byteLength = 6);

    /*! @brief Reads an integer value up to 48 bits from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @param byteLength Specifies the number of bytes to read, default 6 bytes
     @return Returns the read integer value
     */
    Number readIntBE(Integer offset = 0, Integer byteLength = 6);

    /*! @brief Reads a float from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read float
     */
    Number readFloatLE(Integer offset = 0);

    /*! @brief Reads a float from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read float
     */
    Number readFloatBE(Integer offset = 0);

    /*! @brief Reads a double-precision float from the buffer object in little-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read double-precision float
     */
    Number readDoubleLE(Integer offset = 0);

    /*! @brief Reads a double-precision float from the buffer object in big-endian storage
     @param offset Specifies the read start position, default 0
     @return Returns the read double-precision float
     */
    Number readDoubleBE(Integer offset = 0);

    /*! @brief Writes an 8-bit unsigned integer value to the buffer object
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeUInt8(Integer value, Integer offset = 0);

    /*! @brief Writes a 16-bit unsigned integer value to the buffer object in little-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeUInt16LE(Integer value, Integer offset = 0);

    /*! @brief Writes a 16-bit unsigned integer value to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeUInt16BE(Integer value, Integer offset = 0);

    /*! @brief Writes a 32-bit unsigned integer value to the buffer object in little-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeUInt32LE(Long value, Integer offset = 0);

    /*! @brief Writes a 32-bit unsigned integer value to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeUInt32BE(Long value, Integer offset = 0);

    /*! @brief Writes an unsigned integer value up to 48 bits to the buffer object in little-endian storage
     @param value The value to write
     @param offset The write start position
     @param byteLength The number of bytes to write, default 6 bytes
     @return offset plus the number of bytes written
     */
    Integer writeUIntLE(Long value, Integer offset = 0, Integer byteLength = 6);

    /*! @brief Writes an unsigned integer value up to 48 bits to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @param byteLength The number of bytes to write, default 6 bytes
     @return offset plus the number of bytes written
     */
    Integer writeUIntBE(Long value, Integer offset = 0, Integer byteLength = 6);

    /*! @brief Writes an 8-bit integer value to the buffer object
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeInt8(Integer value, Integer offset = 0);

    /*! @brief Writes a 16-bit integer value to the buffer object in little-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeInt16LE(Integer value, Integer offset = 0);

    /*! @brief Writes a 16-bit integer value to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeInt16BE(Integer value, Integer offset = 0);

    /*! @brief Writes a 32-bit integer value to the buffer object in little-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeInt32LE(Integer value, Integer offset = 0);

    /*! @brief Writes a 32-bit integer value to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeInt32BE(Integer value, Integer offset = 0);

    /*! @brief Writes a 64-bit integer value to the buffer object in little-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeInt64LE(Long value, Integer offset = 0);

    /*! @brief Writes a 64-bit integer value to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeInt64BE(Long value, Integer offset = 0);

    /*! @brief Writes an integer value up to 48 bits to the buffer object in little-endian storage
     @param value The value to write
     @param offset The write start position
     @param byteLength The number of bytes to write, default 6 bytes
     @return offset plus the number of bytes written
     */
    Integer writeIntLE(Long value, Integer offset = 0, Integer byteLength = 6);

    /*! @brief Writes an integer value up to 48 bits to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @param byteLength The number of bytes to write, default 6 bytes
     @return offset plus the number of bytes written
     */
    Integer writeIntBE(Long value, Integer offset = 0, Integer byteLength = 6);

    /*! @brief Writes a float to the buffer object in little-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeFloatLE(Number value, Integer offset);

    /*! @brief Writes a float to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeFloatBE(Number value, Integer offset);

    /*! @brief Writes a double-precision float to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeDoubleLE(Number value, Integer offset);

    /*! @brief Writes a double-precision float to the buffer object in big-endian storage
     @param value The value to write
     @param offset The write start position
     @return offset plus the number of bytes written
     */
    Integer writeDoubleBE(Number value, Integer offset);

    /*! @brief Returns the position where the specified data first appears in the Buffer
     @param v The data to find, if offset is not specified, starts from the beginning
     @param offset Start search position
     @return Returns the found position, -1 if not found
     */
    Integer indexOf(Integer v, Integer offset = 0);

    /*! @brief Returns the position where the specified data first appears in the Buffer
     @param v The data to find, if offset is not specified, starts from the beginning
     @param offset Start search position
     @return Returns the found position, -1 if not found
     */
    Integer indexOf(Buffer v, Integer offset = 0);

    /*! @brief Returns the position where the specified data first appears in the Buffer
     @param v The data to find, if offset is not specified, starts from the beginning
     @param offset Start search position
     @return Returns the found position, -1 if not found
     */
    Integer indexOf(String v, Integer offset = 0);

    /*! @brief Returns the position where the specified data last appears in the Buffer
     @param v The data to find, if offset is not specified, starts from the beginning
     @param offset Start search position
     @return Returns the found position, -1 if not found
     */
    Integer lastIndexOf(Integer v, Integer offset = -1);

    /*! @brief Returns the position where the specified data last appears in the Buffer
     @param v The data to find, if offset is not specified, starts from the beginning
     @param offset Start search position
     @return Returns the found position, -1 if not found
     */
    Integer lastIndexOf(Buffer v, Integer offset = -1);

    /*! @brief Returns the position where the specified data last appears in the Buffer
     @param v The data to find, if offset is not specified, starts from the beginning
     @param offset Start search position
     @return Returns the found position, -1 if not found
     */
    Integer lastIndexOf(String v, Integer offset = -1);

    /*! @brief Returns a new buffer object containing data from the specified start to the end of the buffer
     @param start The start of the range, defaults to from the beginning
     @return Returns the new buffer object
     */
    Buffer slice(Integer start = 0);

    /*! @brief Returns a new buffer object containing data in the specified range, if the range exceeds the buffer, only returns valid partial data
     @param start The start of the range
     @param end The end of the range
     @return Returns the new buffer object
     */
    Buffer slice(Integer start, Integer end);

    /*! @brief Compares whether the current object is equal to the given object
     @param expected The target object for comparison
     @return Returns the result of object comparison
    */
    Boolean equals(object expected);

    /*! @brief Compares the content of the buffer
     @param buf The buffer object to compare
     @return Content comparison result
     */
    Integer compare(Buffer buf);

    /*! @brief Returns the encoded string of binary data
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @param offset Read start position
     @param end Read end position
     @return Returns the string representation of the object
    */
    String toString(String codec, Integer offset = 0, Integer end);

    /*! @brief Returns the encoded string of binary data
     @param codec Specifies the encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by the iconv module
     @param offset Read start position
     @return Returns the string representation of the object
    */
    String toString(String codec, Integer offset = 0);

    /*! @brief Returns the array of all binary data
     @return Returns the array containing object data
    */
    Array toArray();

    /*! @brief Encodes buffer object content using hex
     @return Returns the encoded string
     */
    String hex();

    /*! @brief Encodes buffer object content using base32
     @return Returns the encoded string
     */
    String base32();

    /*! @brief Encodes buffer object content using base58
     @return Returns the encoded string
     */
    String base58();

    /*! @brief Encodes buffer object content using base64
     @return Returns the encoded string
     */
    String base64();
};