/*! @brief Message handler chain processing object

 The Chain object is a message handler chain processing object in fibjs, used to link a series of message handlers, processing in a chain according to the specified order. The method to create a Chain object is as follows:

```
var chain = new mq.Chain([
    func1, func2
]);
```

In this creation method, func1 and func2 are both function objects of message handlers. The Chain object links these handlers in order to form a handler chain. When processing each message, each handler can perform custom processing on the message, and then pass the message to the next handler for processing. In this way, a message can be processed step by step to its final state.

The invoke() function of the Chain object is used to process a message or object. When this function is called, the Chain object passes the message or object to each handler in turn, processing them in the order of the handlers until all handlers have finished processing. In this process, each handler can perform custom processing on the message or object, or choose to pass the message or object to the next handler for processing.

In practical applications, the Chain object can be applied to various scenarios, such as in web frameworks, request messages can be passed to each handler in turn for processing; in message queues, a batch of messages can be passed to each handler in turn for processing. The Chain object is very flexible in its usage, can be customized according to actual needs, and has high scalability and reusability.
 */
interface Chain : Handler
{
    /*! @brief Construct a message handler chain processing object
     @param hdlrs Handler array
     */
    Chain(Handler hdlrs[]);

    /*! @brief Add handler array
     @param hdlrs Handler array
     */
    append(Handler hdlrs[]);

    /*! @brief Add handler
     @param hdlr Built-in message handler, processing function, chain processing array, routing object, see mq.Handler for details
     */
    append(Handler hdlr);
};