/*! @brief Child process management module
 Reference method:
 ```JavaScript
 var child_process = require("child_process");
 var child = child_process.spawn("ls");
 ```

When creating a child process, the options.stdio option is used to configure the pipes established between the parent process and the child process. By default, the child's stdin, stdout, and stderr are redirected to the corresponding stdin, stdout, and stderr streams on the ChildProcess object. This is equivalent to setting options.stdio to ['pipe', 'pipe', 'pipe'].

For convenience, options.stdio can be one of the following strings:

- 'pipe': equivalent to ['pipe', 'pipe', 'pipe'] (default).
- 'ignore': equivalent to ['ignore', 'ignore', 'ignore'].
- 'inherit': equivalent to ['inherit', 'inherit', 'inherit'] or [0, 1, 2].
- 'pty': equivalent to ['pty', 'pty', 'pty'].

Otherwise, the value of options.stdio must be an array (where each index corresponds to a file descriptor in the child process). File descriptors 0, 1, and 2 correspond to stdin, stdout, and stderr respectively. Other file descriptors can be specified to create additional pipes between the parent and child process. The value can be one of the following:

1. 'pipe': Creates a pipe between the child process and the parent process. The parent end of the pipe is exposed as the stdio[fd] property on the child_process object. Pipes created for file descriptors 0, 1, and 2 can also be used as stdin, stdout, and stderr respectively.
2. 'ignore': Instructs fibjs to ignore the file descriptor in the child process. Although fibjs will always open file descriptors 0, 1, and 2 for its spawned processes, setting the file descriptor to 'ignore' causes fibjs to open /dev/null and attach it to the child's file descriptor.
3. 'inherit': Passes the corresponding stdio stream to or from the parent process. In the first three positions, this is equivalent to process.stdin, process.stdout, and process.stderr respectively. In any other position, it is equivalent to 'ignore'.
4. 'pty': The child process will be executed in a virtual terminal. Only stdin and stdout are valid here.
5. Positive integer: The integer value is interpreted as a file descriptor currently open in the parent process. It is shared with the child process, similar to how <Stream> objects are shared. Passing sockets is not supported on Windows.
6. null or undefined: Use the default value. For stdio file descriptors 0, 1, and 2 (in other words, stdin, stdout, and stderr), pipes will be created. For file descriptors 3 and higher, the default is 'ignore'.

```JavaScript
const { spawn } = require('child_process');

// child process uses parent's stdio
spawn('prg', [], { stdio: 'inherit' });

// child process uses parent's stderr
spawn('prg', [], { stdio: ['pipe', 'pipe', process.stderr] });
```

 For users using both nodejs, please note:
 - fibjs's `child_process.exec(command, args)` is similar in function to nodejs's same-named API, but on Windows, it does not automatically use cmd.exe as the execution environment for the command parameter;
 - fibjs's child_process.[spawn|exec|execFile|run] are synchronous/callback integrated async style functions:
   - If the last parameter is not a function, it is synchronous
   - If a function is passed as the last parameter, it is asynchronous;
 - fibjs's child_process.[exec|execFile] return result is an object, which is **completely different** from the object returned by nodejs's same-named API
 - fibjs's `child_process.run` has no corresponding API in nodejs
 */
module child_process
{
    /*! @brief Spawn a child process with the given command
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "stdio": Array | String, // configure the pipes that are established between the parent and child process
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // configure the group identity of the process
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param args Specify the list of string arguments
     @param options Specify the creation parameters
     @return Return the child process object
     */
    static ChildProcess spawn(String command, Array args, Object options = {});

    /*! @brief Spawn a child process with the given command
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "stdio": Array | String, // configure the pipes that are established between the parent and child process
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param options Specify the creation parameters
     @return Return the child process object
     */
    static ChildProcess spawn(String command, Object options = {});

    /*! @brief Execute a command in the shell and buffer the output, when executed in callback mode, the function returns the child process object
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "encoding": "utf8", // specify the character encoding used to decode the stdout and stderr output
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param options Specify the creation parameters
     @return Return the stdio output content of the child process
     */
    static (Variant stdout, Variant stderr, Integer exitCode) exec(String command, Object options = {}) async;

    /*! @brief Directly execute the specified file and buffer the output, when executed in callback mode, the function returns the child process object
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "encoding": "utf8", // specify the character encoding used to decode the stdout and stderr output
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param args Specify the list of string arguments
     @param options Specify the creation parameters
     @return Return the stdio output content of the child process
     */
    static (Variant stdout, Variant stderr, Integer exitCode) execFile(String command, Array args, Object options = {}) async;

    /*! @brief Directly execute the specified file and buffer the output, when executed in callback mode, the function returns the child process object
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "encoding": "utf8", // specify the character encoding used to decode the stdout and stderr output
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param options Specify the creation parameters
     @return Return the stdio output content of the child process
     */
    static (Variant stdout, Variant stderr, Integer exitCode) execFile(String command, Object options = {}) async;

    /*! @brief Spawn a child process with the given command
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "stdio": Array | String, // configure the pipes that are established between the parent and child process
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // configure the group identity of the process
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param args Specify the list of string arguments
     @param options Specify the creation parameters
     @return Return the child process execution result
     */
    static (Integer pid, NArray output, Variant stdout, Variant stderr, Integer status, Variant error) spawnSync(String command, Array args, Object options = {});

    /*! @brief Spawn a child process with the given command
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "stdio": Array | String, // configure the pipes that are established between the parent and child process
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param options Specify the creation parameters
     @return Return the child process execution result
     */
    static (Integer pid, NArray output, Variant stdout, Variant stderr, Integer status, Variant error) spawnSync(String command, Object options = {});

    /*! @brief Synchronously execute a command in the shell and buffer the output
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "encoding": "utf8", // specify the character encoding used to decode the stdout and stderr output
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // configure the group identity of the process
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param options Specify the creation parameters
     @return Return the stdout output content of the child process
     */
    static Variant execSync(String command, Object options = {});

    /*! @brief Directly synchronously execute the specified file and buffer the output
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "encoding": "utf8", // specify the character encoding used to decode the stdout and stderr output
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // configure the group identity of the process
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param args Specify the list of string arguments
     @param options Specify the creation parameters
     @return Return the stdout output content of the child process
     */
    static Variant execFileSync(String command, Array args, Object options = {});

    /*! @brief Directly synchronously execute the specified file and buffer the output
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "encoding": "utf8", // specify the character encoding used to decode the stdout and stderr output
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // configure the group identity of the process
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param options Specify the creation parameters
     @return Return the stdout output content of the child process
     */
    static Variant execFileSync(String command, Object options = {});

    /*! @brief Execute a module in the child process
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "stdio": Array | String, // configure the pipes that are established between the parent and child process
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param module Specify the command to run
     @param args Specify the list of string arguments
     @param options Specify the creation parameters
     @return Return the child process object
     */
    static ChildProcess fork(String module, Array args, Object options = {});

    /*! @brief Execute a module in the child process
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "stdio": Array | String, // configure the pipes that are established between the parent and child process
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param module Specify the command to run
     @param options Specify the creation parameters
     @return Return the child process object
     */
    static ChildProcess fork(String module, Object options = {});

    /*! @brief Directly execute the specified file and return exitCode, when executed in callback mode, the function returns the child process object
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param args Specify the list of string arguments
     @param options Specify the creation parameters
     @return Return the exitCode of the child process
     */
    static Integer run(String command, Array args, Object options = {}) async;

    /*! @brief Directly execute the specified file and return exitCode, when executed in callback mode, the function returns the child process object
    options supports the following content:
     ```JavaScript
     {
        "cwd": "", // working directory of the child process, default to current directory
        "env": {}, // key-value pairs of environment variables to add to the child's environment
        "detached": false, // child process will be a leader of a new process group, default to false
        "uid": 0, // configure the user identity of the process
        "gid": 0, // con
        "windowsVerbatimArguments": false, // do not execute any quote or escape processing on Windows. Ignored on Unix. When specified, the command line string is passed directly to the underlying operating system shell without any processing whatsoever. This is set to true automatically when the shell option is specified and is CMD.
        "windowsHide": false, // hide the subprocess console window that would normally be created on Windows systems. This option has no effect on non-Windows systems.
        "cols": 80, // specify the initial number of columns for the PTY (only for stdio: 'pty')
        "rows": 24 // specify the initial number of rows for the PTY (only for stdio: 'pty')
     }
     ```
     @param command Specify the command to run
     @param options Specify the creation parameters
     @return Return the exitCode of the child process
     */
    static Integer run(String command, Object options = {}) async;

    /*! @brief Execute a command in the shell using string template syntax and buffer the output

     sh is another encapsulation of the exec method, used for quickly executing shell commands, supporting string template syntax, for example:
     ```JavaScript
       const $ = require("child_process").sh;
       var ret = $`ls -l`;
       console.log(ret);
      ```
      Because sh is a template function, you can conveniently use templates in commands, for example:
      ```JavaScript
       const $ = require("child_process").sh;
       var ret = $`ls -l ${__dirname}`;
       console.log(ret);
      ```
      You can also conveniently introduce arrays in commands, for example:
      ```JavaScript
       const $ = require("child_process").sh;
       const words = [
         "hello",
         "world"
       ]
       var ret = $`echo ${words}`;
       console.log(ret);
      ```
      sh will automatically remove the last newline returned by the command to facilitate use in the next command, for example:
      ```JavaScript
       const $ = require("child_process").sh;
       var world = $`echo world`;
       var ret = $`echo hello ${world}`;
       console.log(ret);
      ```

      @param strings Specify the command to run
      @param args Specify the list of string arguments
      @return Return the stdio output content of the child process
    */
    static String sh(Array strings, ...args) async;

    /*! @brief Create an ssh execution function

    options supports the following content:
     ```JavaScript
     {
         "user": "", // ssh user
         "port": 22, // ssh port
     }
     ```

     ssh is another encapsulation of the execFile method, used for quickly executing ssh shell commands, supporting string template syntax, for example:
     ```JavaScript
       const $ = require("child_process").ssh('remote');
       var ret = $`ls -l`;
       console.log(ret);
      ```
      Because sh is a template function, you can conveniently use templates in commands, for example:
      ```JavaScript
       const $ = require("child_process").ssh('remote');
       var ret = $`ls -l ${__dirname}`;
       console.log(ret);
      ```
      You can also conveniently introduce arrays in commands, for example:
      ```JavaScript
       const $ = require("child_process").ssh('remote');
       const words = [
         "hello",
         "world"
       ]
       var ret = $`echo ${words}`;
       console.log(ret);
      ```
      sh will automatically remove the last newline returned by the command to facilitate use in the next command, for example:
      ```JavaScript
       const $ = require("child_process").ssh('remote');
       var world = $`echo world`;
       var ret = $`echo hello ${world}`;
       console.log(ret);
      ```

    @param host Specify the remote host address
    @param options Specify the ssh connection parameters
    @return Return the child process object
   */
    static Function ssh(String host, Object options = {});
};