/*! @brief Child process object

 ```JavaScript
 var child_process = require("child_process");
 var child = child_process.spawn("ls");
 ```
 */
interface ChildProcess : EventEmitter
{
    /*! @brief Kill the process pointed to by the current object and pass the signal
      @param signal The signal to pass
     */
    kill(Integer signal);

    /*! @brief Kill the process pointed to by the current object and pass the signal
      @param signal The signal to pass
     */
    kill(String signal = "SIGTERM");

    /*! @brief Wait for the process pointed to by the current object to end and return the process exit code
      @return The exit code of the process
     */
    Integer join() async;

    /*! @brief Query whether the pipe with the child process is normally connected */
    readonly Boolean connected;

    /*! @brief Close the ipc pipe with the child process */
    disconnect();

    /*! @brief Send a message to the current child process
     @param msg The message to send
    */
    send(Value msg);

    /*! @brief Adjust the terminal size of the current child process
     @param cols Number of columns in the terminal
     @param rows Number of rows in the terminal
    */
    resize(Integer cols, Integer rows);

    /*! @brief Query the number of columns in the current terminal */
    readonly Integer cols;

    /*! @brief Query the number of rows in the current terminal */
    readonly Integer rows;

    /*! @brief Query the memory and time spent by the current process

     Memory report generates results similar to the following:
     ```JavaScript
     {
       "user": 132379,
       "system": 50507,
       "rss": 8622080
     }
     ```
     Where:
     - user Returns the time spent by the process in user code, in microseconds (millionths of a second)
     - system Returns the time spent by the process in system code, in microseconds (millionths of a second)
     - rss Returns the current physical memory size occupied by the process
     @return Returns the report containing time
     */
    Object usage();

    /*! @brief Read the id of the process pointed to by the current object
     */
    readonly Integer pid;

    /*! @brief Query whether the process pointed to by the current object has exited */
    readonly Boolean killed;

    /*! @brief Query and set the exit code of the current process */
    readonly Integer exitCode;

    /*! @brief Read the standard input object of the process pointed to by the current object
     */
    readonly Stream stdin;

    /*! @brief Read the standard output object of the process pointed to by the current object
     */
    readonly Stream stdout;

    /*! @brief Read the standard error object of the process pointed to by the current object
     */
    readonly Stream stderr;

    /*! @brief Read the standard IO object list of the process pointed to by the current object

     The array contains the standard IO streams of the child process, corresponding to
     the stdio option passed to spawn. Pipe entries are Stream objects, other entries
     are null.
     */
    readonly Array stdio;

    /*! @brief Query and bind process exit event, equivalent to on("exit", func); */
    event exit();

    /*! @brief Query and bind child process message event, equivalent to on("message", func); */
    event message();

    /*! @brief Query and bind child process spawn event, equivalent to on("spawn", func); */
    event spawn();

    /*! @brief Query and bind child process disconnect event, equivalent to on("disconnect", func); */
    event disconnect();

    /*! @brief Keep the fibjs process from exiting, prevent fibjs process from exiting during object binding
     @return Return the current object
    */
    ChildProcess ref();

    /*! @brief Allow the fibjs process to exit, allow fibjs process to exit during object binding
     @return Return the current object
    */
    ChildProcess unref();
};