/*! @brief Symmetric encryption algorithm object */
interface Cipher : object
{
    /*! @brief Set authentication tag
     @param buffer Specify authentication tag data
     @param encoding Specify authentication tag data encoding method
     @return Return the current Cipher object
     */
    Cipher setAuthTag(Buffer buffer, String encoding = "buffer");

    /*! @brief Set authentication tag
     @param buffer Specify authentication tag data
     @param encoding Specify authentication tag data encoding method
     @return Return the current Cipher object
     */
    Cipher setAuthTag(String buffer, String encoding = "utf8");

    /*! @brief Query authentication tag 
      @return Return authentication tag data
    */
    Buffer getAuthTag();

    /*! @brief Set additional authenticated data
     @param buffer Specify additional authenticated data
     @param options Specify additional authenticated data options
     @return Return the current Cipher object
    */
    Cipher setAAD(Buffer buffer, Object options = {});

    /*! @brief Set additional authenticated data
     @param buffer Specify additional authenticated data
     @param options Specify additional authenticated data options
     @return Return the current Cipher object
    */
    Cipher setAAD(String buffer, Object options = {});

    /*! @brief Set auto padding
     @param autoPadding Specify whether to auto pad
     @return Return the current Cipher object
    */
    Cipher setAutoPadding(Boolean autoPadding = true);

    /*! @brief Update data
      @param data Specify the data to update
      @param inputEncoding Specify input data encoding method
      @param outputEncoding Specify output data encoding method
      @return Return the updated data
    */
    Value update(Buffer data, String inputEncoding = "buffer", String outputEncoding = "buffer");

    /*! @brief Update data
      @param data Specify the data to update
      @param inputEncoding Specify input data encoding method
      @param outputEncoding Specify output data encoding method
      @return Return the updated data
    */
    Value update(String data, String inputEncoding = "utf8", String outputEncoding = "buffer");

    /*! @brief Finalize data
      @param outputEncoding Specify output data encoding method
      @return Return the updated data
    */
    Value final(String outputEncoding = "buffer");
};