/*! @brief Condition variable object

 Condition variables are a mechanism for synchronization using global variables shared between fibers, mainly including two actions:
 1) A thread waits for a condition to be established and suspends itself;
 2) Another thread makes the condition established and notifies the waiting fiber to continue execution.

 To prevent competition, each condition variable needs the cooperation of a Lock (Lock can be explicitly created and passed in by yourself, or you can let fibjs create it for you)

 By using condition variables, you can use one condition variable to control the switch of a batch of fibers;

 The following are two examples of fiber scheduling:
 ```JavaScript
 var coroutine = require("coroutine");
 var cond = new coroutine.Condition();
 var ready = false;
 var state = "ready";

 function funcwait() {
    cond.acquire();
    while (!ready)
        cond.wait();
    state = "go"
    cond.release();
 }

 coroutine.start(funcwait);

 cond.acquire();
 console.log(state)
 ready = true;
 cond.notify();
 coroutine.sleep();
 console.log(state);
 ```
 will output:
 ```sh
 ready
 go
 ```
 */
interface Condition : Lock
{
    /*! @brief Condition variable constructor (the lock required by the condition variable is constructed internally by fibjs) */
    Condition();

    /*! @brief Condition variable constructor
     @param lock Use a self-constructed lock
     */
    Condition(Lock lock);

    /*! @brief Wait for a condition variable
     @param timeout Specifies the timeout time in milliseconds, default is -1, meaning never timeout.
     @return Returns true if acquired successfully, false if timeout
    */
    Boolean wait(Integer timeout = -1) async;

    /*! @brief Notify a blocked fiber (the last added to the fiber pool) to continue execution */
    notify();

    /*! @brief Notify all blocked fibers to continue execution */
    notifyAll();
};