/*! @brief Concurrency control module

The `coroutine` module provides an API for controlling the execution order of `fiber`. It allows developers to manually switch `fiber`, thereby implementing cooperative multitasking. An important function of the `coroutine` module is the `sleep` function, which allows the currently executing `fiber` to yield the CPU, allowing other `fiber` to run.

 The following is a simple example code demonstrating how to use the `coroutine` module:
 ```JavaScript
 const coroutine = require('coroutine');

 function foo() {
  console.log('start foo');
  coroutine.sleep(1000); // enter sleep mode
  console.log('end foo');
 }

 function bar() {
  console.log('start bar');
  coroutine.sleep(2000);
  console.log('end bar');
 }

 coroutine.start(foo);
 coroutine.start(bar);
 ```
 In the above code, we define two functions `foo` and `bar`, then use the `coroutine.start` function to start two `fiber`. In each `fiber`, we use the `coroutine.sleep` function to yield the CPU, allowing other `fiber` to run.
 */
module coroutine
{
    /*! @brief Lock object, see Lock */
    static Lock;

    /*! @brief Semaphore object, see Semaphore */
    static Semaphore;

    /*! @brief Condition variable object, see Condition */
    static Condition;

    /*! @brief Event object, see Event */
    static Event;

    /*! @brief Start a fiber and return the fiber object
     @param func Specify the function for fiber execution
     @param args Variable parameter sequence, this sequence will be passed to the function within the fiber
     @return Return the fiber object
     */
    static Fiber start(Function func, ...args);

    /*! @brief Execute a group of functions in parallel and wait for return
     @param funcs Array of functions to execute in parallel
     @param fibers Limit the number of concurrent fibers, default is -1, enable the same number of fibers as funcs
     @return Return an array of function execution results
     */
    static Array parallel(Array funcs, Integer fibers = -1);

    /*! @brief Execute a function to process a group of data in parallel and wait for return
     @param datas Array of data to execute in parallel
     @param func Function to execute in parallel
     @param fibers Limit the number of concurrent fibers, default is -1, enable the same number of fibers as datas
     @return Return an array of function execution results
     */
    static Array parallel(Array datas, Function func, Integer fibers = -1);

    /*! @brief Execute a function multiple times in parallel and wait for return
     @param func Number of functions to execute in parallel
     @param num Number of repeated tasks
     @param fibers Limit the number of concurrent fibers, default is -1, enable the same number of fibers as funcs
     @return Return an array of function execution results
     */
    static Array parallel(Function func, Integer num, Integer fibers = -1);

    /*! @brief Execute a group of functions in parallel and wait for return
     @param funcs A group of functions to execute in parallel
     @return Return an array of function execution results
     */
    static Array parallel(...funcs);

    /*! @brief Return the current fiber
     @return Current fiber object
     */
    static Fiber current();

    /*! @brief Suspend the current fiber for the specified time
     @param ms Specify the time to suspend, in milliseconds, default is 0, resume immediately when idle
     */
    static sleep(Integer ms = 0) async;

    /*! @brief Return an array of all currently running fibers */
    static readonly Array fibers;

    /*! @brief Query and set the number of idle fibers, can appropriately increase the number of idle fibers when server jitter is large. Default is 256 */
    static Integer spareFibers;

    /*! @brief Query the current vm number */
    static readonly Integer vmid;
};