/*! @brief dgram.Socket object is an EventEmitter that encapsulates datagram functions.

DgramSocket instances are created by dgram.createSocket(). Creating a dgram.Socket instance does not require the use of the new keyword.

Creation method:
```JavaScript
var dgram = require('dgram');
var sock = dgram.createSocket('udp4');
```
 */
interface DgramSocket : EventEmitter
{
    /*! @brief This method will make dgram.Socket listen for datagram messages on the specified `port` and `addr`. A `listening` event will be triggered when binding is complete.
     @param port Specify the binding port, if `port` is not specified or is 0, the operating system will try to bind a random port
     @param addr Specify the binding address, if address is not specified, the operating system will try to listen on all addresses.
    */
    bind(Integer port = 0, String addr = "") async;

    /*! @brief This method will make dgram.Socket listen for datagram messages on the `port` and `address` specified by `opts`. A `listening` event will be triggered when binding is complete.
     @param opts Specify binding parameters
    */
    bind(Object opts) async;

    /*! @brief Send a datagram on the socket
     @param msg Specify the data to send
     @param port Specify the destination port to send
     @param address Specify the destination address to send
     @return Return the send size
    */
    Integer send(Buffer msg, Integer port, String address = "") async;

    /*! @brief Send a datagram on the socket
     @param msg Specify the data to send
     @param offset Send from the specified offset
     @param length Send only the specified length
     @param port Specify the destination port to send
     @param address Specify the destination address to send
     @return Return the send size
    */
    Integer send(Buffer msg, Integer offset, Integer length, Integer port, String address = "") async;

    /*! @brief Return an object containing socket address information. For UDP sockets, this object will contain address, family and port properties. 
     @return Return the bound address of the object
    */
    NObject address();

    /*! @brief Close the current socket */
    close();

    /*! @brief Close the current socket
     @param callback Callback function after closing, it is equivalent to adding a listener for the `close` event
    */
    close(Function callback);

    /*! @brief Query socket receive buffer size 
     @return Return the query result
    */
    Integer getRecvBufferSize();

    /*! @brief Query socket send buffer size
     @return Return the query result
    */
    Integer getSendBufferSize();

    /*! @brief Use the IP_ADD_MEMBERSHIP socket option to join the multicast group at the given multicastAddress and multicastInterface. If the multicastInterface parameter is not specified, the operating system will choose an interface and add membership to it. To add membership to each available interface, call addMembership multiple times, once for each interface.
     @param multicastAddress Specify the multicast group address to join
     @param multicastInterface Specify the multicast group interface to join
     */
    addMembership(String multicastAddress, String multicastInterface = "");

    /*! @brief Use the IP_DROP_MEMBERSHIP socket option to leave the multicast group at multicastAddress. When the socket is closed or the process terminates, the kernel will automatically call this method, so most applications have no reason to call this method.
     @param multicastAddress Specify the multicast group address to remove
     @param multicastInterface Specify the multicast group interface to remove
     */
    dropMembership(String multicastAddress, String multicastInterface = "");

    /*! @brief Set the IP_MULTICAST_TTL socket option
     @param ttl Specify the ttl to set, the ttl parameter can be between 0 and 255. The default value on most systems is 1.
     */
    setMulticastTTL(Integer ttl);

    /*! @brief Set socket receive buffer size 
     @param size Specify the size to set
    */
    setRecvBufferSize(Integer size);

    /*! @brief Set socket send buffer size
     @param size Specify the size to set
    */
    setSendBufferSize(Integer size);

    /*! @brief Set or clear the SO_BROADCAST socket option
     @param flag When set to true, UDP packets will be sent to the broadcast address of a local interface
    */
    setBroadcast(Boolean flag);

    /*! @brief The `close` event will be triggered after closing a `socket` using `close()`. Once this event is triggered, no new `message` events will be triggered on this `socket` */
    event close();

    /*! @brief When any error occurs, the `error` event will be triggered */
    event error();

    /*! @brief When a `socket` starts listening for datagram messages, the `listening` event will be triggered. This event will be triggered immediately after creating the UDP socket */
    event listening();

    /*! @brief When a new datagram is received by the `socket`, the `message` event will be triggered. `msg` and `rinfo` will be passed as parameters to the event handler.
     @param msg The received datagram
     @param rinfo An object containing remote information of the received datagram. This object contains `address`, `port` and `family` properties, representing the remote address, port and protocol family respectively.
    */
    event message(Buffer msg, NObject rinfo);

    /*! @brief Keep the fibjs process from exiting, prevent fibjs process from exiting during object binding
     @return Return the current object
    */
    DgramSocket ref();

    /*! @brief Allow the fibjs process to exit, allow fibjs process to exit during object binding
     @return Return the current object
    */
    DgramSocket unref();
};