/*! @brief Message digest object */
interface Digest : object
{
    /*! @brief Update the binary digest
     @param data The binary data blocks
     */
    update(Buffer data);

    /*!	@brief Compute and return the digest
     @param codec The encode format, can be "buffer", "hex", “base64”, "utf8" or any other character sets supported by the system.
     @return The encode value representing the value of the digest
     */
    Value digest(String codec = "buffer");

    /*! @brief Query the number of bytes of the digest of the digest algorithm currently being used */
    readonly Integer size;
};
