/*! @brief dns domain name query module

 Basic module, reference method:
 ```JavaScript
 var dns = require('dns');
 ```
 */
module dns
{
    /*! @brief Query the address of the given hostname
     @param name Specify hostname
     @return Return the queried ip string array
     */
    static NArray resolve(String name) async;

    /*! @brief Query the address of the given hostname
     @param name Specify hostname
     @param options Query options
     @return Return the queried ip string
     */
    static Variant lookup(String name, Object options = {}) async;
};