/*! @brief `encoding` module is a built-in module in FibJS, used to implement conversion between various data encoding formats and binary. These data encoding formats include `base64`, `base32`, `hex`, `json`, `msgpack`, `multibase`, `base58` and other commonly used data encoding formats.

Below is a brief introduction to the sub-modules provided by the `encoding` module:

- `iconv`: Used to handle conversions between various encodings.
- `base64`: Provides support for Base64 encoding and decoding, can encode strings to Base64 format, and can also decode Base64 format to strings.
- `base32`: Provides support for Base32 encoding and decoding, can encode given data to Base32 and return the encoded string. Can also decode Base32 encoded strings to original data.
- `hex`: Provides support for hexadecimal encoding and decoding, can encode given data to hexadecimal and return the encoded string. Can also decode hexadecimal encoded strings to original data.
- `json`: Provides support for JSON encoding and decoding, can serialize JavaScript objects to JSON strings, and can also deserialize JSON strings to JavaScript objects.
- `multibase`: Provides support for Multibase encoding, Multibase is an encoding method that introduces multiple encoding prefixes based on Base1x encoding.
- `msgpack`: Provides support for Msgpack encoding and decoding, Msgpack is a lighter data exchange format than JSON, it can serialize JSON objects to binary data to achieve faster and more efficient data exchange.
- `base58`: Provides support for Base58 encoding and decoding, Base58 is a combination representation of numbers and letters, it does not contain numbers 0, letters O, I, L and other confusing characters, and has the characteristic of not being easy to make mistakes.

Most sub-modules in the `encoding` module contain encoding and decoding functions, using these functions can encode or decode data in specific formats. When using these encoding and decoding modules, you need to choose the most suitable module according to the characteristics of the module type, etc., to ensure the correctness of encoding and decoding.
 
 Reference method for `encoding` module:
 ```JavaScript
 var encoding = require('encoding');
 ```



 */
module encoding
{
    /*! @brief base32 encoding and decoding module */
    static base32;

    /*! @brief base64 encoding and decoding module */
    static base64;

    /*! @brief base58 encoding and decoding module */
    static base58;

    /*! @brief hex encoding and decoding module */
    static hex;

    /*! @brief multibase encoding and decoding module */
    static multibase;

    /*! @brief iconv encoding and decoding module */
    static iconv;

    /*! @brief Determine if the specified encoding is supported
     @param codec Specify encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by iconv module
     @return Return whether the encoding is supported
    */
    static Boolean isEncoding(String codec);

    /*! @brief Encode Buffer to string
     @param data Initialize string, string will be written in utf-8 format
     @param codec Specify encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by iconv module, default is "utf8"
     @return Return the encoded string
    */
    static String encode(Buffer data, String codec = "utf8");

    /*! @brief Decode string to Buffer
     @param str Initialize string, string will be written in utf-8 format
     @param data Specify encoding format, allowed values: "hex", "base32", "base58", "base64", "utf8", or character sets supported by iconv module, default is "utf8"
     @return Return the decoded Buffer
    */
    static Buffer decode(String str, String codec = "utf8");

    /*! @brief json encoding and decoding module */
    static json;

    /*! @brief msgpack encoding and decoding module */
    static msgpack;

    /*! @brief Encode string to javascript escaped string, used to include text in javascript code
     @param str String to encode
     @param json Whether to generate json compatible string
     @return Return the encoded string
     */
    static String jsstr(String str, Boolean json = false);

    /*! @brief url string safe encoding
     @param url url to encode
     @return Return the encoded string
     */
    static String encodeURI(String url);

    /*! @brief url component string safe encoding
     @param url url to encode
     @param formEncoded Whether to use application/x-www-form-urlencoded format encoding (space encoded as +), default is false
     @return Return the encoded string
     */
    static String encodeURIComponent(String url, Boolean formEncoded = false);

    /*! @brief url safe string decoding
     @param url url to decode
     @return Return the decoded string
     */
    static String decodeURI(String url);
};