/*! @brief EventEmitter is an event trigger object, it can be used to establish observer pattern, all objects that support event triggering inherit from this

When an event is triggered, all listeners associated with that event will be called asynchronously. It also allows us to create code with high customizability and flexibility.

Common functions include: addListener/on, once, removeListener/off, removeAllListeners and emit.

Below is an example code:

```javascript
var fs = require('fs');
var EventEmitter = require('events');
var event = new EventEmitter();

event.on('read_file', function(filename) {
  fs.readFile(filename, 'utf8', function(err, data) {
    if (err) {
      event.emit('error', err);
      return;
    }
    event.emit('show_content', data);
  });
});

event.on('error', function(err) {
  console.log(`Error ${err}`);
});

event.on('show_content', function(content) {
  console.log(content);
});

event.emit('read_file', 'test.txt');
```

The above example code, when running, the event emitter instance event first listens to the 'read_file' event, then triggers the file reading operation when the event is triggered (`event.emit('read_file', 'test.txt')`). When the reading is successful, the 'show_content' event will be triggered, and the function listening to the 'show_content' event will be executed and display the file content. If an error occurs during the file reading process, the 'error' event will be triggered, and the failure situation is handled.

This pattern has excellent advantages in business scenarios dealing with asynchronous operations.
 */
interface EventEmitter : object
{
    /*! @brief Constructor */
    EventEmitter();

    /*! @brief Event trigger object */
    static EventEmitter;

    /*! @brief Default global maximum number of listeners */
    static Integer defaultMaxListeners;

    /*! @brief Bind an event handler function to the object
    @param ev Specifies the event name
    @param func Specifies the event handler function
    @return Returns the event object itself for chaining
   */
    Object on(String ev, Function func);

    /*! @brief Bind an event handler function to the object
    @param map Specifies the event mapping relationship, object property names will be used as event names, property values will be used as event handler functions
    @return Returns the event object itself for chaining
   */
    Object on(Object map);

    /*! @brief Bind an event handler function to the object
    @param ev Specifies the event name
    @param func Specifies the event handler function
    @return Returns the event object itself for chaining
   */
    Object addListener(String ev, Function func);

    /*! @brief Bind an event handler function to the object
    @param map Specifies the event mapping relationship, object property names will be used as event names, property values will be used as event handler functions
    @return Returns the event object itself for chaining
   */
    Object addListener(Object map);

    /*! @brief Bind an event handler function to the object

    options parameter is an object, it can contain the following properties:
    - once: if true, the event handler function will only trigger once, and will be removed after triggering

    @param ev Specifies the event name
    @param func Specifies the event handler function
    @param options Specifies the options for the event handler function
    @return Returns the event object itself for chaining
    */
    Object addEventListener(String ev, Function func, Object options = {});

    /*! @brief Bind an event handler function to the beginning of the object
    @param ev Specifies the event name
    @param func Specifies the event handler function
    @return Returns the event object itself for chaining
   */
    Object prependListener(String ev, Function func);

    /*! @brief Bind an event handler function to the beginning of the object
    @param map Specifies the event mapping relationship, object property names will be used as event names, property values will be used as event handler functions
    @return Returns the event object itself for chaining
   */
    Object prependListener(Object map);

    /*! @brief Bind a one-time event handler function to the object, the one-time handler function will only trigger once
    @param ev Specifies the event name
    @param func Specifies the event handler function
    @return Returns the event object itself for chaining
   */
    Object once(String ev, Function func);

    /*! @brief Bind a one-time event handler function to the object, the one-time handler function will only trigger once
    @param map Specifies the event mapping relationship, object property names will be used as event names, property values will be used as event handler functions
    @return Returns the event object itself for chaining
   */
    Object once(Object map);

    /*! @brief Bind an event handler function to the beginning of the object
    @param ev Specifies the event name
    @param func Specifies the event handler function
    @return Returns the event object itself for chaining
   */
    Object prependOnceListener(String ev, Function func);

    /*! @brief Bind an event handler function to the beginning of the object
    @param map Specifies the event mapping relationship, object property names will be used as event names, property values will be used as event handler functions
    @return Returns the event object itself for chaining
   */
    Object prependOnceListener(Object map);

    /*! @brief Remove the specified function from the object's processing queue
    @param ev Specifies the event name
    @param func Specifies the event handler function
    @return Returns the event object itself for chaining
   */
    Object off(String ev, Function func);

    /*! @brief Remove all functions from the object's processing queue
    @param ev Specifies the event name
    @return Returns the event object itself for chaining
   */
    Object off(String ev);

    /*! @brief Remove the specified function from the object's processing queue
    @param map Specifies the event mapping relationship, object property names as event names, property values as event handler functions
    @return Returns the event object itself for chaining
   */
    Object off(Object map);

    /*! @brief Remove the specified function from the object's processing queue
    @param ev Specifies the event name
    @param func Specifies the event handler function
    @return Returns the event object itself for chaining
   */
    Object removeListener(String ev, Function func);

    /*! @brief Remove all functions from the object's processing queue
    @param ev Specifies the event name
    @return Returns the event object itself for chaining
   */
    Object removeListener(String ev);

    /*! @brief Remove the specified function from the object's processing queue
    @param map Specifies the event mapping relationship, object property names as event names, property values as event handler functions
    @return Returns the event object itself for chaining
   */
    Object removeListener(Object map);

    /*! @brief Remove the specified function from the object's processing queue
    @param ev Specifies the event name
    @param func Specifies the event handler function
    @param options Specifies the options for the event handler function
    @return Returns the event object itself for chaining
    */
    Object removeEventListener(String ev, Function func, Object options = {});

    /*! @brief Remove all listeners for all events from the object's processing queue, if an event is specified, remove all listeners for the specified event.
    @param ev Specifies the event name
    @return Returns the event object itself for chaining
   */
    Object removeAllListeners(String ev);

    /*! @brief Remove all listeners for all events from the object's processing queue, if an event is specified, remove all listeners for the specified event.
    @param evs Specifies the event names
    @return Returns the event object itself for chaining
   */
    Object removeAllListeners(Array evs = []);

    /* The default limit number of listeners, only for compatibility
    @param n Specifies the number of events
   */
    setMaxListeners(Integer n);

    /* Get the default limit number of listeners, only for compatibility
    @return Returns the default limit number
   */
    Integer getMaxListeners();

    /*! @brief Query the listener array for the specified event of the object
    @param ev Specifies the event name
    @return Returns the listener array for the specified event
   */
    Array listeners(String ev);

    /*! @brief Query the raw listener array for the specified event of the object, including once wrappers
    @param ev Specifies the event name
    @return Returns the raw listener array for the specified event
   */
    Array rawListeners(String ev);

    /*! @brief Query the number of listeners for the specified event of the object
    @param ev Specifies the event name
    @return Returns the number of listeners for the specified event
   */
    Integer listenerCount(String ev);

    /*! @brief Query the number of listeners for the specified event of the object
    @param o Specifies the object to query
    @param ev Specifies the event name
    @return Returns the number of listeners for the specified event
   */
    Integer listenerCount(Value o, String ev);

    /*! @brief Query listener event names
    @return Returns the array of event names
   */
    Array eventNames();

    /*! @brief Actively trigger an event
    @param ev Event name
    @param args Event parameters, will be passed to the event handler function
    @return Returns the event trigger status, returns true if there is a response event, otherwise returns false
   */
    Boolean emit(String ev, ...args);

    /*! @brief Listen to an AbortSignal's abort event, returns a disposable object

    The returned object contains a `[Symbol.dispose]()` method, which removes the listener when called. If the signal is already aborted, the listener will be called immediately.

    @param signal The AbortSignal object to listen to
    @param func The handler function for the abort event
    @return Returns a Disposable object with a `[Symbol.dispose]` method
   */
    static Object addAbortListener(EventEmitter signal, Function func);

    /*! @brief Create a Promise that resolves when the specified event is emitted once

    Returns a Promise that resolves with the event arguments array when the target event fires. If an 'error' event is emitted (and the listened event is not 'error' itself), the Promise will be rejected.

    options parameter can contain:
    - signal: AbortSignal, used to cancel the wait

    @param emitter The event emitter object to listen to
    @param ev Specifies the event name
    @param options Optional parameters object
    @return Returns a Promise that resolves with the event arguments array
   */
    static Object once(EventEmitter emitter, String ev, Object options = {});

    /*! @brief Create an async iterator that continuously listens for the specified event

    Returns an AsyncIterator that yields event arguments arrays each time the event fires. If an 'error' event is emitted, the iterator will throw the error.

    options parameter can contain:
    - signal: AbortSignal, used to cancel the iteration
    - close: Array of strings, specifying event names that end the iteration

    @param emitter The event emitter object to listen to
    @param ev Specifies the event name
    @param options Optional parameters object
    @return Returns an AsyncIterator object
   */
    static Object on(EventEmitter emitter, String ev, Object options = {});
};