/*! @brief gui module

Usage:
```JavaScript
var gui = require('gui');
```
 */
module gui
{
    /*! @brief Browser window object, WebView is a window component embedded with browser */
    static WebView;

    /*! @brief Open a window and visit the specified URL

     Supports the following parameters:
     ```JavaScript
     {
         "icon": "/path/to/file.png", // specify the icon of the window, not work in gtk4
         "left": 100, // specify the left position of the window, default position is center of the screen, not work in gtk4
         "right": 100, // specify the top position of the window, default position is center of the screen, not work in gtk4
         "width": 100, // specify the width of the window, default is system auto set
         "height": 100, // specify the height of the window, default is system auto set
         "visible": true, // specify whether the window is visible, default is true
         "hideOnClose": false, // specify whether the window is hidden when closed, default is false
         "minWidth": 0, // specify the minimum width of the window, default is 0
         "minHeight": 0, // specify the minimum height of the window, default is 0
         "maxWidth": 0, // specify the maximum width of the window, default is no limit
         "maxHeight": 0, // specify the maximum height of the window, default is no limit
         "frame": true, // specify whether the window has frame, default is true
         "titlebar": "show" | {  // specify the titlebar style: "show" (default), "hide", "transparent"
            "style": "show", // specify the titlebar style: "show" (default), "hide", "transparent"
            "height": "normal" // specify the titlebar height: "normal" (default), "tall", not work in macos
         },
         "resizable": true, // specify whether the window is resizable, default is true
         "menu": menu, // specify the menu of the window, can be a Menu object or a menu item array, default is null
         "maximize": false, // specify whether the window is maximized, default is false
         "fullscreen": false, // specify whether the window is fullscreen, default is false
         "devtools": false, // specify whether the DevTools in WebView is enabled, default is false
         "app": {}, // specify the app object that can be remote call in WebView, default is undefined
     }
     ```
     When width and height are set, and left or right is not set, the window will be automatically centered
     @param url The specified URL
     @param opt Open window parameters
     @return Return the opened window object
	*/
    static WebView open(String url, Object opt = {});

    /*! @brief Open a browser window, if url or file is specified, load the specified resource

     Supports the following parameters:
     ```JavaScript
     {
         "url": , // specify the url of the window, default is about:blank
         "file": , // specify the file of the window
         "icon": "/path/to/file.png", // specify the icon of the window, not work in gtk4
         "left": 100, // specify the left position of the window, default position is center of the screen, not work in gtk4
         "right": 100, // specify the top position of the window, default position is center of the screen, not work in gtk4
         "width": 100, // specify the width of the window, default is system auto set
         "height": 100, // specify the height of the window, default is system auto set
         "visible": true, // specify whether the window is visible, default is true
         "hideOnClose": false, // specify whether the window is hidden when closed, default is false
         "minWidth": 0, // specify the minimum width of the window, default is 0
         "minHeight": 0, // specify the minimum height of the window, default is 0
         "maxWidth": 0, // specify the maximum width of the window, default is no limit
         "maxHeight": 0, // specify the maximum height of the window, default is no limit
         "frame": true, // specify whether the window has frame, default is true
         "titlebar": "show" | {  // specify the titlebar style: "show" (default), "hide", "transparent"
            "style": "show", // specify the titlebar style: "show" (default), "hide", "transparent"
            "height": "normal" // specify the titlebar height: "normal" (default), "tall", not work in macos
         },
         "resizable": true, // specify whether the window is resizable, default is true
         "menu": menu, // specify the menu of the window, can be a Menu object or a menu item array, default is null
         "maximize": false, // specify whether the window is maximized, default is false
         "fullscreen": false, // specify whether the window is fullscreen, default is false
         "devtools": false, // specify whether the DevTools in WebView is enabled, default is false
         "app": {}, // specify the app object that can be remote call in WebView, default is undefined
     }
     ```
     When width and height are set, and left or right is not set, the window will be automatically centered
     @param opt Open window parameters
     @return Return the opened window object
	*/
    static WebView open(Object opt = {});

    /*! @brief Open a window and visit the specified file

     Supports the following parameters:
     ```JavaScript
     {
         "icon": "/path/to/file.png", // specify the icon of the window, not work in gtk4
         "left": 100, // specify the left position of the window, default position is center of the screen, not work in gtk4
         "right": 100, // specify the top position of the window, default position is center of the screen, not work in gtk4
         "width": 100, // specify the width of the window, default is system auto set
         "height": 100, // specify the height of the window, default is system auto set
         "visible": true, // specify whether the window is visible, default is true
         "hideOnClose": false, // specify whether the window is hidden when closed, default is false
         "minWidth": 0, // specify the minimum width of the window, default is 0
         "minHeight": 0, // specify the minimum height of the window, default is 0
         "maxWidth": 0, // specify the maximum width of the window, default is no limit
         "maxHeight": 0, // specify the maximum height of the window, default is no limit
         "frame": true, // specify whether the window has frame, default is true
         "titlebar": "show" | {  // specify the titlebar style: "show" (default), "hide", "transparent"
            "style": "show", // specify the titlebar style: "show" (default), "hide", "transparent"
            "height": "normal" // specify the titlebar height: "normal" (default), "tall", not work in macos
         },
         "resizable": true, // specify whether the window is resizable, default is true
         "menu": menu, // specify the menu of the window, can be a Menu object or a menu item array, default is null
         "maximize": false, // specify whether the window is maximized, default is false
         "fullscreen": false, // specify whether the window is fullscreen, default is false
         "devtools": false, // specify whether the DevTools in WebView is enabled, default is false
         "app": {}, // specify the app object that can be remote call in WebView, default is undefined
     }
     ```
     When width and height are set, and left or right is not set, the window will be automatically centered
     @param file The specified file
     @param opt Open window parameters
     @return Return the opened window object
	*/
    static WebView openFile(String file, Object opt = {});

    /*! @brief Create a menu object

    Menu items support the following types:
    - normal
        - type: "normal"
        - label: required
        - tooltip, icon, enabled: optional
        - cannot have submenu or checked
    - checkbox
        - type: "checkbox"
        - label: required
        - checked: optional
        - tooltip, icon, enabled: optional
        - cannot have submenu
    - submenu
        - type: "submenu"
        - label, submenu: required
        - tooltip, icon, enabled: optional
        - cannot have checked
    - separator
        - type: "separator"
        - cannot have label, submenu, checked, icon or tooltip

    If the menu item does not specify type, the type is automatically determined based on other attributes. The identification strategy is as follows:
    - If the submenu attribute exists, set type to "submenu".
    - If the checked attribute exists, set type to "checkbox".
    - If the passed object is empty, set type to "separator".
    - If none of the above conditions are met, set type to "normal".

     @param items Menu item array
     @return Return the created menu object
    */
    static Menu createMenu(Object items[] = []);

    /*! @brief Create a status icon object

     Supports the following parameters:
     ```JavaScript
     {
         "icon": "/path/to/file.png", // specify the icon of the tray, must be a png file
         "title": "", // specify the title of the tray, if not set, it will not be displayed
         "tooltip": "", // specify the tooltip of the tray, if not set, it will not be displayed
         "menu": menu, // specify the menu of the tray, default is null
     }
     ```
     @param opt Create status icon parameters
     @return Return the created status icon object
    */
    static Tray createTray(Object opt = {});

    /*! @brief Pop up a message box
     @param message Message content
    */
    static alert(String message) async;

    /*! @brief Pop up a message box
     @param title Message title
     @param message Message content
    */
    static alert(String title, String message) async;

    /*! @brief Pop up a confirmation box
     @param message Message content
     @return Return the user's selection result
    */
    static Boolean confirm(String message) async;

    /*! @brief Pop up a confirmation box
     @param title Message title
     @param message Message content
     @return Return the user's selection result
    */
    static Boolean confirm(String title, String message) async;

    /*! @brief Pop up an input box
     @param message Message content
     @param password Whether it is password input, default is false
     @return Return the content entered by the user
    */
    static String input(String message, Boolean password = false) async;

    /*! @brief Pop up an input box
     @param title Message title
     @param message Message content
     @param password Whether it is password input, default is false
     @return Return the content entered by the user
    */
    static String input(String title, String message, Boolean password = false) async;

    /*! @brief Pop up a file selection dialog

     options supports the following parameters:
      - title: Dialog title
      - type: Dialog type, "openFile", "openDirectory", "saveFile", default is "openFile"
      - defaultPath: Default open path
      - multiple: Whether to allow multiple selection, default is false
      - filters: File filter array, each element is an object containing name and extensions two attributes, extensions is an extension name array

     @param options File selection dialog parameters
     @return Return the file array selected by the user
    */
    static NArray chooseFile(Object options) async;
};