/*! @brief HeapSnapshots record the state of the JS heap at a certain moment */
interface HeapSnapshot : object
{
    /*! @brief Compare with the specified heap snapshot
     @param before heap snapshot to compare
     @return Return the comparison result of heap snapshots
     */
    Object diff(HeapSnapshot before);

    /*! @brief Get heap view node by ID
     @param id node ID of number type
     @return Return the obtained heap view node
     */
    HeapGraphNode getNodeById(Integer id);

    /*! @brief Save HeapSnapshot with specified name
     @param fname snapshot name
    */
    save(String fname) async;

    /*! @brief time information */
    readonly Date time;

    /*! @brief root node of heap view */
    readonly HeapGraphNode root;

    /*! @brief list composed of heap view nodes */
    readonly NArray nodes;
};