/*! @brief hex module is a built-in module that provides hexadecimal implementation for encoding and decoding between binary data and ASCII characters. The `hex` module provides encoding and decoding functions

Using the encoding method, you can encode arbitrary binary data into a hexadecimal string. For example:

```JavaScript
const hex = require('hex')

const data = new Buffer([0x4e, 0x4f, 0x44, 0x45]) // [0x4e, 0x4f, 0x44, 0x45] => 'NODE'
const encodedData = hex.encode(data)
console.log(encodedData) // "4e4f4445"
```

Using the decoding method, you can decode a hexadecimal string back to the original binary data. For example:

```JavaScript
const hex = require('hex')

const encodedData = '4e4f4445' // 'NODE'
const decodedData = hex.decode(encodedData)
console.log(decodedData) // [0x4e, 0x4f, 0x44, 0x45]
```

As you can see, `hex` is a very simple encoding and decoding module, suitable for some simple conversion needs between binary data and strings.
 */
module hex
{
    /*! @brief Encode data in hex format
	 @param data Data to encode
	 @return Return the encoded string
	 */
    static String encode(Buffer data);

    /*! @brief Decode string to binary data in hex format
	 @param data String to decode
	 @return Return the decoded binary data
	 */
    static Buffer decode(String data);
};