/*! @brief HttpCollection is a general container for handling headers, query, form, cookie data in http messages

Take headers as an example to illustrate the usage of HttpCollection.

HttpCollection supports three forms of adding data:

1. Add a key-value data, adding data does not modify existing key-value data. `add`

```JavaScript
headers.add({
    'Content-Type': 'text/plain',
    'User-Agent': 'fibjs'
});
```

2. Add a set of data for a key-value, adding data does not modify existing key-value data. `add`

```JavaScript
headers.add('Set-Cookie', [
    'a=10',
    'b=20'
]);
```

3. Add a key-value data, adding data does not modify existing key-value data. `add`

```JavaScript
headers.add('Accept-Encoding', 'gzip');
```

The form of HttpCollection setting data is the same as adding, using the method `set`.

We can use `has` to check if the specified key-value data exists in the container

```JavaScript
const contentTypeExists = headers.has('Content-Type');
```

Use `first` to get the first value corresponding to a key in the container:

```JavaScript
const contentType = headers.first('Content-Type');
```

Use `all` to query all values of the specified key-value, return an array. If an empty string parameter is passed, return all values

```JavaScript
const cookieArray = headers.all('Set-Cookie');
const alls = headers.all();
```

Use `delete` method to delete all data of the specified key-value, return `true` indicates */
interface HttpCollection : object
{
    /*! @brief clear container data */
    clear();

    /*! @brief check if the specified key-value data exists in the container
     @param name specify the key-value to check
     @return return whether the key-value exists
     */
    Boolean has(String name);

    /*! @brief query the first value of the specified key-value
     @param name specify the key-value to query
     @return return the value corresponding to the key-value, if not exist, return undefined
     */
    Variant first(String name);

    /*! @brief query the first value of the specified key-value, equivalent to first
     @param name specify the key-value to query
     @return return the value corresponding to the key-value, if not exist, return undefined
     */
    Variant get(String name);

    /*! @brief query all values of the specified key-value
     @param name specify the key-value to query, pass empty string to return all key-value results
     @return return the array of all values corresponding to the key-value, if data does not exist, return null
     */
    NObject all(String name = "");

    /*! @brief query all values of the specified key-value
     @param name specify the key-value to query
     @return return the array of all values corresponding to the key-value, if data does not exist, return null
     */
    NArray getAll(String name);

    /*! @brief add a key-value data, adding data does not modify existing key-value data
     @param map specify the key-value data dictionary to add
     */
    append(Object map);

    /*! @brief add a set of data for a key-value, adding data does not modify existing key-value data
     @param name specify the key-value to add
     @param values specify the set of data to add
     */
    append(String name, Array values);

    /*! @brief add a set of data, adding data does not modify existing key-value data
     @param entries specify the set of data to add, format as [[<key>, <value>]]
     */
    append(Array entries);

    /*! @brief add a key-value data, adding data does not modify existing key-value data
     @param name specify the key-value to add
     @param value specify the data to add
     */
    append(String name, Variant value);

    /*! @brief set a key-value data, setting data will modify the first value corresponding to the key-value and clear the remaining data of the same key-value
     @param map specify the key-value data dictionary to set
     */
    set(Object map);

    /*! @brief set a set of data for a key-value, setting data will modify the value corresponding to the key-value and clear the remaining data of the same key-value
     @param name specify the key-value to set
     @param values specify the set of data to set
     */
    set(String name, Array values);

    /*! @brief set a key-value data, setting data will modify the first value corresponding to the key-value and clear the remaining data of the same key-value
     @param name specify the key-value to set
     @param value specify the data to set
     */
    set(String name, Variant value);

    /*! @brief delete all values of the specified key-value
     @param name specify the key-value to delete
     */
    remove(String name);

    /*! @brief delete all values of the specified key-value
     @param name specify the key-value to delete
     */
    delete(String name);

    /*! @brief sort the content in the container by key-value
     */
    sort();

    /*! @brief traverse the content in the container
     @param callback specify the function called during traversal, function parameters are (value, key, object)
     */
    forEach(Function callback);

    /*! @brief traverse the content in the container
     @param callback specify the function called during traversal, function parameters are (value, key, object)
     @param thisArg specify the this object of the callback function
     */
    forEach(Function callback, Value thisArg);

    /*! @brief query the key-values in the container
     @return return the iterator containing all key-values
     */
    Iterator keys();

    /*! @brief query the values in the container
     @return return the iterator containing all values
     */
    Iterator values();

    /*! @brief query the key-values and values in the container
     @return return the iterator containing all key-values and values
     */
    Iterator entries();

    /*! @brief allow direct access to values using key-value subscript */
    Variant operator[String];

    /*! @brief query the iterator of current object elements
     @return return the iterator of current object elements
    */
    Iterator @iterator();
};