/*! @brief HttpRequest is a class for handling HTTP requests, it allows you to create HTTP requests and interact with servers. You can use it to send GET, POST and other types of HTTP requests to web servers.

Assume we have a query parameter with key 'name', we return different results based on this parameter: if the parameter is empty, return "Hello world!"; if the parameter is "fibjs", return "Hello fibjs!"; otherwise return "Hello some body!".

The code implementation is as follows:
```JavaScript
const http = require('http');

var svr = new http.Server(8080, (req) => {
  var name = req.query.get('name');
  var msg = name ? `Hello ${name}!` : 'Hello world!';
  
  req.response.write(msg);
});

svr.start();
```

Here we used `req.query` this Collection type, which represents the query parameters in the HTTP request URL.

We access the service program through the browser at http://127.0.0.1:8080/?name=fibjs and get the server response content `Hello fibjs!`.
 */
interface HttpRequest : HttpMessage
{
    /*! @brief HttpRequest constructor, creates a new HttpRequest object */
    HttpRequest();

    /*! @brief Get the response message object*/
    readonly HttpResponse response;

    /*! @brief Query and set the request method */
    String method;

    /*! @brief Query and set the request address */
    String address;

    /*! @brief Get or set the request URL path with query string, e.g. /path?key=value */
    String url;

    /*! @brief Get the complete URL of the request, including protocol, host, path and query string */
    readonly String href;

    /*! @brief Query and set the request query string */
    String queryString;

    /*! @brief Get the container containing the message cookies*/
    readonly HttpCollection cookies;

    /*! @brief Get the container containing the message form*/
    readonly FormData form;

    /*! @brief Get the container containing the message query*/
    readonly URLSearchParams query;
};