/*! @brief http protocol conversion handler

  Used to convert data streams to http protocol messages, creation method:
  ```JavaScript
  var hdlr = new mq.HttpHandler(...);
  ```
  or:
  ```JavaScript
  var hdlr = new http.Handler(...);
  ```
 */
interface HttpHandler : Handler
{
    /*! @brief Create an http protocol handler object, convert the data of the stream object into http message objects
    @param hdlr Built-in message handler, processing function, chain processing array, routing object, see mq.Handler for details
    */
    HttpHandler(Handler hdlr);

    /*! @brief Allow cross-origin requests
     @param allowHeaders Specify accepted http header fields
     */
    enableCrossOrigin(String allowHeaders = "Content-Type");

    /*! @brief Query and set the maximum number of request headers, default 128 */
    Integer maxHeadersCount;

    /*! @brief Query and set the maximum request header length, default 8192 */
    Integer maxHeaderSize;

    /*! @brief Query and set the maximum body size in MB, default 64 */
    Integer maxBodySize;

    /*! @brief Auto-decompression function switch, default off */
    Boolean enableEncoding;

    /*! @brief Query and set the server name, default: fibjs/0.x.0 */
    String serverName;

    /*! @brief http protocol conversion handler current event handler interface object */
    Handler handler;
};