/*! @brief http base message object */
interface HttpMessage : Message
{
    /*! @brief Protocol version information, allowed format: HTTP/#.# */
    String protocol;

    /*! @brief Container containing http headers in the message, read-only property */
    readonly Headers headers;

    /*! @brief Query and set whether to keep connection */
    Boolean keepAlive;

    /*! @brief Query and set whether it is an upgrade protocol */
    Boolean upgrade;

    /*! @brief Query and set the maximum number of request headers, default 128 */
    Integer maxHeadersCount;

    /*! @brief Query and set the maximum request header length, default 8192 */
    Integer maxHeaderSize;

    /*! @brief Query and set the maximum chunk size in MB, default 2 */
    Integer maxChunkSize;

    /*! @brief Query and set the maximum body size in MB, default 64 */
    Integer maxBodySize;

    /*! @brief Query the source socket of the current object */
    readonly Stream socket;

    /*! @brief Check if the specified key-value message header exists
     @param name Specify the key-value to check
     @return Return whether the key-value exists
     */
    Boolean hasHeader(String name);

    /*! @brief Query the first message header of the specified key-value
     @param name Specify the key-value to query
     @return Return the value corresponding to the key-value, if it does not exist, return undefined
     */
    String firstHeader(String name);

    /*! @brief Query all message headers of the specified key-value
     @param name Specify the key-value to query, passing an empty string returns the results of all key-values
     @return Return the array of all values corresponding to the key-value, if the data does not exist, return null
     */
    NObject allHeader(String name = "");

    /*! @brief Add a message header, adding data does not modify existing key-value message headers
     @param map Specify the key-value data dictionary to add
     */
    appendHeader(Object map);

    /*! @brief Add message headers, adding data does not modify existing key-value message headers
     @param headers Specify the Headers object to add
     */
    appendHeader(Headers headers);

    /*! @brief Add a group of message headers of the specified name, adding data does not modify existing key-value message headers
     @param name Specify the key-value to add
     @param values Specify the group of data to add
     */
    appendHeader(String name, Array values);

    /*! @brief Add a message header, adding data does not modify existing key-value message headers
     @param name Specify the key-value to add
     @param value Specify the data to add
     */
    appendHeader(String name, String value);

    /*! @brief Set a message header, setting data will modify the first value corresponding to the key-value and clear the remaining message headers of the same key-value
     @param map Specify the key-value data dictionary to set
     */
    setHeader(Object map);

    /*! @brief Set message headers, setting data will modify the values corresponding to the key-values and clear the remaining message headers of the same key-values
     @param headers Specify the Headers object to set
     */
    setHeader(Headers headers);

    /*! @brief Set a group of message headers of the specified name, setting data will modify the values corresponding to the key-values and clear the remaining message headers of the same key-values
     @param name Specify the key-value to set
     @param values Specify the group of data to set
     */
    setHeader(String name, Array values);

    /*! @brief Set a message header, setting data will modify the first value corresponding to the key-value and clear the remaining message headers of the same key-value
     @param name Specify the key-value to set
     @param value Specify the data to set
     */
    setHeader(String name, String value);

    /*! @brief Delete all message headers of the specified key-value
     @param name Specify the key-value to delete
     */
    removeHeader(String name);
};