/*! @brief json encoding and decoding module
 Reference method:
 ```JavaScript
 var encoding = require('encoding');
 var json = encoding.json;
 ```
 or
 ```JavaScript
 var json = require('json');
 ```
 */
module json
{
    /*! @brief Encode variable in json format
	 @param data Variable to encode
	 @return Return the encoded string
	 */
    static String encode(Value data);

    /*! @brief Decode string to a variable in json format
	 @param data String to decode
	 @return Return the decoded variable
	 */
    static Value decode(String data);
};