/*! @brief LevelDB is the built-in database operation object of fibjs, used to create and manage dictionary objects in the form of key-value pairs. Using LevelDB object, you can easily implement storage, query, deletion, enumeration and other operations of key-value pair data. It is based on Google's open source LevelDB implementation, with advantages such as high efficiency, reliability, and scalability

Creating LevelDB object is very simple, just create a database object with a specified name through db.openLevelDB method. For example:

```JavaScript
var db = require("db");
var test = db.openLevelDB("test.db");
```

Where, db is the database operation object of fibjs, openLevelDB method is used to open leveldb database, test.db is the database name, the test object returned by the function is the object for operating the database.

The main operations supported by LevelDB object include:

- set(key, value): set a key-value data, insert new data if the key does not exist.
- get(key): query the value of the specified key.
- has(key): determine whether the specified key exists.
- remove(key): delete all values of the specified key.
- forEach(func): enumerate all key-value pairs in the database.
- between(from, to, func): enumerate key-value pairs in the database where the key is between from and to.
- toJSON(key): return the JSON format representation of the object, generally return the readable property collection defined by the object.
- begin(): start a transaction on the current database.
- commit(): commit the current transaction.
- close(): close the current database connection or transaction.

For example:

```JavaScript
var db = require("db");
var test = db.openLevelDB("test.db");

test.set("test_key", "test_value");

var value = test.get("test_key");
console.log("test_key:", value.toString());

test.remove("test_key");

console.log("has test_key:", test.has("test_key"));

test.close();
```

The above is the basic usage and example of LevelDB object, which can conveniently and flexibly operate key-value pair data. In practical applications, it can be used for storage, caching, logging and other scenarios, improving data read and write efficiency, simplifying program logic, reducing development complexity, etc.
 */
interface LevelDB : object
{
    /*! @brief Check if the specified key data exists in the database
     @param key specifies the key to check
     @return returns whether the key exists
     */
    Boolean has(Buffer key) async;

    /*! @brief Query the value of the specified key
     @param key specifies the key to query
     @return returns the value corresponding to the key, if it does not exist, returns null
     */
    Buffer get(Buffer key) async;

    /*! @brief Query the values of a group of specified keys
     @param keys specifies the array of keys to query
     @return returns the array containing the keys
     */
    NArray mget(Array keys);

    /*! @brief Set a key-value data, insert new data if the key does not exist
     @param key specifies the key to set
     @param value specifies the data to set
     */
    set(Buffer key, Buffer value) async;

    /*! @brief Set a group of key-value data, insert new data if the key does not exist
     @param map specifies the key-value data dictionary to set
     */
    mset(Object map);

    /*! @brief Delete the values of a group of specified keys
     @param keys specifies the array of keys to delete
     */
    mremove(Array keys);

    /*! @brief Delete all values of the specified key
     @param key specifies the key to delete
     */
    remove(Buffer key) async;

    /*! @brief Query the smallest key
      @return returns the smallest key
     */
    Buffer firstKey() async;

    /*! @brief Query the largest key
    @return returns the largest key */
    Buffer lastKey() async;

    /*! @brief Enumerate all key-value pairs in the database

     The callback function has two parameters, (value, key)

     ```JavaScript
     var db = require("db");
     var test = new db.openLevelDB("test.db");

     test.forEach(function(value, key){
        ...
     });
     ```
     @param func enumeration callback function
     */
    forEach(Function func);

    /*! @brief Enumerate all key-value pairs in the database

     The callback function has two parameters, (value, key)

     ```JavaScript
     var db = require("db");
     var test = new db.openLevelDB("test.db");

     test.forEach("aaa", "bbb", function(value, key){
        ...
     });
     ```
     @param from the minimum key for enumeration, included when enumerating
     @param func enumeration callback function
     */
    forEach(Buffer from, Function func);

    /*! @brief Enumerate all key-value pairs in the database

     The callback function has two parameters, (value, key)

     ```JavaScript
     var db = require("db");
     var test = new db.openLevelDB("test.db");

     test.forEach("aaa", "bbb", function(value, key){
        ...
     });
     ```
     @param from the minimum key for enumeration, included when enumerating
     @param to the maximum key for enumeration, not included when enumerating
     @param func enumeration callback function
     */
    forEach(Buffer from, Buffer to, Function func);

    /*! @brief Enumerate all key-value pairs in the database

     The callback function has two parameters, (value, key)

     ```JavaScript
     var db = require("db");
     var test = new db.openLevelDB("test.db");

     test.forEach(function(value, key){
        ...
     });
     ```
     @param opt enumeration options, support skip, limit, reverse
     @param func enumeration callback function
     */
    forEach(Object opt, Function func);

    /*! @brief Enumerate all key-value pairs in the database

     The callback function has two parameters, (value, key)

     ```JavaScript
     var db = require("db");
     var test = new db.openLevelDB("test.db");

     test.forEach("aaa", "bbb", function(value, key){
        ...
     });
     ```
     @param from the minimum key for enumeration, included when enumerating
     @param opt enumeration options, support skip, limit, reverse
     @param func enumeration callback function
     */
    forEach(Buffer from, Object opt, Function func);

    /*! @brief Enumerate all key-value pairs in the database

     The callback function has two parameters, (value, key)

     ```JavaScript
     var db = require("db");
     var test = new db.openLevelDB("test.db");

     test.forEach("aaa", "bbb", function(value, key){
        ...
     });
     ```
     @param from the minimum key for enumeration, included when enumerating
     @param to the maximum key for enumeration, not included when enumerating
     @param opt enumeration options, support skip, limit, reverse
     @param func enumeration callback function
     */
    forEach(Buffer from, Buffer to, Object opt, Function func);

    /*! @brief Start a transaction on the current database
     @return returns the started transaction object */
    LevelDB begin();

    /*! @brief Commit the current transaction */
    commit();

    /*! @brief Close the current database connection or transaction */
    close() async;
};