/*! @brief Lock is a built-in object, it can be used to control fiber concurrent access, a fiber can acquire the lock to prevent other fibers from acquiring it at the same time. Lock can be created through coroutine.Lock() function

Common situation is, in a multi-threaded scenario, when multiple threads want to modify the same data, data inconsistency will occur. For example, two threads want to modify the same value in the same data, in uncontrolled situations, may produce inconsistent results. At this time, using Lock object, can achieve mutual exclusive access to the same data.

Below is a simple example, using Lock to make two fibers execute alternately, and the shared variable v is not 300.

```JavaScript
var coroutine = require("coroutine")

var l = new coroutine.Lock()
var v = 100
function f() {
    l.acquire()
    v = 200
    coroutine.sleep(1)
    v = 300
    l.release()
}
coroutine.start(f)

coroutine.sleep(1)

l.acquire()
assert.notEqual(300, v)
assert.equal(200, v)
l.release()
```

First created a Lock object, and entered fiber f, acquired the lock and modified variable v, then released the lock. In the main thread, first wait for fiber f to complete... When fiber f released the Lock, the main thread starts to acquire the Lock, ensuring the value of variable v is changed to 300.
 */
interface Lock : object
{
    /*! @brief Constructor*/
    Lock();

    /*! @brief Acquire the ownership of the lock

     The acquire method is used to acquire the ownership of the lock, when the lock is in acquirable state, this method immediately returns true.

     When the lock is not acquirable, and blocking is true, the current fiber enters sleep, when other fibers release the lock, this method returns true.

     When the lock is not acquirable, and blocking is false, the method returns false.
     @param blocking specifies whether to wait, true to wait, default true
     @return returns whether successfully acquired the lock, true means successfully acquired
     */
    Boolean acquire(Boolean blocking = true) async;

    /*! @brief Release the ownership of the lock

     This method will release the ownership of the lock, if the current fiber does not own the lock, this method will throw an error.
     */
    release();

    /*! @brief Query the current number of waiting tasks
     @return returns the number of tasks
     */
    Integer count();
};