/*! @brief Memory stream object

 MemoryStream object creates a memory-based stream object, creation method:
 ```JavaScript
 var ms = new io.MemoryStream();
 ```
 */
interface MemoryStream : SeekableStream
{
    /*! @brief MemoryStream constructor */
    MemoryStream();

    /*! @brief Force set the last update time of the memory stream object
     @param d Specify the time to set
     */
    setTime(Date d);

    /*! @brief Create a read-only copy of the current memory stream
     @return Return a read-only memory stream object
     */
    MemoryStream clone();

    /*! @brief Clear memory file data, reset pointer */
    clear();
};