/*! @brief Menu item interface, inherits from EventEmitter. */
interface MenuItem : EventEmitter
{
    /*! @brief Unique identifier of the menu item. */
    String id;

    /*! @brief Type of the menu item. */
    readonly String type;

    /*! @brief Icon of the menu item. */
    String icon;

    /*! @brief Label of the menu item. */
    String label;

    /*! @brief Tooltip of the menu item. */
    String tooltip;

    /*! @brief Whether the menu item is enabled. */
    Boolean enabled;

    /*! @brief Whether the menu item is checked. */
    Boolean checked;

    /*! @brief Submenu. */
    readonly Menu submenu;

    /*! @brief Click event handler for the menu item. */
    event click();
};