/*! @brief Message queue module */
module mq
{
    /*! @brief Create a message object, see Message */
    static Message;

    /*! @brief Create an http protocol handler object, see HttpHandler */
    static HttpHandler;

    /*! @brief Create a message handler object, if the value is a built-in handler, return directly

     hdlr accepts built-in message handlers, processing functions, chain processing arrays, routing objects:
     - Function javascript function, will use this function for processing
     - Handler built-in handler, will use this handler for processing
     - Chain processing array, equivalent to returning new mq.Chain(hdlr), see Chain
     - Routing object, equivalent to returning new mq.Routing(hdlr), see Routing

     Message processing function syntax is as follows:
     ```JavaScript
     function func(v){
     }
     ```
     Parameter v is the message being processed, return result allows four types:
     - Function javascript function, will use this function for next stage processing
     - Handler built-in handler, will use this handler for next stage processing
     - Chain processing array, equivalent to new mq.Chain(v), see Chain
     - Routing object, equivalent to new mq.Routing(v), see Routing

     No return or other return results will end message processing.
     @param hdlr Built-in message handler, processing function, chain processing array, routing object
     @return Return the handler encapsulating the processing function
     */
    static Handler;

    /*! @brief Create a message handler chain processing object, see Chain */
    static Chain;

    /*! @brief Create a message handler routing object, see Routing*/
    static Routing;

    /*! @brief Create an empty handler object, this handler object does nothing and returns directly
     @return Return empty processing function
     */
    static Handler nullHandler();

    /*! @brief Process a message or object using the given handler

    Unlike the handler's invoke method, this method will cyclically call the return handler of each handler until the handler returns null.
     @param hdlr Specify the handler to use
     */
    static invoke(Handler hdlr, object v) async;
};