/*! @brief Network access module

 Basic module. Can be used to create and operate network resources, reference method:
 ```JavaScript
 var net = require('net');
 ```
 */
module net
{
    /*! @brief Address family constant, specify unix socket */
    const AF_UNIX = 1;

    /*! @brief Address family constant, specify Windows pipe */
    const AF_PIPE = 1;

    /*! @brief Address family constant, specify ipv4*/
    const AF_INET = 2;

    /*! @brief Address family constant, specify ipv6*/
    const AF_INET6 = 10;

    /*! @brief Query and set whether socket backend uses uv, default is false */
    static Boolean use_uv_socket;

    /*! @brief Query current runtime environment network information
     @return Return network card information
    */
    static Object info();

    /*! @brief Query the address of the given hostname
     @param name Specify hostname
     @param family Specify query return type, default is AF_INET
     @return Return queried ip string
     */
    static String resolve(String name, Integer family = AF_INET) async;

    /*! @brief Fast query hostname address, equivalent to resolve(name)
     @param name Specify hostname
     @return Return queried ip string
     */
    static String ip(String name) async;

    /*! @brief Fast query hostname ipv6 address, equivalent to resolve(name, net.AF_INET6)
     @param name Specify hostname
     @return Return queried ipv6 string
     */
    static String ipv6(String name) async;

    /*! @brief Create a Socket object, see Socket */
    static Socket;

    /*! @brief Create a Socket or SslSocket object and establish connection
     @param url Specify connection protocol, can be: tcp://host:port or ssl://host:port, or unix:/usr/local/proc1 or pipe://./pipe/proc1, when connecting pipe, need to replace \ with /
     @param timeout Specify timeout time in milliseconds, default is 0
     @return Return successfully connected Socket or SslSocket object
     */
    static Stream connect(String url, Integer timeout = 0) async;

    /*! @brief Create a Socket object and establish connection
     @param port Specify peer port
     @param host Specify peer address or hostname, default is localhost
     @param timeout Specify timeout time in milliseconds, default is 0
     @return Return successfully connected Socket object
     */
    static Stream connect(Integer port, String host = "localhost", Integer timeout = 0) async;

    /*! @brief Create a Socket object and establish connection

     options parameter can contain the following properties:
      - port: Specify peer port
      - host: Specify peer address or hostname
      - timeout: Specify timeout time in milliseconds, default is 0

     @param options Specify connection options object
     @return Return successfully connected Socket object
     */
    static Stream connect(Object options) async;

    /*! @brief Establish a connection, and trigger connect event after connection is established
     @param port Specify peer port
     @param connectListener Specify once connect event listener
     @return Return connected Socket object
     */
    static Stream connect(Integer port, Function connectListener) async;

    /*! @brief Establish a connection, and trigger connect event after connection is established
     @param port Specify peer port
     @param host Specify peer address or hostname, default is localhost
     @param connectListener Specify once connect event listener
     @return Return connected Socket object
     */
    static Stream connect(Integer port, String host, Function connectListener) async;

    /*! @brief Establish a connection, and trigger connect event after connection is established
     @param port Specify peer port
     @param host Specify peer address or hostname, default is localhost
     @param timeout Specify timeout time in milliseconds, default is 0
     @param connectListener Specify once connect event listener
     @return Return connected Socket object
     */
    static Stream connect(Integer port, String host, Integer timeout, Function connectListener) async;

    /*! @brief Establish a connection, and trigger connect event after connection is established
     @param path Specify unix socket or Windows pipe path
     @param connectListener Specify once connect event listener
     @return Return connected Socket object
     */
    static Stream connect(String path, Function connectListener) async;

    /*! @brief Establish a connection, and trigger connect event after connection is established
     @param path Specify unix socket or Windows pipe path
     @param timeout Specify timeout time in milliseconds, default is 0
     @param connectListener Specify once connect event listener
     @return Return connected Socket object
     */
    static Stream connect(String path, Integer timeout, Function connectListener) async;

    /*! @brief Establish a connection, and trigger connect event after connection is established
     @param options Specify connection options object, can contain the following properties:
     @param connectListener Specify once connect event listener
     @return Return connected Socket object
     */
    static Stream connect(Object options, Function connectListener) async;

    /*! @brief Create an Smtp object, see Smtp */
    static Smtp;

    /*! @brief Create an Smtp object and establish connection, see Smtp
     @param url Specify connection protocol, can be: tcp://host:port or ssl://host:port
     @param timeout Specify timeout time in milliseconds, default is 0
     @return Return successfully connected Smtp object
     */
    static Smtp openSmtp(String url, Integer timeout = 0) async;

    /*! @brief Create a TcpServer object, see TcpServer */
    static TcpServer;

    /*! @brief Create a TCP server
     @param options Server options object, can contain the following properties:
      - address: Specify listening address, default is all addresses
      - port: Specify listening port, optional. If not provided, call listen() to start
     @param listener Connection handler function
     @return Return TcpServer object
     */
    static TcpServer createServer(Object options, Handler listener);

    /*! @brief Create a TCP server
     @param listener Connection handler function
     @return Return an unbound TcpServer object, call listen() to start
     */
    static TcpServer createServer(Handler listener);

    /*! @brief Create a UrlObject object, see UrlObject */
    static UrlObject new Url();

    /*! @brief Query current system asynchronous network engine
     @return Return network engine name
    */
    static String backend();

    /*! @brief Detect if input is IP address
     @param ip Specify string to detect
     @return Return 0 for invalid IP address, 4 for IPv4, 6 for IPv6
    */
    static Integer isIP(String ip = "");

    /*! @brief Detect if input is IPv4 address
     @param ip Specify string to detect
     @return Return true if IPv4, otherwise false
    */
    static Boolean isIPv4(String ip = "");

    /*! @brief Detect if input is IPv6 address
     @param ip Specify string to detect
     @return Return true if IPv6, otherwise false
    */
    static Boolean isIPv6(String ip = "");
};