/*! @brief The `os` module is one of the core modules, used for operating system functions. It provides utility functions for interacting with the operating system, including file addresses, file paths, network interfaces, hostnames, operating system types, etc.

### Common methods

There are many methods provided in the `os` module, here are several commonly used ones:

#### os.hostname()

Get the hostname of the current computer.

Example code:

```JavaScript
const os = require('os');
const hostname = os.hostname();
console.log(hostname);
```

Return result similar to:

```sh
localhost
```

#### os.type()

Get the name of the current operating system.

Example code:

```JavaScript
const os = require('os');
const type = os.type();
console.log(type);
```

Return result similar to:

```sh
Windows_NT
```

#### os.release()

Get the version of the current operating system.

Example code:

```JavaScript
const os = require('os');
const release = os.release();
console.log(release);
```

Return result similar to:

```sh
10.0.18362
```

#### os.arch()

Get the processor architecture of the operating system.

Example code:

```JavaScript
const os = require('os');
const arch = os.arch();
console.log(arch);
```

Return result similar to:

```sh
x64
```

#### os.cpus()

Get CPU information.

Example code:

```JavaScript
const os = require('os');
const cpus = os.cpus();
console.log(cpus);
```

Return result similar to:

```sh
[
  { model: 'Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz', speed: 2592, times: { user: 2400298, nice: 0, sys: 9684894, idle: 91516801, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz', speed: 2592, times: { user: 464927, nice: 0, sys: 1454926, idle: 95119061, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz', speed: 2592, times: { user: 232077, nice: 0, sys: 898942, idle: 95482112, irq: 0 } },
  { model: 'Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz', speed: 2592, times: { user: 950448, nice: 0, sys: 1875169, idle: 93117788, irq: 0 } }
]
```
 */
module os
{
    /*! @brief Service constructor, see Service */
    static Service;

    /*! @brief Query current runtime environment hostname 
     @return Return hostname
    */
    static String hostname();

    /*! @brief Query current CPU endianness
     @return Return endianness
    */
    static String endianness();

    /*! @brief Query current runtime environment operating system name 
     @return Return system name
    */
    static String type();

    /*! @brief Query current runtime environment operating system version
     @return Return version information
     */
    static String release();

    /*! @brief Query current user directory 
     @return Return directory string
    */
    static String homedir();

    /*! @brief Query current cpu environment
     @return Return cpu type, possible results are 'amd64', 'arm', 'arm64', 'ia32' 
    */
    static String arch();

    /*! @brief Query runtime environment current timezone */
    static readonly Integer timezone;

    /*! @brief Query current runtime environment line ending identifier, posix:"\\n"; windows:"\\r\\n"   */
    static readonly String EOL;

    /*! OS module constants object, see os_constants */
    static constants = os_constants;

    /*! @brief Query runtime environment 1 minute, 5 minutes, 15 minutes average load
     @return Return array containing three load data
    */
    static Array loadavg();

    /*! @brief Query runtime environment total memory in bytes
     @return Return memory data
    */
    static Long totalmem();

    /*! @brief Query runtime environment available memory in bytes
     @return Return memory data
    */
    static Long freemem();

    /*! @brief Query current runtime environment cpu count and parameters
     @return Return array containing cpu parameters, each item corresponds to one cpu
    */
    static Array cpus();

    /*! @brief Query current runtime environment cpu count
     @return Return cpu count
    */
    static Integer cpuNumbers();

    /*! @brief Query current runtime environment temporary file directory
     @return Return temporary file directory
    */
    static String tmpdir();

    /*! @brief Return current effective execution user information
     @param options Character encoding used to interpret result string
     @return Current effective execution user information
    */
    static Object userInfo(Object options = {});

    /*! @brief Query current runtime environment network information
     @return Return network card information
    */
    static Object networkInterfaces();

    /*! @brief Query current platform name
     @return Return platform name, possible results are 'darwin', 'freebsd', 'linux', or 'win32' 
     */
    static String platform();

    /*! @brief Parse time string or query runtime environment current time
     @param tmString Time string, default query current time
     @return Return javascript Date object
     */
    static Date time(String tmString = "");

    /*! @brief Time calculation function, calculate time according to part specified
     @param d Specify Date object for calculation
     @param num Specify calculation value
     @param part Specify calculation time part, accepts values: "year", "month", "day", "hour", "minute", "second"
     @return Return javascript Date object
     */
    static Date dateAdd(Date d, Integer num, String part);
};