/*! @brief os_constants dlopen sub-module, contains dynamic linker flags constants

 Usage:
 ```JavaScript
 var dlopen = require('os').constants.dlopen
 ```
 */
module os_constants_dlopen
{
    const RTLD_LAZY = 1;
    const RTLD_NOW = 2;
    const RTLD_GLOBAL = 256;
    const RTLD_LOCAL = 0;
    const RTLD_DEEPBIND = 8;
};
