/*! @brief File path processing module

 Reference method:
 ```JavaScript
 var path = require('path').win32;
 ```
 */
module path_win32
{
    /*! @brief Normalize the path, handle parent directory information in the path

     @param path The given unprocessed path
     @return Return the processed path
     */
    static String normalize(String path);

    /*! @brief Query the file name in the path, if extension is specified, automatically remove the matching extension

     @param path The given path to query
     @param ext Specify the extension, if the file name has a matching extension, it will be automatically removed
     @return Return the file name
     */
    static String basename(String path, String ext = "");

    /*! @brief Query the file extension in the path

     @param path The given path to query
     @return Return the obtained extension
     */
    static String extname(String path);

    /*! @brief Try to format an object as a path

     pathObject supports the following fields:
     ```JavaScript
     {
         "dir": "", // specify the directory of the path
         "root": "", // specify the root of the path
         "base": "", // specify the base of the path, it's the combination of name and ext
         "name": "", // specify the name of the path
         "ext": "", // specify the ext of the path
     }
     ```
     @param pathObject Specify parameters
     @return Return the formatted path
     */
    static String format(Object pathObject);

    /*! @brief Parse the path into a path object

     @param path Path
     @return Return pathObject object
     */
    static NObject parse(String path);

    /*! @brief Query the directory path in the path

     @param path The given path to query
     @return Return the obtained directory path
     */
    static String dirname(String path);

    /*! @brief Convert the given path to a full path

     @param path The given path to convert
     @return Return the converted full path
     */
    static String fullpath(String path);

    /*! @brief Identify whether the given path matches the given pattern

     @param path The given path to identify
     @param pattern Specify the matching pattern
     @return Return the matching result
     */
    static Boolean matchesGlob(String path, String pattern);

    /*! @brief Identify whether the given path is an absolute path

     @param path The given path to identify
     @return Return true if it is an absolute path
     */
    static Boolean isAbsolute(String path);

    /*! @brief Merge a series of paths into a single path

     @param ps One or more related paths
     @return Return the obtained new path
     */
    static String join(...ps);

    /*! @brief Merge a series of paths into an absolute path

     @param ps One or more related paths
     @return Return the obtained new path
     */
    static String resolve(...ps);

    /*! @brief Find the relative path from _from to to

     @param _from Source path
     @param to Target path
     @return Return the obtained relative path
     */
    static String relative(String _from, String to);

    /*! @brief Convert to namespace-prefixed path. Only valid on windows, return directly on other systems.
    see: https://msdn.microsoft.com/library/windows/desktop/aa365247(v=vs.85).aspx#namespaces
     @param path The given path.
     @return Return the obtained new path
     */
    static Value toNamespacedPath(Value path = undefined);

    /*! @brief Query the path separator character of the current operating system, posix returns '/', windows returns '\\'
     */
    const sep = "\\";

    /*! @brief Query the multi-path combination character of the current operating system, posix returns ':', windows returns ';'
     */
    const delimiter = ";";

    /*! @brief posix implementation, see path_posix
     */
    static readonly Object posix;

    /*! @brief windows implementation, see path_win32
     */
    static readonly Object win32;
};