/*! @brief PerformanceObserver interface for observing performance records

 PerformanceObserver interface is used to observe performance records. It allows you to register a callback function that will be called when a new performance record is added to the browser's performance buffer. You can use the PerformanceObserver interface to observe specific types of performance records, such as resource loading times, user input delays, etc.
*/
interface PerformanceObserver : object
{
    /*! @brief Constructor

     @param callback This callback function will be called when a new performance record is added to the browser's performance buffer
    */
    PerformanceObserver(Function callback);

    /*! @brief Register observed resource types

     options is an object containing the following properties:
       - type: observed resource type
       - entryTypes: list of observed resource types

     @param options Observed resource types
    */
    observe(Object options);

    /*! @brief Unregister observed resource types */
    disconnect();

    /*! @brief Get records of observed resource types
     @return Return records of observed resource types
    */
    NArray takeRecords();
};