/*! @brief PerformanceEntry interface provides common properties for performance records */
interface PerformanceEntry : object
{
    /*! @brief Name of the performance record. */
    readonly String name;

    /*! @brief Type of the performance record. */
    readonly String entryType;

    /*! @brief Start time of the performance record. */
    readonly Number startTime;

    /*! @brief Duration of the performance record. */
    readonly Number duration;
};