/*! @brief PerformanceMeasure interface provides detailed information for performance measure records.*/
interface PerformanceMeasure : PerformanceEntry
{
    /*! @brief Detailed information of the performance measure record. */
    readonly Value detail;
};