
/*! @brief punycode Internationalized Domain translation modules
Punycode is a character encoding scheme defined by RFC 3492 that is primarily intended for use in Internationalized Domain Names. Because host names in URLs are limited to ASCII characters only, Domain Names that contain non-ASCII characters must be converted into ASCII using the Punycode scheme.

 example:
 ```JavaScript
 var punycode = require('punycode');
 ```
 */
module punycode
{
    /*! @brief  Converts a string of Unicode codepoints to a Punycode string of ASCII-only characters.
	 @param domain String in Unicode
	 @return a Punycode string of ASCII-only characters.
	 */
    static String encode(String domain);

    /*! @brief Converts a Punycode string of ASCII-only characters to the equivalent string of Unicode codepoints.
	 @param domain a Punycode string of ASCII-only characters
	 @return string of Unicode codepoints.
	 */
    static String decode(String domain);

    /*! @brief Converts a Unicode string representing an Internationalized Domain Name to Punycode. Only the non-ASCII parts of the domain name will be converted. Calling punycode.toASCII() on a string that already only contains ASCII characters will have no effect.
	 @param domain a Unicode string representing an Internationalized Domain Name
	 @return a punycode string representing an an Internationalized Domain Name
	 */
    static String toASCII(String domain);

    /*! @brief Converts a string representing a domain name containing Punycode encoded characters into Unicode. Only the Punycode encoded parts of the domain name are be converted.
	 @param domain a string representing a domain name containing Punycode encoded characters
	 @return a Unicode string representing an Internationalized Domain Name
	 */
    static String toUnicode(String domain);
};
