/*! @brief Range query stream read object

 RangeStream object is used to truncate data from SeekableStream objects. Creation method:
 ```JavaScript
 var stm = new io.RangeStream(stream, '0-10');
 stm.end // 11

 var stm = new io.RangeStream(stream, 0, 10);
 stm.end // 10
 ```

 It can also limit the read length of a plain Stream object, with begin fixed at 0:
 ```JavaScript
 var stm = new io.RangeStream(stream, 1024);
 stm.begin // 0
 stm.end   // 1024
 ```
 If the passed stm is a SeekableStream, it is equivalent to RangeStream(stm, 0, end).
 */
interface RangeStream : SeekableStream
{
    /*! @brief RangeStream constructor
      @param stm RangeStream's binary base stream object, must be SeekableStream
      @param range String describing range, format 'begin-[end]', '[begin]-end'
     */
    RangeStream(SeekableStream stm, String range);

    /*! @brief RangeStream constructor
      @param stm RangeStream's binary base stream object, must be SeekableStream
      @param begin Starting position to read content from stm
      @param end Ending position to read content from stm
     */
    RangeStream(SeekableStream stm, Long begin, Long end);

    /*! @brief RangeStream constructor, used to limit read length of a plain Stream
      @param stm Base stream object, if it is a SeekableStream then equivalent to RangeStream(stm, 0, end)
      @param end Maximum bytes to read from stm
     */
    RangeStream(Stream stm, Long end);

    /*! @brief Query range start value */
    readonly Long begin;

    /*! @brief Query range end value */
    readonly Long end;
};