/*! @brief Redis database client object

 Used to create and manage Redis database, creation method:
 ```JavaScript
 var db = require("db");
 var test = new db.openRedis("redis-server");
 ```
 */
interface Redis : object
{
    /*! @brief Redis basic command method
     @param cmd Specifies the command to send
     @param args Specifies the parameters to send
     @return Returns the result returned by the server */
    Value command(String cmd, ...args);

    /*! @brief Associate a string value with a key, if the key already holds another value, SET overwrites the old value regardless of type
     @param key Specifies the key to associate
     @param value Specifies the data to associate
     @param ttl Sets the lifetime for the key in milliseconds; if ttl is 0, no lifetime is set */
    set(Buffer key, Buffer value, Long ttl = 0);

    /*! @brief Set the value of a key to value, only if the key does not exist. If the given key already exists, SETNX does nothing.
     @param key Specifies the key to associate
     @param value Specifies the data to associate
     @param ttl Sets the lifetime for the key in milliseconds; if ttl is 0, no lifetime is set */
    setNX(Buffer key, Buffer value, Long ttl = 0);

    /*! @brief Set the value of a key to value, only if the key already exists.
     @param key Specifies the key to associate
     @param value Specifies the data to associate
     @param ttl Sets the lifetime for the key in milliseconds; if ttl is 0, no lifetime is set */
    setXX(Buffer key, Buffer value, Long ttl = 0);

    /*! @brief Set one or more key-value pairs at the same time. If a given key already exists, MSET will overwrite the old value with the new one
     @param kvs Specifies the key/value object to set*/
    mset(Object kvs);

    /*! @brief Set one or more key-value pairs at the same time. If a given key already exists, MSET will overwrite the old value with the new one
     @param kvs Specifies the key/value list to set*/
    mset(...kvs);

    /*! @brief Set one or more key-value pairs at the same time, only if all given keys do not exist
     @param kvs Specifies the key/value object to set*/
    msetNX(Object kvs);

    /*! @brief Set one or more key-value pairs at the same time, only if all given keys do not exist
     @param kvs Specifies the key/value list to set*/
    msetNX(...kvs);

    /*! @brief If the key already exists and is a string, the append command appends the value to the end of the key's original value. If the key does not exist, append simply sets the given key to value
     @param key Specifies the key to append
     @param value Specifies the data to append
     @return The length of the string in the key after appending the value */
    Integer append(Buffer key, Buffer value);

    /*! @brief Overwrite the string value stored by the given key with the value parameter, starting from offset
     @param key Specifies the key to modify
     @param offset Specifies the byte offset to modify
     @param value Specifies the data to overwrite
     @return The length of the string after modification */
    Integer setRange(Buffer key, Integer offset, Buffer value);

    /*! @brief Return the substring of the string value stored by the key, determined by the start and end offsets (including start and end)
     @param key Specifies the key to query
     @param start Specifies the starting byte offset for the query
     @param end Specifies the ending byte offset for the query
     @return The extracted substring */
    Buffer getRange(Buffer key, Integer start, Integer end);

    /*! @brief Return the length of the string value stored by the key. Returns an error when the key stores a non-string value
     @param key Specifies the key to calculate
     @return The length of the string value. Returns 0 when the key does not exist */
    Integer strlen(Buffer key);

    /*! @brief Count the number of bits set to 1 in the given string
     @param key Specifies the key to calculate
     @param start Specifies the starting byte to calculate, can use negative values, -1 means the last byte, -2 means the second last byte, and so on
     @param end Specifies the ending byte to calculate, can use negative values, -1 means the last byte, -2 means the second last byte, and so on
     @return The number of bits set to 1 */
    Integer bitcount(Buffer key, Integer start = 0, Integer end = -1);

    /*! @brief Return the string value associated with the key, if the key does not exist, return the special value Null
     @param key Specifies the key to associate
     @return Returns Null when the key does not exist, otherwise returns the value of the key */
    Buffer get(Buffer key);

    /*! @brief Return the values of all (one or more) given keys. If a key in the given keys does not exist, that key returns the special value nil.
     @param keys Specifies the array of keys to query
     @return A list containing the values of all given keys */
    NArray mget(Array keys);

    /*! @brief Return the values of all (one or more) given keys. If a key in the given keys does not exist, that key returns the special value nil.
     @param keys Specifies the list of keys to query
     @return A list containing the values of all given keys */
    NArray mget(...keys);

    /*! @brief Set the value of the given key to value, and return the old value of the key
     @param key Specifies the key to query and modify
     @param value Specifies the value to modify
     @return Returns the old value of the given key */
    Buffer getset(Buffer key, Buffer value);

    /*! @brief Subtract the decrement from the value stored by the key
     @param key Specifies the key to modify
     @param num Specifies the value to subtract
     @return The value of the key after subtracting num */
    Long decr(Buffer key, Long num = 1);

    /*! @brief Add the increment to the value stored by the key
     @param key Specifies the key to modify
     @param num Specifies the value to add
     @return The value of the key after adding num */
    Long incr(Buffer key, Long num = 1);

    /*! @brief Set or clear the bit at the specified offset for the string value stored by the key
     @param key Specifies the key to modify
     @param offset Specifies the bit offset to modify
     @param value Specifies the parameter to set or clear, can be 0 or 1
     @return The bit originally stored at the specified offset */
    Integer setBit(Buffer key, Integer offset, Integer value);

    /*! @brief Get the bit at the specified offset for the string value stored by the key
     @param key Specifies the key to query
     @param offset Specifies the bit offset to query
     @return The bit at the specified offset of the string value */
    Integer getBit(Buffer key, Integer offset);

    /*! @brief Check if the given key exists
     @param key Specifies the key to associate
     @return Returns True if the key exists, otherwise returns False */
    Boolean exists(Buffer key);

    /*! @brief Return the type of the value stored by the key
     @param key Specifies the key to query
     @return Returns the type of the value stored by the key, possible values are none (key does not exist) string (string) list (list) set (set) zset (sorted set) hash (hash) */
    String type(Buffer key);

    /*! @brief Find all keys matching the given pattern
     @param pattern Specifies the query pattern
     @return List of keys matching the given pattern */
    NArray keys(String pattern);

    /*! @brief Delete one or more given keys, non-existent keys are ignored
     @param keys Specifies the array of keys to delete
     @return The number of deleted keys */
    Integer del(Array keys);

    /*! @brief Delete one or more given keys, non-existent keys are ignored
     @param keys Specifies the list of keys to delete
     @return The number of deleted keys */
    Integer del(...keys);

    /*! @brief Set a lifetime for the given key, when the key expires, it will be automatically deleted
     @param key Specifies the key to set
     @param ttl Sets the lifetime for the key in milliseconds
     @return Returns True if the key exists, otherwise returns False */
    Boolean expire(Buffer key, Long ttl);

    /*! @brief Return the remaining lifetime of the given key
     @param key Specifies the key to query
     @return Returns the remaining lifetime of the key in milliseconds, returns -2 when the key does not exist, returns -1 when the key exists but has no remaining lifetime set */
    Long ttl(Buffer key);

    /*! @brief Remove the lifetime of the given key, converting this key from 'volatile' (with lifetime) to 'persistent' (without lifetime, never expires)
     @param key Specifies the key to set
     @return Returns True if the key exists, otherwise returns False */
    Boolean persist(Buffer key);

    /*! @brief Rename the key to newkey, returns an error when key and newkey are the same, or when key does not exist
     @param key Specifies the key to rename
     @param newkey Specifies the target key to rename to */
    rename(Buffer key, Buffer newkey);

    /*! @brief Rename the key to newkey only if newkey does not exist, returns an error when key does not exist
     @param key Specifies the key to rename
     @param newkey Specifies the target key to rename to
     @return Returns True on successful modification, returns False if newkey already exists */
    Boolean renameNX(Buffer key, Buffer newkey);

    /*! @brief Subscribe to information from a given channel, automatically call func when a message occurs, func contains two parameters, channel and message in order, the same channel and function will only callback once
     @param channel Specifies the channel name to subscribe
     @param func Specifies the callback function
     */
    sub(Buffer channel, Function func);

    /*! @brief Subscribe to information from a group of channels, automatically call the corresponding callback functions when messages occur, the same channel and function will only callback once
     @param map Specifies the channel mapping, object property names will be used as channel names, property values will be used as callback functions
     */
    sub(Object map);

    /*! @brief Unsubscribe all callbacks for the given channel
     @param channel Specifies the channel name to unsubscribe
    */
    unsub(Buffer channel);

    /*! @brief Unsubscribe the specified callback function for the given channel
     @param channel Specifies the channel name to unsubscribe
     @param func Specifies the callback function to unsubscribe
    */
    unsub(Buffer channel, Function func);

    /*! @brief Unsubscribe all callbacks for a group of given channels
     @param channels Specifies the array of channels to unsubscribe
    */
    unsub(Array channels);

    /*! @brief Unsubscribe the specified callback functions for a group of given channels
     @param map Specifies the channel mapping, object property names will be used as channel names, property values will be used as callback functions
     */
    unsub(Object map);

    /*! @brief Subscribe to information from a group of channels according to the template, automatically call func when messages occur, func contains three parameters, channel, message and pattern in order, the same template and function will only callback once
     @param pattern Specifies the channel template to subscribe
     @param func Specifies the callback function
     */
    psub(String pattern, Function func);

    /*! @brief Subscribe to information from a group of channel templates, automatically call the corresponding func when messages occur, the same channel and function will only callback once
     @param map Specifies the channel mapping, object property names will be used as channel templates, property values will be used as callback functions
     */
    psub(Object map);

    /*! @brief Unsubscribe all callbacks for channels matching the given template
     @param pattern Specifies the channel template to unsubscribe
    */
    unpsub(String pattern);

    /*! @brief Unsubscribe the specified callback function for channels matching the given template
     @param pattern Specifies the channel template to unsubscribe
     @param func Specifies the callback function to unsubscribe
    */
    unpsub(String pattern, Function func);

    /*! @brief Unsubscribe all callbacks for channels matching a group of given templates
     @param patterns Specifies the array of channel templates to publish
    */
    unpsub(Array patterns);

    /*! @brief Unsubscribe the specified callback functions for channels matching a group of templates
     @param map Specifies the channel mapping, object property names will be used as channel templates, property values will be used as callback functions
     */
    unpsub(Object map);

    /*! @brief Query and set the error handling function, called back when sub encounters an error or network interruption, after the callback occurs, all subs of this object will be terminated
     */
    event suberror();

    /*! @brief Send the message to the specified channel
     @param channel Specifies the channel to publish
     @param message Specifies the message to publish
     @return The number of clients that received this message
    */
    Integer pub(Buffer channel, Buffer message);

    /*! @brief Get the Hash object for the specified key, this object is a client containing the specified key, only calling its methods will operate the database
     @param key Specifies the key to get
     @return Returns the Hash object containing the specified key */
    RedisHash getHash(Buffer key);

    /*! @brief Get the List object for the specified key, this object is a client containing the specified key, only calling its methods will operate the database
     @param key Specifies the key to get
     @return Returns the List object containing the specified key */
    RedisList getList(Buffer key);

    /*! @brief Get the Set object for the specified key, this object is a client containing the specified key, only calling its methods will operate the database
     @param key Specifies the key to get
     @return Returns the Set object containing the specified key */
    RedisSet getSet(Buffer key);

    /*! @brief Get the SortedSet object for the specified key, this object is a client containing the specified key, only calling its methods will operate the database
     @param key Specifies the key to get
     @return Returns the SortedSet object containing the specified key */
    RedisSortedSet getSortedSet(Buffer key);

    /*! @brief Serialize the given key and return the serialized value, use the restore command to deserialize this value back into a Redis key
     @param key Specifies the key to serialize
     @return Returns the serialized value, returns null if the key does not exist */
    Buffer dump(Buffer key);

    /*! @brief Deserialize the given serialized value and associate it with the given key
     @param key Specifies the key to deserialize
     @param data Specifies the data to deserialize
     @param ttl Sets the lifetime for the key in milliseconds; if ttl is 0, no lifetime is set*/
    restore(Buffer key, Buffer data, Long ttl = 0);

    /*! @brief Close the current database connection or transaction */
    close();
};