
/*! @brief Regular expression
 */
interface Regex : object
{
    /*! @brief Match in string
     @param str String to match
     @return Return array of results, null otherwise
     */
    Array exec(String str);

    /*! @brief Test to match a string
     @param str String to match
     @return Return true when pass test, false otherwise
     */
    Boolean test(String str);

    /*! @brief Get and set last match start position */
    Integer lastIndex;

    /*! @brief Check if expression has "g" sign to match glob */
    readonly Boolean global;

    /*! @brief Check if expression has "i" sign */
    readonly Boolean ignoreCase;

    /*! @brief Check if expression has "m" sign to match in multiline mode. In this mode, if string to match contains new lien characters, ^ and $ will also match line start and end */
    readonly Boolean multiline;
};
