/*! @brief RTCDataChannel interface defines a bidirectional data channel */
interface RTCDataChannel : EventEmitter
{
    /*! @brief Send binary data, this method is used to send data to the remote end

     @param data Binary data to send
    */
    send(Buffer data);

    /*! @brief Send text data, this method is used to send data to the remote end

     @param data Text data to send
    */
    send(String data);

    /*! @brief Close the channel, this method is used to close the channel */
    close();

    /*! @brief Return the ID number that uniquely identifies the RTCDataChannel */
    readonly Integer id;

    /*! @brief Return a string containing the name describing the data channel */
    readonly String label;

    /*! @brief Return a string containing the name of the subprotocol being used */
    readonly String protocol;

    /*! @brief Return the number of bytes of data currently queued to be sent over the data channel */
    readonly Number bufferedAmount;

    /*! @brief Channel open event, triggered when the channel opens */
    event open();

    /*! @brief Channel message event, triggered when a message is received */
    event message();

    /*! @brief Channel close event, triggered when the channel closes */
    event close();

    /*! @brief Channel error event, triggered when an error occurs on the channel */
    event error();

    /*! @brief Channel buffered amount low event, triggered when the channel buffer is low */
    event bufferedamountlow();
};