/*! @brief WebRTC ICE candidate parameter object */
interface RTCIceCandidate : object
{
    /*! @brief Constructor

     description initialization parameters, supports the following fields:
        - candidate: candidate string
        - sdpMid: media stream identifier

      @param description Initialization parameters
    */
    RTCIceCandidate(Object description = {});

    /*! @brief Return candidate string */
    readonly String candidate;

    /*! @brief Return media stream identifier */
    readonly String sdpMid;

    /*! @brief Return priority */
    readonly Integer priority;

    /*! @brief Return transport protocol */
    readonly String transport;

    /*! @brief Return address */
    readonly String address;

    /*! @brief Return port */
    readonly Integer port;

    /*! @brief Return type */
    readonly String type;
};