/*! @brief Stream object interface that can move the current pointer */
interface SeekableStream : Stream
{
    /*! @brief Move the current file operation position
      @param offset Specify the new position
      @param whence Specify the position base, allowed values are: SEEK_SET, SEEK_CUR, SEEK_END
     */
    seek(Long offset, Integer whence = fs.SEEK_SET);

    /*! @brief Query the current position of the stream
     @return Return the current position of the stream
     */
    Long tell();

    /*! @brief Move the current position to the beginning of the stream */
    rewind();

    /*! @brief Query the stream size
     @return Return the stream size
     */
    Long size();

    /*! @brief Read all remaining data from the stream
     @return Return the data read from the stream, return null if no data is readable or the connection is interrupted
     */
    Buffer readAll() async;

    /*! @brief Modify the file size, if the new size is smaller than the original size, the file is truncated
      @param bytes New file size
     */
    truncate(Long bytes) async;

    /*! @brief Query if the file has reached the end
     @return Return True for end
     */
    Boolean eof();

    /*! @brief Query the basic information of the current file
     @return Return Stat object describing file information
     */
    Stat stat() async;
};