/*! @brief Fiber semaphore object

 The semaphore object manages an internal counter, which decreases by one after calling acquire or wait, and increases by one after calling release or post.
 The counter will not decrease to negative, because acquire and wait will sleep the current fiber when the value is 0, until other fibers increase the counter's value through release or post.

 Semaphores are commonly used to limit concurrent resource usage and producer/consumer pattern applications.

 Taking database requests as an example, limiting resource concurrent usage:
 ```JavaScript
 var maxconnections = 5;
 var l = new coroutine.Semaphore(maxconnections);

 ......

 l.acquire();
 var conn = connectdb()
 .....
 conn.close();
 l.release();
 ```

 Producer/consumer pattern usually cooperates semaphore with queue. Producer adds data to the queue and posts a signal, consumer first waits for the signal, after getting the signal, goes to the queue to fetch data.

 */
interface Semaphore : Lock
{
    /*! @brief Semaphore constructor
     @param value Initial value of the counter
     */
    Semaphore(Integer value = 1);

    /*! @brief Wait for a semaphore
     @param timeout Specify timeout time in milliseconds, default is -1, meaning never timeout.
     @return Return true if acquired successfully, false if timeout
    */
    Boolean wait(Integer timeout = -1) async;

    /*! @brief Release a semaphore, equivalent to release() */
    post();

    /*! @brief Try to acquire a semaphore, if cannot acquire, return immediately and return false, equivalent to acquire(false)
     @return Return true if acquired successfully, false if timeout
     */
    Boolean trywait();
};