/*! @brief System service management object */
interface Service : EventEmitter
{
    /*! @brief System service management object constructor
     @param name Service name
     @param worker Service running function
     @param event Service event handling
     */
    Service(String name, Function worker, Object event = {});

    /*! @brief Start running the service entity */
    run() async;

    /*! @brief Query and set service name */
    String name;

    /*! @brief Query and bind service stop event, equivalent to on("stop", func); */
    event stop();

    /*! @brief Query and bind service pause event, equivalent to on("pause", func); */
    event pause();

    /*! @brief Query and bind service resume event, equivalent to on("continue", func); */
    event continue();

    /*! @brief Install service to system
     @param name Service name
     @param cmd Service command line
     @param displayName Service display name
     @param description Service description
     */
    static install(String name, String cmd, String displayName = "", String description = "");

    /*! @brief Uninstall service from system
     @param name Service name
     */
    static remove(String name);

    /*! @brief Start service
     @param name Service name
     */
    static start(String name);

    /*! @brief Stop service
     @param name Service name
     */
    static stop(String name);

    /*! @brief Restart service
     @param name Service name
     */
    static restart(String name);

    /*! @brief Check if service is installed
     @param name Service name
     @return Return True if service is installed
     */
    static Boolean isInstalled(String name);

    /*! @brief Check if service is running
     @param name Service name
     @return Return True if service is running
     */
    static Boolean isRunning(String name);
};