
/*! @brief Smtp object

 */
interface Smtp : object
{
    /*! @brief Smtp constructor */
    Smtp();

    /*! @brief Connect to given server
     @param host Server address or hostname
     @param port Server port
     @param family Address family, defualt is AF_INE, ipv4
     */
    connect(String host, Integer port, Integer family = net.AF_INET) async;

    /*! @brief Send command and get response, throw error when server returns error
     @param cmd Command name
     @param arg Command arguments
     @return Return server response when succeed
     */
    String command(String cmd, String arg) async;

    /*! @brief Send HELO command, throw error when server returns error
     @param hostname Hostname, defualt is localhost
     */
    hello(String hostname = "localhost") async;

    /*! @brief Login with username and password, throw error when server returns error
     @param username Username
     @param password Password
     */
    login(String username, String password) async;

    /*! @brief Indicates sender's e-mail address, throw error when server returns error
     @param address Sender's e-mail address
     */
    from(String address) async;

    /*! @brief Indicates receiver's e-mail address, throw error when server returns error
     @param address Receiver's e-mail address
     */
    to(String address) async;

    /*! @brief Send text to receiver, throw error when server returns error
     @param txt Content to send
     */
    data(String txt) async;

    /*! @brief Quit and close connection, throw error when server returns error */
    quit() async;

    /*! @brief Get Socket of current Smtp connection */
    readonly Socket socket;
};
