/*! @brief Basic file information object

  Stat object is queried through fs.stat, FileStream.stat, fs.readdir, cannot be created independently
 */
interface Stat : object
{
    /*! @brief File name */
    readonly String name;

    /*! @brief Device ID containing the file */
    readonly Integer dev;

    /*! @brief Number of Inodes in the file */
    readonly Integer ino;

    /*! @brief File permissions, not supported on Windows */
    readonly Integer mode;

    /*! @brief Number of hard links associated with the file */
    readonly Integer nlink;

    /*! @brief ID of the file owner */
    readonly Integer uid;

    /*! @brief ID of the group the file belongs to */
    readonly Integer gid;

    /*! @brief For special types of files, contains the device ID of the file */
    readonly Integer rdev;

    /*! @brief File size */
    readonly Number size;

    /*! @brief File system block size in I/O operations */
    readonly Integer blksize;

    /*! @brief Number of blocks allocated to the file */
    readonly Integer blocks;

    /*! @brief File last modification time */
    readonly Date mtime;

    /*! @brief File last modification time (ms) */
    readonly Number mtimeMs;

    /*! @brief File last modification time (ns), only valid when bigint is true */
    readonly Long mtimeNs;

    /*! @brief File last access time */
    readonly Date atime;

    /*! @brief File last access time (ms) */
    readonly Number atimeMs;

    /*! @brief File last access time (ns), only valid when bigint is true */
    readonly Long atimeNs;

    /*! @brief File status change time */
    readonly Date ctime;

    /*! @brief File status change time (ms) */
    readonly Number ctimeMs;

    /*! @brief File status change time (ns), only valid when bigint is true */
    readonly Long ctimeNs;

    /*! @brief File birth time */
    readonly Date birthtime;

    /*! @brief File birth time (ms) */
    readonly Number birthtimeMs;

    /*! @brief File birth time (ns), only valid when bigint is true */
    readonly Long birthtimeNs;

    /*! @brief Query if the file has write permission
     @return true if has write permission
     */
    Boolean isWritable();

    /*! @brief Query if the file has read permission
     @return true if has read permission
     */
    Boolean isReadable();

    /*! @brief Query if the file has execute permission
     @return true if has execute permission
     */
    Boolean isExecutable();

    /*! @brief Query if the file is hidden
     @return true if hidden
     */
    Boolean isHidden();

    /*! @brief Query if Stat describes a block device
     @return true if describes a block device
     */
    Boolean isBlockDevice();

    /*! @brief Query if Stat describes a character device
     @return true if describes a character device
     */
    Boolean isCharacterDevice();

    /*! @brief Query if the file is a directory
     @return true if directory
     */
    Boolean isDirectory();

    /*! @brief Query if Stat describes a FIFO pipe
     @return true if describes a FIFO pipe
     */
    Boolean isFIFO();

    /*! @brief Query if the file is a file
     @return true if file
     */
    Boolean isFile();

    /*! @brief Query if the file is a symbolic link
     @return true if symbolic link
     */
    Boolean isSymbolicLink();

    /*! @brief Query if the file is a memory file
     @return true if memory file
     */
    Boolean isMemory();

    /*! @brief Query if the file is a Socket
     @return true if Socket
     */
    Boolean isSocket();
};