/*! @brief Stream decoder object
 */
interface StringDecoder : object
{
    /*! @brief Decoder constructor
     @param encoding Decoding encoding. Default 'utf8'.
     */
    StringDecoder(String encoding = "utf8");

    /*! @brief Return the internally buffered buffer as characters. Incomplete UTF-8 and UTF-16 bytes will be attempted to be completed.
     @return The decoded string.
     */
    String end();

    /*! @brief Return the internally buffered buffer as characters. Incomplete UTF-8 and UTF-16 bytes will be attempted to be completed.
     @param buf The Buffer to decode. Before executing end, write will be called first to write the buffer.
     @return The decoded string.
     */
    String end(Buffer buf);

    /*! @brief Return a decoded string, ensuring that any incomplete trailing characters are omitted from this return and stored internally for the next write or end method.
     @param buf The Buffer to decode.
     @return The decoded string.
     */
    String write(Buffer buf);

    /*! @brief For internal use.
     @param buf The Buffer to decode.
     @param offset Decoding offset
     @return The decoded string.
     */
    String text(Buffer buf, Integer offset);

    /*! @brief For internal use.
     @param buf A Buffer containing the bytes to decode.
     @return The decoded string.
     */
    String fillLast(Buffer buf);

    /*! @brief For internal use. */
    Integer lastNeed;

    /*! @brief For internal use. */
    Integer lastTotal;

    /*! @brief For internal use. */
    Buffer lastChar;

    /*! @brief Decoding encoding. For internal use. */
    String encoding;
};