/*! @brief The timers module is a built-in module that provides some time-related functions and objects, including setTimeout(), setInterval(), clearInterval(), clearTimeout(), etc.

The setInterval() function calls the function after the specified time interval, returns the timer object.

```JavaScript
var timers = require('timers');
function callback() {
    console.log('Hello, World!');
}
var intervalId = timers.setInterval(callback, 1000);
```

The setTimeout() function calls the function after the specified time, returns the timer object.

```JavaScript
var timers = require('timers');
function callback() {
    console.log('Hello, World!');
}
var timeoutId = timers.setTimeout(callback, 1000);
```

The clearTimeout() function is used to cancel a timer set by the setTimeout() method. What needs to be provided is the timer identifier value returned in setTimeout().

```JavaScript
var timers = require('timers');
function callback() {
    console.log('Hello, World!');
}
var timeoutId = timers.setTimeout(callback, 1000);
timers.clearTimeout(timeoutId);
```

The clearInterval() function is used to cancel a timer set by the setInterval() method. What needs to be provided is the timer identifier value returned in setInterval().

```JavaScript
var timers = require('timers');
function callback() {
    console.log('Hello, World!');
}
var intervalId = timers.setInterval(callback, 1000);
timers.clearInterval(intervalId);
```

The setImmediate() function is used to call the function immediately at the next idle time, returns the timer object.

```JavaScript
var timers = require('timers');
function callback() {
    console.log('Hello, World!');
}
var immediateId = timers.setImmediate(callback);
```

The above are examples of commonly used functions and objects provided by the timers module. By using these functions and objects, it is convenient to implement delayed execution tasks or scheduled task execution in applications.
 */
module timers
{
    /*! @brief Call the function after the specified time
    @param callback Specify callback function
    @param timeout Specify the delay time in milliseconds. If it exceeds 2^31, execute immediately.
    @param args Additional parameters, passed into the specified callback, optional.
    @return Return timer object
    */
    static Timer setTimeout(Function callback, Number timeout = 1, ...args);

    /*! @brief Clear the specified timer
     @param t Specify the timer to clear
    */
    static clearTimeout(Value t);

    /*! @brief Call the function after each specified time interval
     @param callback Specify callback function
     @param timeout Specify the interval time in milliseconds. If it exceeds 2^31, execute immediately.
     @param args Additional parameters, passed into the specified callback, optional.
     @return Return timer object
    */
    static Timer setInterval(Function callback, Number timeout, ...args);

    /*! @brief Clear the specified timer
     @param t Specify the timer to clear
    */
    static clearInterval(Value t);

    /*! @brief Call the function after each specified time interval, this is a high-precision timer that will actively interrupt the running JavaScript script to execute the timer
     Since the setHrInterval timer will interrupt the running code to execute the callback, do not modify data that may affect other modules in the callback function, or call any api functions marked as async in the callback, otherwise unpredictable results will occur. For example:
     ```JavaScript
        var timers = require('timers');

        var cnt = 0;
        timers.setHrInterval(() => {
            cnt++;
        }, 100);

        while (cnt < 10);

        console.error("===============================> done");
     ```
     In this code, the loop in line 8 will not end because cnt changes, because JavaScript optimizes the code and determines that cnt will not change during this loop.
     @param callback Specify callback function
     @param timeout Specify the interval time in milliseconds. If it exceeds 2^31, execute immediately.
     @param args Additional parameters, passed into the specified callback, optional.
     @return Return timer object
    */
    static Timer setHrInterval(Function callback, Number timeout, ...args);

    /*! @brief Clear the specified timer
     @param t Specify the timer to clear
    */
    static clearHrInterval(Value t);

    /*! @brief Execute the callback function immediately at the next idle time
     @param callback Specify callback function
     @param args Additional parameters, passed into the specified callback, optional.
     @return Return timer object
    */
    static Timer setImmediate(Function callback, ...args);

    /*! @brief Clear the specified timer
     @param t Specify the timer to clear
    */
    static clearImmediate(Value t);

    /*! @brief Call the given function and interrupt the function run when the timeout expires
     @param func Specify the function to run
     @param timeout Specify timeout time
     @param args Additional parameters, passed into the specified callback, optional.
     @return Return the running result of func
    */
    static Value call(Function func, Number timeout, ...args);
};