/*! @brief The util module provides utility functions for data type judgment, object property copying, template string parsing, event handling, etc.

Here is the specific introduction and example:

1. Judging data types - `util.is[type]`
This module provides methods such as `isDate`, `isRegExp`, `isError` to judge the data type of the incoming parameters, for example:

```JavaScript
var util = require('util');
console.log(util.isDate(new Date()));
console.log(util.isRegExp(/some regexp/));
```
2. Object property copying - `util.inherits()`
This method can choose to inherit one constructor from another, thus implementing prototype inheritance.

```JavaScript
var util = require('util');
function Animal() {
  this.name = 'Animal';
  this.sleep = function () {
    console.log(this.name + '正在睡觉！');
  }
}
Animal.prototype.eat = function (food) {
  console.log(this.name + '正在吃：' + food);
};
function Cat() {
  this.name = 'cat';
}
util.inherits(Cat, Animal);
```

Using the `Cat` constructor inherited the instance properties and prototype properties of `Animal`, print the properties and methods of the instance of `Cat`

```JavaScript
var cat = new Cat();
console.log(cat.name); 
console.log(cat.eat('fish')); 
console.log(cat.sleep());
```

3. util.format() formatted output template
```JavaScript
const util = require('util');
const str1 = util.format('%s:%s', 'foo');
const str2 = util.format('%s:%s', 'foo', 'bar', 'baz');
console.log(str1) // => 'foo:%s'
console.log(str2) // => 'foo:bar baz'
```

The above are some commonly used methods of the `util` module, which can often be used to simplify the actual development process.
*/
module util
{
    /*! @brief TextDecoder decoding object, see TextDecoder object.*/
    static TextDecoder;

    /*! @brief TextEncoder encoding object, see TextEncoder object.*/
    static TextEncoder;

    /*! @brief types module provides utility functions for data type judgment.*/
    static types;

    /*! @brief colors module provides a set of color constants for setting console output colors.*/
    static colors;

    /*! @brief Format variables according to the specified format

     @param fmt Format string
     @param args Optional parameter list
     @return Return the formatted string
     */
    static String format(String fmt, ...args);

    /*! @brief Format variables

     @param args Optional parameter list
     @return Return the formatted string
     */
    static String format(...args);

    /*! @brief Inherit prototype functions from one constructor to another. The prototype of the constructor will be set to a new object created from the superclass (superConstructor).

     @param constructor Initial constructor
     @param superConstructor Inherited superclass
     */
    static inherits(Value constructor, Value superConstructor);

    /*! @brief The function returns the string representation of obj, mainly used for debugging. Additional options can be used to change certain aspects of the formatted string.

     Supports the following parameters:
     ```JavaScript
     {
         "colors": false, // specify if output should be colorized, defaults to false
         "depth": 2, // specify the max depth of the output, defaults to 2
         "table": false, // specify if output should be a table, defaults to false
         "encode_string": true, // specify if string should be encoded, defaults to true
         "maxArrayLength": 100, // specify max number of array elements to show, set to 0 or negative to show no elements, defaults to 100
         "maxStringLength": 10000, // specify max string length to output, set to 0 or negative to show no strings, defaults to 10000
         "fields": [], // specify the fields to be displayed, defaults to all
     }
     ```
     @param obj Specify the object to process
     @param options Specify format control options
     @return Return the formatted string
     */
    static String inspect(Value obj, Object options = {});

    /*! @brief Apply ANSI color/style formatting to a text string (Node.js v20.12+ compatible)

     When color output is not supported (e.g. non-TTY, NO_COLOR set), the text is returned unmodified.

     Supported formats: bold, italic, underline, strikethrough, hidden,
     black, red, green, yellow, blue, magenta, cyan, white,
     bgBlack, bgRed, bgGreen, bgYellow, bgBlue, bgMagenta, bgCyan, bgWhite,
     gray/grey, blackBright, redBright, greenBright, yellowBright, blueBright,
     magentaBright, cyanBright, whiteBright

     @param format Array of format names to apply
     @param text Text to style
     @return Return the styled string
     */
    static String styleText(String format[], String text);

    /*! @brief Apply ANSI color/style formatting to a text string (Node.js v20.12+ compatible)

     @param format Format name to apply
     @param text Text to style
     @return Return the styled string
     */
    static String styleText(String format, String text);

    /*! @brief Create a ConsoleObject object that conditionally outputs debug information based on the NODE_DEBUG environment variable
     
     @param section Specified debug area
     @return Return a ConsoleObject object
     */
    static ConsoleObject debuglog(String section);

    /*! @brief Create a ConsoleObject object that conditionally outputs debug information based on the NODE_DEBUG environment variable

     @param section Specified debug area
     @param fn Callback called when the log function is called for the first time, its function parameter is a more optimized log function
     @return Return a ConsoleObject object
     */
    static ConsoleObject debuglog(String section, Function fn);

    /*! @brief Create a ConsoleObject object that conditionally outputs debug information based on the NODE_DEBUG environment variable. It is an alias for debuglog
     
     @param section Specified debug area
     @return Return a ConsoleObject object
     */
    static ConsoleObject debug(String section);

    /*! @brief Create a ConsoleObject object that conditionally outputs debug information based on the NODE_DEBUG environment variable. It is an alias for debuglog

     @param section Specified debug area
     @param fn Callback called when the log function is called for the first time, its function parameter is a more optimized log function
     @return Return a ConsoleObject object
     */
    static ConsoleObject debug(String section, Function fn);

    /*! @brief Wrap the given function, this function is only for compatibility and does not output warnings

     @param fn Given function to wrap
     @param msg Given warning message
     @param code Given warning code
     @return If wrapping result
     */
    static Function deprecate(Function fn, String msg, String code = "");

    /*! @brief Detect whether the given variable contains no value (no enumerable properties)

     @param v Given variable to detect
     @return Return True if empty
     */
    static Boolean isEmpty(Value v);

    /*! @brief Detect whether the given variable is an array

     @param v Given variable to detect
     @return Return True if it is an array
     */
    static Boolean isArray(Value v);

    /*! @brief Detect whether the given variable is Boolean

     @param v Given variable to detect
     @return Return True if it is Boolean
     */
    static Boolean isBoolean(Value v);

    /*! @brief Detect whether the given variable is Null

     @param v Given variable to detect
     @return Return True if it is Null
     */
    static Boolean isNull(Value v);

    /*! @brief Detect whether the given variable is Null or Undefined

     @param v Given variable to detect
     @return Return True if it is Null or Undefined
     */
    static Boolean isNullOrUndefined(Value v);

    /*! @brief Detect whether the given variable is a number

     @param v Given variable to detect
     @return Return True if it is a number
     */
    static Boolean isNumber(Value v);

    /*! @brief Detect whether the given variable is BigInt

     @param v Given variable to detect
     @return Return True if it is a number
     */
    static Boolean isBigInt(Value v);

    /*! @brief Detect whether the given variable is a string

     @param v Given variable to detect
     @return Return True if it is a string
     */
    static Boolean isString(Value v);

    /*! @brief Detect whether the given variable is Undefined

     @param v Given variable to detect
     @return Return True if it is Undefined
     */
    static Boolean isUndefined(Value v);

    /*! @brief Detect whether the given variable is a regular expression object

     @param v Given variable to detect
     @return Return True if it is a regular expression object
     */
    static Boolean isRegExp(Value v);

    /*! @brief Detect whether the given variable is an object

     @param v Given variable to detect
     @return Return True if it is an object
     */
    static Boolean isObject(Value v);

    /*! @brief Detect whether the given variable is a date object

     @param v Given variable to detect
     @return Return True if it is a date object
     */
    static Boolean isDate(Value v);

    /*! @brief Detect whether the given variable is an error object

     @param v Given variable to detect
     @return Return True if it is an error object
     */
    static Boolean isNativeError(Value v);

    /*! @brief Detect whether the given variable is a primitive type

     @param v Given variable to detect
     @return Return True if it is a primitive type
     */
    static Boolean isPrimitive(Value v);

    /*! @brief Detect whether the given variable is Symbol type

     @param v Given variable to detect
     @return Return True if it is Symbol type
     */
    static Boolean isSymbol(Value v);

    /*! @brief Detect whether the given variable is DataView type

     @param v Given variable to detect
     @return Return True if it is DataView type
     */
    static Boolean isDataView(Value v);

    /*! @brief Detect whether the given variable is External type

     @param v Given variable to detect
     @return Return True if it is External type
     */
    static Boolean isExternal(Value v);

    /*! @brief Detect whether the given variable is Map type

     @param v Given variable to detect
     @return Return True if it is Map type
     */
    static Boolean isMap(Value v);

    /*! @brief Detect whether the given variable is MapIterator type

     @param v Given variable to detect
     @return Return True if it is MapIterator type
     */
    static Boolean isMapIterator(Value v);

    /*! @brief Detect whether the given variable is Promise type

     @param v Given variable to detect
     @return Return True if it is Promise type
     */
    static Boolean isPromise(Value v);

    /*! @brief Detect whether the given variable is AsyncFunction type

     @param v Given variable to detect
     @return Return True if it is AsyncFunction type
     */
    static Boolean isAsyncFunction(Value v);

    /*! @brief Detect whether the given variable is Set type

     @param v Given variable to detect
     @return Return True if it is Set type
     */
    static Boolean isSet(Value v);

    /*! @brief Detect whether the given variable is SetIterator type

     @param v Given variable to detect
     @return Return True if it is SetIterator type
     */
    static Boolean isSetIterator(Value v);

    /*! @brief Detect whether the given variable is TypedArray type

     @param v Given variable to detect
     @return Return True if it is TypedArray type
     */
    static Boolean isTypedArray(Value v);

    /*! @brief Detect whether the given variable is Float32Array type

     @param v Given variable to detect
     @return Return True if it is Float32Array type
     */
    static Boolean isFloat32Array(Value v);

    /*! @brief Detect whether the given variable is Float64Array type

     @param v Given variable to detect
     @return Return True if it is Float64Array type
     */
    static Boolean isFloat64Array(Value v);

    /*! @brief Detect whether the given variable is Int8Array type

     @param v Given variable to detect
     @return Return True if it is Int8Array type
     */
    static Boolean isInt8Array(Value v);

    /*! @brief Detect whether the given variable is Int16Array type

     @param v Given variable to detect
     @return Return True if it is Int16Array type
     */
    static Boolean isInt16Array(Value v);

    /*! @brief Detect whether the given variable is Int32Array type

     @param v Given variable to detect
     @return Return True if it is Int32Array type
     */
    static Boolean isInt32Array(Value v);

    /*! @brief Detect whether the given variable is Uint8Array type

     @param v Given variable to detect
     @return Return True if it is Uint8Array type
     */
    static Boolean isUint8Array(Value v);

    /*! @brief Detect whether the given variable is Uint8ClampedArray type

     @param v Given variable to detect
     @return Return True if it is Uint8ClampedArray type
     */
    static Boolean isUint8ClampedArray(Value v);

    /*! @brief Detect whether the given variable is Uint16Array type

     @param v Given variable to detect
     @return Return True if it is Uint16Array type
     */
    static Boolean isUint16Array(Value v);

    /*! @brief Detect whether the given variable is Uint32Array type

     @param v Given variable to detect
     @return Return True if it is Uint32Array type
     */
    static Boolean isUint32Array(Value v);

    /*! @brief Detect whether the given variable is a function object

     @param v Given variable to detect
     @return Return True if it is a function object
     */
    static Boolean isFunction(Value v);

    /*! @brief Detect whether the given variable is a Buffer object

     @param v Given variable to detect
     @return Return True if it is a Buffer object
     */
    static Boolean isBuffer(Value v);

    /*! @brief Detect whether the given variable is a BigInt object, not a primitive type

     @param v Given variable to detect
     @return Return True if it is a BigInt object
     */
    static Boolean isBigIntObject(Value v);

    /*! @brief Detect whether the given variable is a Boolean object, not a primitive type

     @param v Given variable to detect
     @return Return True if it is a Boolean object
     */
    static Boolean isBooleanObject(Value v);

    /*! @brief Detect whether the given variable is a Number object, not a primitive type

     @param v Given variable to detect
     @return Return True if it is a Number object
     */
    static Boolean isNumberObject(Value v);

    /*! @brief Detect whether the given variable is a String object, not a primitive type

     @param v Given variable to detect
     @return Return True if it is a String object
     */
    static Boolean isStringObject(Value v);

    /*! @brief Detect whether the given variable is a Symbol object, not a primitive type

     @param v Given variable to detect
     @return Return True if it is a Symbol object
     */
    static Boolean isSymbolObject(Value v);

    /*! @brief Detect whether the given variable is WeakMap type

     @param v Given variable to detect
     @return Return True if it is WeakMap type
     */
    static Boolean isWeakMap(Value v);

    /*! @brief Detect whether the given variable is WeakSet type

     @param v Given variable to detect
     @return Return True if it is WeakSet type
     */
    static Boolean isWeakSet(Value v);

    /*! @brief Detect whether the given variable is ArrayBuffer type

     @param v Given variable to detect
     @return Return True if it is ArrayBuffer type
     */
    static Boolean isArrayBuffer(Value v);

    /*! @brief Detect whether the given variable is ArrayBufferView type

     @param v Given variable to detect
     @return Return True if it is ArrayBufferView type
     */
    static Boolean isArrayBufferView(Value v);

    /*! @brief Detect whether the given variable is BigInt64Array type

     @param v Given variable to detect
     @return Return True if it is BigInt64Array type
     */
    static Boolean isBigInt64Array(Value v);

    /*! @brief Detect whether the given variable is BigUint64Array type

     @param v Given variable to detect
     @return Return True if it is BigUint64Array type
     */
    static Boolean isBigUint64Array(Value v);

    /*! @brief Detect whether the given variable is Float16Array type

     @param v Given variable to detect
     @return Return True if it is Float16Array type
     */
    static Boolean isFloat16Array(Value v);

    /*! @brief Detect whether the given variable is ArrayBuffer or SharedArrayBuffer type

     @param v Given variable to detect
     @return Return True if it is ArrayBuffer or SharedArrayBuffer type
     */
    static Boolean isAnyArrayBuffer(Value v);

    /*! @brief Detect whether the given variable is SharedArrayBuffer type

     @param v Given variable to detect
     @return Return True if it is SharedArrayBuffer type
     */
    static Boolean isSharedArrayBuffer(Value v);

    /*! @brief Detect whether the given variable is an arguments object

     @param v Given variable to detect
     @return Return True if it is an arguments object
     */
    static Boolean isArgumentsObject(Value v);

    /*! @brief Detect whether the given variable is a boxed primitive object (e.g. new Boolean(), new String())

     @param v Given variable to detect
     @return Return True if it is a boxed primitive object
     */
    static Boolean isBoxedPrimitive(Value v);

    /*! @brief Detect whether the given variable is a GeneratorFunction

     @param v Given variable to detect
     @return Return True if it is a GeneratorFunction
     */
    static Boolean isGeneratorFunction(Value v);

    /*! @brief Detect whether the given variable is a Generator object

     @param v Given variable to detect
     @return Return True if it is a Generator object
     */
    static Boolean isGeneratorObject(Value v);

    /*! @brief Detect whether the given variable is a Proxy instance

     @param v Given variable to detect
     @return Return True if it is a Proxy instance
     */
    static Boolean isProxy(Value v);

    /*! @brief Detect whether the given variable is a Module Namespace object

     @param v Given variable to detect
     @return Return True if it is a Module Namespace object
     */
    static Boolean isModuleNamespaceObject(Value v);

    /*! @brief Detect whether the given variable is a CryptoKey type

     @param v Given variable to detect
     @return Return True if it is a CryptoKey type
     */
    static Boolean isCryptoKey(Value v);

    /*! @brief Detect whether the given variable is a KeyObject type

     @param v Given variable to detect
     @return Return True if it is a KeyObject type
     */
    static Boolean isKeyObject(Value v);

    /*! @brief Strip TypeScript type annotations from code

     This function removes TypeScript-specific syntax from the provided code string, converting it to plain JavaScript. It handles various TypeScript features including:

     - Type annotations (e.g., `const x: string = "hello";` becomes `const x         = "hello";`)
     - Interface declarations
     - Class property type annotations
     - Generic type parameters
     - Enum declarations
     - Namespace declarations (converted to IIFE)
     - Constructor parameter properties (e.g., `constructor(public x: string)`)
     - `import = require()` syntax
     - `export =` syntax
     - Angle bracket type assertions (e.g., `<T>expr`, use `as` syntax instead)

     Example:
     ```JavaScript
     var util = require('util');
     var ts = 'const x: string = "hello";';
     var js = util.stripTypeScript(ts);
     console.log(js); // 'const x         = "hello";'
     ```

     @param code TypeScript source code
     @return Return the converted JavaScript code
     */
    static String stripTypeScript(String code);

    /*! @brief Get the visual width of a string, considering full-width characters, emoji, and ANSI escape sequences
     Characters with East Asian Width property of Fullwidth (F) or Wide (W) count as 2, most others count as 1.
     Control characters and combining marks count as 0. ANSI escape sequences are skipped.

     @param str The string to measure
     @return Return the visual width of the string
     */
    static Integer getStringWidth(String str);

    /*! @brief Remove ANSI escape sequences (VT control characters) from a string

     @param str The string to strip
     @return Return the string with ANSI escape sequences removed
     */
    static String stripVTControlCharacters(String str);
};