
/*! @brief Safe SandBox module, to isolate runtime based on safety level.

 By establishing a safe SandBox, you can limit the accessible resources when the script runs, and isolate different script execution environment, also can be customized for different environments base module to ensure the safety of the overall operating environment.

 Following example demonstrates a sandbox which is only allowed for accessing assert module, and add a and b as customized modules.
 @code
 var vm = require('vm');
 var sbox = new vm.SandBox({
   a: 100,
   b: 200,
   assert: require('assert')
 });

 var mod_in_sbox = sbox.require('./path/to/mod');
 @endcode
 */
module vm
{
    /*! @brief Create a SandBox object, see SandBox */
    static SandBox new SandBox();
};
