/*! @brief WebSocket is a full-duplex communication protocol based on TCP protocol, establishing an uninterrupted connection between browser and server, enabling real-time bidirectional data transmission, and supporting arbitrary format data transmission. In fibjs, the WebSocket support module provides corresponding API interfaces, enabling development of WebSocket server and client

The WebSocket support module is just an implementation of the WebSocket protocol, requiring HTTP protocol to work. On the server side, HTTP requests can be converted to WebSocket connections through the upgrade function, while on the client side, the server address to connect to needs to be specified through the WebSocket protocol URL.

Start WebSocket server example:
```JavaScript
var http = require('http');

var svr = new http.Server(80, {
    '/ws': WebSocket.upgrade({
        protocols: ['json', 'text']
    }, conn => {
        conn.onmessage = e => {
            conn.send('fibjs:' + e.data);
        };
    })
});
svr.start();
```
Example of establishing connection with the above server in client:
```JavaScript
var conn = new WebSocket("ws://127.0.0.1/ws", ['json', 'text']);
// emit open event
conn.onopen = () => {
    console.log("websocket connected with protocol:", conn.protocol);
    conn.send("hi");
};
// emit close event
conn.onmessage = evt => {
    console.log("websocket receive: " + evt.data);
};
```
 */
interface WebSocket : EventEmitter
{
    /*! @brief WebSocket constructor
     @param url specify the server to connect to
     @param protocol specify the handshake protocol, default is ""
     @param origin specify the simulated origin during handshake, default is ""
    */
    WebSocket(String url, String protocol = "", String origin = "");

    /*! @brief WebSocket constructor
     @param url specify the server to connect to
     @param protocols specify the candidate sub-protocol list during handshake, default is []
     @param origin specify the simulated origin during handshake, default is ""
    */
    WebSocket(String url, String protocols[], String origin = "");

    /*! @brief WebSocket constructor
     opts contains additional options for the request, supported content as follows:
     ```JavaScript
     {
         "protocol": "", // specify the sub-protocol, default is ""
         "protocols": [], // specify the candidate sub-protocol list, takes precedence over protocol when provided
         "origin": "", // specify the origin, default is ""
         "perMessageDeflate": false, // specify whether to enable permessage-deflate, default is false
         "maxPayload": 67108864, // specify the max payload size, default is 64MB
         "httpClient": hc, // specify the http client, default is null, use the global http client
         "headers": // specify the http headers, default is {}
     }
     ```
     @param url specify the server to connect to
     @param opts connection options, default is {}
    */
    WebSocket(String url, Object opts);

    /*! @brief Specify WebSocket message type 0, representing a continuation frame */
    const CONTINUE = 0;

    /*! @brief Specify WebSocket message type 1, representing a text frame */
    const TEXT = 1;

    /*! @brief Specify WebSocket message type 2, representing a binary frame */
    const BINARY = 2;

    /*! @brief Specify WebSocket message type 8, connection close */
    const CLOSE = 8;

    /*! @brief Specify WebSocket message type 9, representing a ping frame */
    const PING = 9;

    /*! @brief Specify WebSocket message type 10, representing a pong frame */
    const PONG = 10;

    /*! @brief Specify WebSocket state, indicating connecting */
    const CONNECTING = 0;

    /*! @brief Specify WebSocket state, indicating open */
    const OPEN = 1;

    /*! @brief Specify WebSocket state, indicating closing after sending CLOSE message */
    const CLOSING = 2;

    /*! @brief Specify WebSocket state, indicating closed */
    const CLOSED = 3;

    /*! @brief Query the server currently connected by the object */
    readonly String url;

    /*! @brief Query the protocol when the object is connected */
    readonly String protocol;

    /*! @brief Query the origin of the object's connection */
    readonly String origin;

    /*! @brief Query the connection status of the current object, see ws */
    readonly Integer readyState;

    /*! @brief Close the current connection, this operation sends CLOSE packet to the other party and waits for response
     @param code specify the close code, allowed values are 3000-4999 or 1000, default is 1000
     @param reason specify the close reason, default is ""
    */
    close(Integer code = 1000, String reason = "");

    /*! @brief Send a piece of text to the other party
     @param data specify the text to send
    */
    send(String data);

    /*! @brief Send a piece of binary data to the other party
     @param data specify the binary data to send
    */
    send(Buffer data);

    /*! @brief Query and bind connection success event, equivalent to on("open", func); */
    event open();

    /*! @brief Query and bind event of receiving message from the other party, equivalent to on("message", func); */
    event message();

    /*! @brief Query and bind connection close event, equivalent to on("close", func); */
    event close();

    /*! @brief Query and bind error occurrence event, equivalent to on("error", func); */
    event error();

    /*! @brief Keep fibjs process from exiting, prevent fibjs process from exiting during object binding
     @return return current object
    */
    WebSocket ref();

    /*! @brief Allow fibjs process to exit, allow fibjs process to exit during object binding
     @return return current object
    */
    WebSocket unref();

    /*! @brief WebSocketMessage class for creating WebSocket protocol messages, see WebSocketMessage object */
    static Message = WebSocketMessage;

    /*! @brief Create a WebSocket protocol handler, receive upgrade request from http and handshake, generate WebSocket object
     @param accept Connection success handler function, callback will pass two parameters, first is the received WebSocket object, second is the HttpRequest object during handshake
     @return Returns protocol handler, can be connected with HttpServer, Chain, Routing, etc.
     */
    static Handler upgrade(Function accept);

    /*! @brief Create a WebSocket protocol handler, receive upgrade request from http and handshake, generate WebSocket object
     opts supports `protocol` or `protocols` to select and return `Sec-WebSocket-Protocol`, for example:
     ```JavaScript
     WebSocket.upgrade({
         protocols: ['json', 'text']
     }, conn => {
         console.log(conn.protocol); // selected sub-protocol
     })
     ```
     @param opts Connection options, default is {}
     @param accept Connection success handler function, callback will pass two parameters, first is the received WebSocket object, second is the HttpRequest object during handshake
     @return Returns protocol handler, can be connected with HttpServer, Chain, Routing, etc.
     */
    static Handler upgrade(Object opts, Function accept);
};