/*! @brief WebSocket support module

The WebSocket protocol is a full-duplex communication protocol based on TCP, establishing a persistent connection between browser and server, enabling real-time bidirectional data transmission, and supporting data transmission in any format. In fibjs, the WebSocket support module provides corresponding API interfaces for developing WebSocket server and client.

Usage:
```JavaScript
var ws = require('ws');
```
Create a server:
```JavaScript
var ws = require('ws');
var http = require('http');

var svr = new http.Server(80, {
    '/ws': ws.upgrade((conn, req) => {
        conn.onmessage = e => console.log(e.data);
    })
});
svr.start();
```
In the above code, first load the built-in WebSocket support module of fibjs through the require function, then create an HTTP server instance using the http.Server class, specify the listening port number and HTTP request path, then use the upgrade function under the specified path to upgrade the request to a WebSocket connection. The server will automatically create a WebSocket object for each connection, providing events such as onopen, onmessage, onerror, onclose, and can send data to the client through the send function.

Using WebSocket client:
```JavaScript
var ws = require('ws');

var conn = new ws.Socket('ws://127.0.0.1/ws');
conn.onmessage = e => console.log(e.data);
```
You can complete the client connection by creating a Socket instance and specifying a WebSocket URL. The Socket class provides callback functions such as onmessage, onerror, onclose and the send function, which can send data to the server and receive data sent by the server.

Note that the WebSocket support module is just an implementation of the WebSocket protocol and needs to work on top of the HTTP protocol. On the server side, you can convert HTTP requests to WebSocket connections through the upgrade function, while on the client side, you need to specify the server address to connect to through the WebSocket protocol URL.
*/
module ws
{
    /*! @brief Specify WebSocket message type 0, representing a continuation frame */
    const CONTINUE = 0;

    /*! @brief Specify WebSocket message type 1, representing a text frame */
    const TEXT = 1;

    /*! @brief Specify WebSocket message type 2, representing a binary frame */
    const BINARY = 2;

    /*! @brief Specify WebSocket message type 8, connection close */
    const CLOSE = 8;

    /*! @brief Specify WebSocket message type 9, representing a ping frame */
    const PING = 9;

    /*! @brief Specify WebSocket message type 10, representing a pong frame */
    const PONG = 10;

    /*! @brief Specify WebSocket state, indicating connecting */
    const CONNECTING = 0;

    /*! @brief Specify WebSocket state, indicating open */
    const OPEN = 1;

    /*! @brief Specify WebSocket state, indicating closing after sending CLOSE message */
    const CLOSING = 2;

    /*! @brief Specify WebSocket state, indicating closed */
    const CLOSED = 3;

    /*! @brief Create a WebSocket message object, see WebSocketMessage */
    static WebSocketMessage new Message();

    /*! @brief WebSocket object, see WebSocket */
    static WebSocket new Socket();

    /*! @brief Create a WebSocket protocol handler, receive upgrade request from http and handshake, generate WebSocket object
     ```
     @param accept Connection success handler function, callback will pass two parameters, first is the received WebSocket object, second is the HttpRequest object during handshake
     @return Returns protocol handler, can be connected with HttpServer, Chain, Routing, etc.
     */
    static Handler upgrade(Function accept);

    /*! @brief Create a WebSocket protocol handler, receive upgrade request from http and handshake, generate WebSocket object
     opts contains additional options for the request, supported contents as follows:
     ```JavaScript
     {
         "perMessageDeflate": false, // specify whether to use permessage-deflate, default is true
         "maxPayload": 67108864 // specify the maximum allowed message size, default is 64MB
     }
     ```
     @param opts Connection options, default is {}
     @param accept Connection success handler function, callback will pass two parameters, first is the received WebSocket object, second is the HttpRequest object during handshake
     @return Returns protocol handler, can be connected with HttpServer, Chain, Routing, etc.
     */
    static Handler upgrade(Object opts, Function accept);
};