/*! @brief X509CertificateRequest object is used to create x509 certificate requests, belongs to crypto module

You can use crypto.createCertificateRequest to create certificate requests, for example:

```JavaScript
var crypto = require('crypto');

var pk = crypto.createPrivateKey(rsa4096_pem);
var req = crypto.createCertificateRequest({
    key: pk,
    subject: {
        C: "CN",
        O: "baoz.cn",
        CN: "baoz.me"
    }
});
```

By calling the issue method of X509CertificateRequest, you can generate a formal certificate object, for example:

```JavaScript
let crt = req.issue({
    key: issuer_pk,
    issuer: {
        C: "CN",
        O: "baoz.cn",
        CN: "baoz.me"
    }
}); 
```

Note that the role of X509CertificateRequest object is to create x509 certificate requests, not certificates themselves. To obtain a valid certificate, it still needs to be signed. At the same time, the public key used for signing the certificate must be consistent with the public key used in the certificate request.
 */
interface X509CertificateRequest : object
{
    /*! @brief certificate request subject */
    readonly String subject;

    /*! @brief certificate request authenticated public key */
    readonly KeyObject publicKey;

    /*! @brief certificate request subject alternative name */
    readonly String subjectAltName;

    /*! @brief certificate request information access extension, returns a newline-separated list of access descriptions. Each line starts with the access method and access location type, followed by a colon and the value associated with the access location */
    readonly String infoAccess;

    /*! @brief certificate request raw binary data */
    readonly Buffer raw;

    /*! @brief certificate request PEM encoding */
    readonly String pem;

    /*! @brief check if the certificate request's public key matches the signature of the given private key
    @param privateKey private key
    @return returns true if matches, false otherwise
    */
    Boolean checkPrivateKey(KeyObject privateKey);

    /*! @brief Issue formal certificate based on request content

     Parameters in options will be used to call crypto.createPrivateKey to create private key object, in addition, the following signing parameters are supported:
      - issuer: issuer's subject information, containing key/value pairs of subject information
      - ca: whether it is a CA certificate, default false
      - pathlen: maximum length of certificate chain, default -1
      - validFrom: certificate effective time, default current time
      - validTo: certificate expiration time, if days is set at the same time, validTo takes precedence
      - days: certificate validity period, default 100 days
      - hashAlgorithm: hash algorithm for signature, default 'sha256'
      - keyUsage: certificate key usage, provided as array, default [], supported values:
        - 'digitalSignature': digital signature
        - 'nonRepudiation': non-repudiation
        - 'keyEncipherment': key encipherment
        - 'dataEncipherment': data encipherment
        - 'keyAgreement': key agreement
        - 'keyCertSign': certificate signing
        - 'cRLSign': CRL signing
        - 'encipherOnly': encipher only
        - 'decipherOnly': decipher only

     - type: certificate Nescape type, provided as array, default [], supported values:
        - 'client': client
        - 'server': server
        - 'email': email
        - 'objsign': object signing
        - 'reserved': reserved
        - 'sslCA': SSL CA
        - 'emailCA': email CA
        - 'objCA': object CA

     @param options certificate issuance options
     @return returns the issued certificate object
    */
    X509Certificate issue(Object options);
};