/*! @brief XmlCharacterData interface provides common functionality for XmlText and XmlComment nodes

XmlCharacterData is the superinterface for XmlText and XmlComment nodes. Documents never contain XmlCharacterData nodes directly, they only contain XmlText nodes and XmlComment nodes. But since these two types of nodes have similar functionality, these functions are defined here so that XmlText and XmlComment can inherit them.
*/
interface XmlCharacterData : XmlNode
{
    /*! @brief The text contained in this node
    */
    String data;

    /*! @brief The number of characters contained in this node
    */
    readonly Integer length;

    /*! @brief Extract a substring from the node
     @param offset The position of the first character to be returned
     @param count The number of characters to be returned in the substring
     @return Returns the extracted string
    */
    String substringData(Integer offset, Integer count);

    /*! @brief Append a string to the node
     @param arg The string to be appended to the node
    */
    appendData(String arg);

    /*! @brief Insert a string into the node
     @param offset The character position where the string is to be inserted into the node
     @param arg The string to be inserted
    */
    insertData(Integer offset, String arg);

    /*! @brief Remove text from the node
     @param offset The position of the first character to be removed
     @param count The number of characters to be removed
    */
    deleteData(Integer offset, Integer count);

    /*! @brief Replace the characters of the node with the specified string
     @param offset The position of the character in the node to be replaced
     @param count The number of characters to be replaced
     @param arg The string to be inserted
    */
    replaceData(Integer offset, Integer count, String arg);
};