/*! @brief XmlComment object represents the content of a comment node in the document

XmlComment nodes represent comments in XML documents.
The content of the comment can be accessed using the data property inherited from XmlCharacterData interface, or the nodeValue property inherited from XmlNode interface. (That is, the text between <!-- and -->). The content of the comment can be manipulated using the various methods inherited from XmlCharacterData interface.

Use XmlDocument.createComment() to create a comment object.
*/
interface XmlComment : XmlCharacterData
{
};