/*! @brief XmlCDATASection object represents a CDATA section in the document

XmlCDATASection interface is a subinterface of XmlText interface, and does not define any properties or methods of its own. The text content of the CDATA Section can be accessed through the nodeValue property inherited from XmlNode interface, or through the data property inherited from XmlCharacterData interface.

Although XmlCDATASection nodes can usually be treated as XmlText nodes, note that the normalize method of XmlNode does not merge adjacent CDATA sections.

Use XmlDocument's createXmlCDATASection method to create an XmlCDATASection.

CDATA sections contain text that is not parsed by the parser. Tags within CDATA sections are not treated as markup, and entities are not expanded. The main purpose is to include materials such as XML fragments without having to escape all the delimiters.

The only delimiter recognized in a CDATA is "]]>", which marks the end of the CDATA section. CDATA sections cannot be nested.
*/
interface XmlCDATASection : XmlText
{
};