/*! @brief XmlNodeList object represents an ordered list of nodes
*/
interface XmlNodeList : object
{
    /*! @brief Return the number of nodes in the node list
    */
    readonly Integer length;

    /*! @brief Return the node at the specified index in the node list
     @param index Specify the index to query
     @return The node at the specified index
    */
    XmlNode item(Integer index);

    /*! @brief Can directly access data using subscript
    */
    readonly XmlNode operator[];

    /*! @brief Query the iterator of the current object elements
     @return Return the iterator of the current object elements
    */
    Iterator @iterator();

    /*! @brief Execute a specified callback function once for each node in the list
     @param callback The callback function to execute for each node, receiving three parameters: current node, index, node list itself
    */
    forEach(Function callback);

    /*! @brief Return an iterator to iterate over the indices of each node in the node list
     @return Return an index iterator
    */
    Iterator keys();

    /*! @brief Return an iterator to iterate over the values of each node in the node list
     @return Return a value iterator
    */
    Iterator values();

    /*! @brief Return an iterator to iterate over [index, value] pairs of each node in the node list
     @return Return a key-value pair iterator
    */
    Iterator entries();
};