/*! @brief base64 编码与解码模块
 引用方式：
 @code
 var encoding = require('encoding');
 var base64 = encoding.base64;
 @endcode
 或者
 @code
 var base64 = require('base64');
 @endcode
 */
module base64
{
	/*! @brief 以 base64 方式编码数据
	 @param data 要编码的数据
	 @return 返回编码的字符串
	 */
	static String encode(Buffer data);

	/*! @brief 以 base64 方式解码字符串为二进制数据
	 @param data 要解码的字符串
	 @return 返回解码的二进制数据
	 */
	static Buffer decode(String data);
};
