/***************************************************************************
 *                                                                         *
 *   This file was automatically generated using idlc.js                   *
 *   PLEASE DO NOT EDIT!!!!                                                *
 *                                                                         *
 ***************************************************************************/

#pragma once

/**
 @author Leo Hoo <lion@9465.net>
 */

#include "../object.h"

namespace fibjs {

class constants_base : public object_base {
    DECLARE_CLASS(constants_base);

public:
    enum {
        C_RTLD_LAZY = 1,
        C_RTLD_NOW = 2,
        C_RTLD_GLOBAL = 8,
        C_RTLD_LOCAL = 4,
        C_E2BIG = 7,
        C_EACCES = 13,
        C_EADDRINUSE = 48,
        C_EADDRNOTAVAIL = 49,
        C_EAFNOSUPPORT = 47,
        C_EAGAIN = 35,
        C_EALREADY = 37,
        C_EBADF = 9,
        C_EBADMSG = 94,
        C_EBUSY = 16,
        C_ECANCELED = 89,
        C_ECHILD = 10,
        C_ECONNABORTED = 53,
        C_ECONNREFUSED = 61,
        C_ECONNRESET = 54,
        C_EDEADLK = 11,
        C_EDESTADDRREQ = 39,
        C_EDOM = 33,
        C_EDQUOT = 69,
        C_EEXIST = 17,
        C_EFAULT = 14,
        C_EFBIG = 27,
        C_EHOSTUNREACH = 65,
        C_EIDRM = 90,
        C_EILSEQ = 92,
        C_EINPROGRESS = 36,
        C_EINTR = 4,
        C_EINVAL = 22,
        C_EIO = 5,
        C_EISCONN = 56,
        C_EISDIR = 21,
        C_ELOOP = 62,
        C_EMFILE = 24,
        C_EMLINK = 31,
        C_EMSGSIZE = 40,
        C_EMULTIHOP = 95,
        C_ENAMETOOLONG = 63,
        C_ENETDOWN = 50,
        C_ENETRESET = 52,
        C_ENETUNREACH = 51,
        C_ENFILE = 23,
        C_ENOBUFS = 55,
        C_ENODATA = 96,
        C_ENODEV = 19,
        C_ENOENT = 2,
        C_ENOEXEC = 8,
        C_ENOLCK = 77,
        C_ENOLINK = 97,
        C_ENOMEM = 12,
        C_ENOMSG = 91,
        C_ENOPROTOOPT = 42,
        C_ENOSPC = 28,
        C_ENOSR = 98,
        C_ENOSTR = 99,
        C_ENOSYS = 78,
        C_ENOTCONN = 57,
        C_ENOTDIR = 20,
        C_ENOTEMPTY = 66,
        C_ENOTSOCK = 38,
        C_ENOTSUP = 45,
        C_ENOTTY = 25,
        C_ENXIO = 6,
        C_EOPNOTSUPP = 102,
        C_EOVERFLOW = 84,
        C_EPERM = 1,
        C_EPIPE = 32,
        C_EPROTO = 100,
        C_EPROTONOSUPPORT = 43,
        C_EPROTOTYPE = 41,
        C_ERANGE = 34,
        C_EROFS = 30,
        C_ESPIPE = 29,
        C_ESRCH = 3,
        C_ESTALE = 70,
        C_ETIME = 101,
        C_ETIMEDOUT = 60,
        C_ETXTBSY = 26,
        C_EWOULDBLOCK = 35,
        C_EXDEV = 18,
        C_PRIORITY_LOW = 19,
        C_PRIORITY_BELOW_NORMAL = 10,
        C_PRIORITY_NORMAL = 0,
        C_PRIORITY_ABOVE_NORMAL = -7,
        C_PRIORITY_HIGH = -14,
        C_PRIORITY_HIGHEST = -20,
        C_SIGHUP = 1,
        C_SIGINT = 2,
        C_SIGQUIT = 3,
        C_SIGILL = 4,
        C_SIGTRAP = 5,
        C_SIGABRT = 6,
        C_SIGIOT = 6,
        C_SIGBUS = 10,
        C_SIGFPE = 8,
        C_SIGKILL = 9,
        C_SIGUSR1 = 30,
        C_SIGSEGV = 11,
        C_SIGUSR2 = 31,
        C_SIGPIPE = 13,
        C_SIGALRM = 14,
        C_SIGTERM = 15,
        C_SIGCHLD = 20,
        C_SIGCONT = 19,
        C_SIGSTOP = 17,
        C_SIGTSTP = 18,
        C_SIGTTIN = 21,
        C_SIGTTOU = 22,
        C_SIGURG = 16,
        C_SIGXCPU = 24,
        C_SIGXFSZ = 25,
        C_SIGVTALRM = 26,
        C_SIGPROF = 27,
        C_SIGWINCH = 28,
        C_SIGIO = 23,
        C_SIGINFO = 29,
        C_SIGSYS = 12,
        C_UV_FS_SYMLINK_DIR = 1,
        C_UV_FS_SYMLINK_JUNCTION = 2,
        C_O_RDONLY = 0,
        C_O_WRONLY = 1,
        C_O_RDWR = 2,
        C_UV_DIRENT_UNKNOWN = 0,
        C_UV_DIRENT_FILE = 1,
        C_UV_DIRENT_DIR = 2,
        C_UV_DIRENT_LINK = 3,
        C_UV_DIRENT_FIFO = 4,
        C_UV_DIRENT_SOCKET = 5,
        C_UV_DIRENT_CHAR = 6,
        C_UV_DIRENT_BLOCK = 7,
        C_S_IFMT = 61440,
        C_S_IFREG = 32768,
        C_S_IFDIR = 16384,
        C_S_IFCHR = 8192,
        C_S_IFBLK = 24576,
        C_S_IFIFO = 4096,
        C_S_IFLNK = 40960,
        C_S_IFSOCK = 49152,
        C_O_CREAT = 512,
        C_O_EXCL = 2048,
        C_UV_FS_O_FILEMAP = 0,
        C_O_NOCTTY = 131072,
        C_O_TRUNC = 1024,
        C_O_APPEND = 8,
        C_O_DIRECTORY = 1048576,
        C_O_NOFOLLOW = 256,
        C_O_SYNC = 128,
        C_O_DSYNC = 4194304,
        C_O_SYMLINK = 2097152,
        C_O_NONBLOCK = 4,
        C_S_IRWXU = 448,
        C_S_IRUSR = 256,
        C_S_IWUSR = 128,
        C_S_IXUSR = 64,
        C_S_IRWXG = 56,
        C_S_IRGRP = 32,
        C_S_IWGRP = 16,
        C_S_IXGRP = 8,
        C_S_IRWXO = 7,
        C_S_IROTH = 4,
        C_S_IWOTH = 2,
        C_S_IXOTH = 1,
        C_F_OK = 0,
        C_R_OK = 4,
        C_W_OK = 2,
        C_X_OK = 1,
        C_UV_FS_COPYFILE_EXCL = 1,
        C_COPYFILE_EXCL = 1,
        C_UV_FS_COPYFILE_FICLONE = 2,
        C_COPYFILE_FICLONE = 2,
        C_UV_FS_COPYFILE_FICLONE_FORCE = 4,
        C_COPYFILE_FICLONE_FORCE = 4
    };

public:
    static void s__new(const v8::FunctionCallbackInfo<v8::Value>& args)
    {
        CONSTRUCT_INIT();

        Isolate* isolate = Isolate::current();

        isolate->m_isolate->ThrowException(
            isolate->NewString("not a constructor"));
    }
};
}

namespace fibjs {
inline ClassInfo& constants_base::class_info()
{
    static ClassData::ClassConst s_const[] = {
        { "RTLD_LAZY", C_RTLD_LAZY },
        { "RTLD_NOW", C_RTLD_NOW },
        { "RTLD_GLOBAL", C_RTLD_GLOBAL },
        { "RTLD_LOCAL", C_RTLD_LOCAL },
        { "E2BIG", C_E2BIG },
        { "EACCES", C_EACCES },
        { "EADDRINUSE", C_EADDRINUSE },
        { "EADDRNOTAVAIL", C_EADDRNOTAVAIL },
        { "EAFNOSUPPORT", C_EAFNOSUPPORT },
        { "EAGAIN", C_EAGAIN },
        { "EALREADY", C_EALREADY },
        { "EBADF", C_EBADF },
        { "EBADMSG", C_EBADMSG },
        { "EBUSY", C_EBUSY },
        { "ECANCELED", C_ECANCELED },
        { "ECHILD", C_ECHILD },
        { "ECONNABORTED", C_ECONNABORTED },
        { "ECONNREFUSED", C_ECONNREFUSED },
        { "ECONNRESET", C_ECONNRESET },
        { "EDEADLK", C_EDEADLK },
        { "EDESTADDRREQ", C_EDESTADDRREQ },
        { "EDOM", C_EDOM },
        { "EDQUOT", C_EDQUOT },
        { "EEXIST", C_EEXIST },
        { "EFAULT", C_EFAULT },
        { "EFBIG", C_EFBIG },
        { "EHOSTUNREACH", C_EHOSTUNREACH },
        { "EIDRM", C_EIDRM },
        { "EILSEQ", C_EILSEQ },
        { "EINPROGRESS", C_EINPROGRESS },
        { "EINTR", C_EINTR },
        { "EINVAL", C_EINVAL },
        { "EIO", C_EIO },
        { "EISCONN", C_EISCONN },
        { "EISDIR", C_EISDIR },
        { "ELOOP", C_ELOOP },
        { "EMFILE", C_EMFILE },
        { "EMLINK", C_EMLINK },
        { "EMSGSIZE", C_EMSGSIZE },
        { "EMULTIHOP", C_EMULTIHOP },
        { "ENAMETOOLONG", C_ENAMETOOLONG },
        { "ENETDOWN", C_ENETDOWN },
        { "ENETRESET", C_ENETRESET },
        { "ENETUNREACH", C_ENETUNREACH },
        { "ENFILE", C_ENFILE },
        { "ENOBUFS", C_ENOBUFS },
        { "ENODATA", C_ENODATA },
        { "ENODEV", C_ENODEV },
        { "ENOENT", C_ENOENT },
        { "ENOEXEC", C_ENOEXEC },
        { "ENOLCK", C_ENOLCK },
        { "ENOLINK", C_ENOLINK },
        { "ENOMEM", C_ENOMEM },
        { "ENOMSG", C_ENOMSG },
        { "ENOPROTOOPT", C_ENOPROTOOPT },
        { "ENOSPC", C_ENOSPC },
        { "ENOSR", C_ENOSR },
        { "ENOSTR", C_ENOSTR },
        { "ENOSYS", C_ENOSYS },
        { "ENOTCONN", C_ENOTCONN },
        { "ENOTDIR", C_ENOTDIR },
        { "ENOTEMPTY", C_ENOTEMPTY },
        { "ENOTSOCK", C_ENOTSOCK },
        { "ENOTSUP", C_ENOTSUP },
        { "ENOTTY", C_ENOTTY },
        { "ENXIO", C_ENXIO },
        { "EOPNOTSUPP", C_EOPNOTSUPP },
        { "EOVERFLOW", C_EOVERFLOW },
        { "EPERM", C_EPERM },
        { "EPIPE", C_EPIPE },
        { "EPROTO", C_EPROTO },
        { "EPROTONOSUPPORT", C_EPROTONOSUPPORT },
        { "EPROTOTYPE", C_EPROTOTYPE },
        { "ERANGE", C_ERANGE },
        { "EROFS", C_EROFS },
        { "ESPIPE", C_ESPIPE },
        { "ESRCH", C_ESRCH },
        { "ESTALE", C_ESTALE },
        { "ETIME", C_ETIME },
        { "ETIMEDOUT", C_ETIMEDOUT },
        { "ETXTBSY", C_ETXTBSY },
        { "EWOULDBLOCK", C_EWOULDBLOCK },
        { "EXDEV", C_EXDEV },
        { "PRIORITY_LOW", C_PRIORITY_LOW },
        { "PRIORITY_BELOW_NORMAL", C_PRIORITY_BELOW_NORMAL },
        { "PRIORITY_NORMAL", C_PRIORITY_NORMAL },
        { "PRIORITY_ABOVE_NORMAL", C_PRIORITY_ABOVE_NORMAL },
        { "PRIORITY_HIGH", C_PRIORITY_HIGH },
        { "PRIORITY_HIGHEST", C_PRIORITY_HIGHEST },
        { "SIGHUP", C_SIGHUP },
        { "SIGINT", C_SIGINT },
        { "SIGQUIT", C_SIGQUIT },
        { "SIGILL", C_SIGILL },
        { "SIGTRAP", C_SIGTRAP },
        { "SIGABRT", C_SIGABRT },
        { "SIGIOT", C_SIGIOT },
        { "SIGBUS", C_SIGBUS },
        { "SIGFPE", C_SIGFPE },
        { "SIGKILL", C_SIGKILL },
        { "SIGUSR1", C_SIGUSR1 },
        { "SIGSEGV", C_SIGSEGV },
        { "SIGUSR2", C_SIGUSR2 },
        { "SIGPIPE", C_SIGPIPE },
        { "SIGALRM", C_SIGALRM },
        { "SIGTERM", C_SIGTERM },
        { "SIGCHLD", C_SIGCHLD },
        { "SIGCONT", C_SIGCONT },
        { "SIGSTOP", C_SIGSTOP },
        { "SIGTSTP", C_SIGTSTP },
        { "SIGTTIN", C_SIGTTIN },
        { "SIGTTOU", C_SIGTTOU },
        { "SIGURG", C_SIGURG },
        { "SIGXCPU", C_SIGXCPU },
        { "SIGXFSZ", C_SIGXFSZ },
        { "SIGVTALRM", C_SIGVTALRM },
        { "SIGPROF", C_SIGPROF },
        { "SIGWINCH", C_SIGWINCH },
        { "SIGIO", C_SIGIO },
        { "SIGINFO", C_SIGINFO },
        { "SIGSYS", C_SIGSYS },
        { "UV_FS_SYMLINK_DIR", C_UV_FS_SYMLINK_DIR },
        { "UV_FS_SYMLINK_JUNCTION", C_UV_FS_SYMLINK_JUNCTION },
        { "O_RDONLY", C_O_RDONLY },
        { "O_WRONLY", C_O_WRONLY },
        { "O_RDWR", C_O_RDWR },
        { "UV_DIRENT_UNKNOWN", C_UV_DIRENT_UNKNOWN },
        { "UV_DIRENT_FILE", C_UV_DIRENT_FILE },
        { "UV_DIRENT_DIR", C_UV_DIRENT_DIR },
        { "UV_DIRENT_LINK", C_UV_DIRENT_LINK },
        { "UV_DIRENT_FIFO", C_UV_DIRENT_FIFO },
        { "UV_DIRENT_SOCKET", C_UV_DIRENT_SOCKET },
        { "UV_DIRENT_CHAR", C_UV_DIRENT_CHAR },
        { "UV_DIRENT_BLOCK", C_UV_DIRENT_BLOCK },
        { "S_IFMT", C_S_IFMT },
        { "S_IFREG", C_S_IFREG },
        { "S_IFDIR", C_S_IFDIR },
        { "S_IFCHR", C_S_IFCHR },
        { "S_IFBLK", C_S_IFBLK },
        { "S_IFIFO", C_S_IFIFO },
        { "S_IFLNK", C_S_IFLNK },
        { "S_IFSOCK", C_S_IFSOCK },
        { "O_CREAT", C_O_CREAT },
        { "O_EXCL", C_O_EXCL },
        { "UV_FS_O_FILEMAP", C_UV_FS_O_FILEMAP },
        { "O_NOCTTY", C_O_NOCTTY },
        { "O_TRUNC", C_O_TRUNC },
        { "O_APPEND", C_O_APPEND },
        { "O_DIRECTORY", C_O_DIRECTORY },
        { "O_NOFOLLOW", C_O_NOFOLLOW },
        { "O_SYNC", C_O_SYNC },
        { "O_DSYNC", C_O_DSYNC },
        { "O_SYMLINK", C_O_SYMLINK },
        { "O_NONBLOCK", C_O_NONBLOCK },
        { "S_IRWXU", C_S_IRWXU },
        { "S_IRUSR", C_S_IRUSR },
        { "S_IWUSR", C_S_IWUSR },
        { "S_IXUSR", C_S_IXUSR },
        { "S_IRWXG", C_S_IRWXG },
        { "S_IRGRP", C_S_IRGRP },
        { "S_IWGRP", C_S_IWGRP },
        { "S_IXGRP", C_S_IXGRP },
        { "S_IRWXO", C_S_IRWXO },
        { "S_IROTH", C_S_IROTH },
        { "S_IWOTH", C_S_IWOTH },
        { "S_IXOTH", C_S_IXOTH },
        { "F_OK", C_F_OK },
        { "R_OK", C_R_OK },
        { "W_OK", C_W_OK },
        { "X_OK", C_X_OK },
        { "UV_FS_COPYFILE_EXCL", C_UV_FS_COPYFILE_EXCL },
        { "COPYFILE_EXCL", C_COPYFILE_EXCL },
        { "UV_FS_COPYFILE_FICLONE", C_UV_FS_COPYFILE_FICLONE },
        { "COPYFILE_FICLONE", C_COPYFILE_FICLONE },
        { "UV_FS_COPYFILE_FICLONE_FORCE", C_UV_FS_COPYFILE_FICLONE_FORCE },
        { "COPYFILE_FICLONE_FORCE", C_COPYFILE_FICLONE_FORCE }
    };

    static ClassData s_cd = {
        "constants", true, s__new, NULL,
        0, NULL, 0, NULL, 0, NULL, ARRAYSIZE(s_const), s_const, NULL, NULL,
        &object_base::class_info()
    };

    static ClassInfo s_ci(s_cd);
    return s_ci;
}
}
