/***************************************************************************
 *                                                                         *
 *   This file was automatically generated using idlc.js                   *
 *   PLEASE DO NOT EDIT!!!!                                                *
 *                                                                         *
 ***************************************************************************/

#pragma once

/**
 @author Leo Hoo <lion@9465.net>
 */

#include "../object.h"

namespace fibjs {

class constants_base : public object_base {
    DECLARE_CLASS(constants_base);

public:
    enum {
        C_RTLD_LAZY = 1,
        C_RTLD_NOW = 2,
        C_RTLD_GLOBAL = 8,
        C_RTLD_LOCAL = 4,
        C_E2BIG = 7,
        C_EACCES = 13,
        C_EADDRINUSE = 48,
        C_EADDRNOTAVAIL = 49,
        C_EAFNOSUPPORT = 47,
        C_EAGAIN = 35,
        C_EALREADY = 37,
        C_EBADF = 9,
        C_EBADMSG = 94,
        C_EBUSY = 16,
        C_ECANCELED = 89,
        C_ECHILD = 10,
        C_ECONNABORTED = 53,
        C_ECONNREFUSED = 61,
        C_ECONNRESET = 54,
        C_EDEADLK = 11,
        C_EDESTADDRREQ = 39,
        C_EDOM = 33,
        C_EDQUOT = 69,
        C_EEXIST = 17,
        C_EFAULT = 14,
        C_EFBIG = 27,
        C_EHOSTUNREACH = 65,
        C_EIDRM = 90,
        C_EILSEQ = 92,
        C_EINPROGRESS = 36,
        C_EINTR = 4,
        C_EINVAL = 22,
        C_EIO = 5,
        C_EISCONN = 56,
        C_EISDIR = 21,
        C_ELOOP = 62,
        C_EMFILE = 24,
        C_EMLINK = 31,
        C_EMSGSIZE = 40,
        C_EMULTIHOP = 95,
        C_ENAMETOOLONG = 63,
        C_ENETDOWN = 50,
        C_ENETRESET = 52,
        C_ENETUNREACH = 51,
        C_ENFILE = 23,
        C_ENOBUFS = 55,
        C_ENODATA = 96,
        C_ENODEV = 19,
        C_ENOENT = 2,
        C_ENOEXEC = 8,
        C_ENOLCK = 77,
        C_ENOLINK = 97,
        C_ENOMEM = 12,
        C_ENOMSG = 91,
        C_ENOPROTOOPT = 42,
        C_ENOSPC = 28,
        C_ENOSR = 98,
        C_ENOSTR = 99,
        C_ENOSYS = 78,
        C_ENOTCONN = 57,
        C_ENOTDIR = 20,
        C_ENOTEMPTY = 66,
        C_ENOTSOCK = 38,
        C_ENOTSUP = 45,
        C_ENOTTY = 25,
        C_ENXIO = 6,
        C_EOPNOTSUPP = 102,
        C_EOVERFLOW = 84,
        C_EPERM = 1,
        C_EPIPE = 32,
        C_EPROTO = 100,
        C_EPROTONOSUPPORT = 43,
        C_EPROTOTYPE = 41,
        C_ERANGE = 34,
        C_EROFS = 30,
        C_ESPIPE = 29,
        C_ESRCH = 3,
        C_ESTALE = 70,
        C_ETIME = 101,
        C_ETIMEDOUT = 60,
        C_ETXTBSY = 26,
        C_EWOULDBLOCK = 35,
        C_EXDEV = 18,
        C_PRIORITY_LOW = 19,
        C_PRIORITY_BELOW_NORMAL = 10,
        C_PRIORITY_NORMAL = 0,
        C_PRIORITY_ABOVE_NORMAL = -7,
        C_PRIORITY_HIGH = -14,
        C_PRIORITY_HIGHEST = -20,
        C_SIGHUP = 1,
        C_SIGINT = 2,
        C_SIGQUIT = 3,
        C_SIGILL = 4,
        C_SIGTRAP = 5,
        C_SIGABRT = 6,
        C_SIGIOT = 6,
        C_SIGBUS = 10,
        C_SIGFPE = 8,
        C_SIGKILL = 9,
        C_SIGUSR1 = 30,
        C_SIGSEGV = 11,
        C_SIGUSR2 = 31,
        C_SIGPIPE = 13,
        C_SIGALRM = 14,
        C_SIGTERM = 15,
        C_SIGCHLD = 20,
        C_SIGCONT = 19,
        C_SIGSTOP = 17,
        C_SIGTSTP = 18,
        C_SIGTTIN = 21,
        C_SIGTTOU = 22,
        C_SIGURG = 16,
        C_SIGXCPU = 24,
        C_SIGXFSZ = 25,
        C_SIGVTALRM = 26,
        C_SIGPROF = 27,
        C_SIGWINCH = 28,
        C_SIGIO = 23,
        C_SIGINFO = 29,
        C_SIGSYS = 12,
        C_UV_FS_SYMLINK_DIR = 1,
        C_UV_FS_SYMLINK_JUNCTION = 2,
        C_O_RDONLY = 0,
        C_O_WRONLY = 1,
        C_O_RDWR = 2,
        C_UV_DIRENT_UNKNOWN = 0,
        C_UV_DIRENT_FILE = 1,
        C_UV_DIRENT_DIR = 2,
        C_UV_DIRENT_LINK = 3,
        C_UV_DIRENT_FIFO = 4,
        C_UV_DIRENT_SOCKET = 5,
        C_UV_DIRENT_CHAR = 6,
        C_UV_DIRENT_BLOCK = 7,
        C_S_IFMT = 61440,
        C_S_IFREG = 32768,
        C_S_IFDIR = 16384,
        C_S_IFCHR = 8192,
        C_S_IFBLK = 24576,
        C_S_IFIFO = 4096,
        C_S_IFLNK = 40960,
        C_S_IFSOCK = 49152,
        C_O_CREAT = 512,
        C_O_EXCL = 2048,
        C_UV_FS_O_FILEMAP = 0,
        C_O_NOCTTY = 131072,
        C_O_TRUNC = 1024,
        C_O_APPEND = 8,
        C_O_DIRECTORY = 1048576,
        C_O_NOFOLLOW = 256,
        C_O_SYNC = 128,
        C_O_DSYNC = 4194304,
        C_O_SYMLINK = 2097152,
        C_O_NONBLOCK = 4,
        C_S_IRWXU = 448,
        C_S_IRUSR = 256,
        C_S_IWUSR = 128,
        C_S_IXUSR = 64,
        C_S_IRWXG = 56,
        C_S_IRGRP = 32,
        C_S_IWGRP = 16,
        C_S_IXGRP = 8,
        C_S_IRWXO = 7,
        C_S_IROTH = 4,
        C_S_IWOTH = 2,
        C_S_IXOTH = 1,
        C_F_OK = 0,
        C_R_OK = 4,
        C_W_OK = 2,
        C_X_OK = 1,
        C_UV_FS_COPYFILE_EXCL = 1,
        C_COPYFILE_EXCL = 1,
        C_UV_FS_COPYFILE_FICLONE = 2,
        C_COPYFILE_FICLONE = 2,
        C_UV_FS_COPYFILE_FICLONE_FORCE = 4,
        C_COPYFILE_FICLONE_FORCE = 4
    };

public:
    static void s__new(const v8::FunctionCallbackInfo<v8::Value>& args)
    {
        CONSTRUCT_INIT();

        ThrowTypeError("not a constructor");
    }

    static result_t load(v8::Local<v8::Value> v, obj_ptr<constants_base>& retVal)
    { return CALL_E_TYPEMISMATCH; }
};
}

namespace fibjs {
inline ClassInfo& constants_base::class_info()
{
    static ClassData::ClassConst s_const[] = {
        { "RTLD_LAZY", ClassData::CONST_Integer, { .intValue = C_RTLD_LAZY } },
        { "RTLD_NOW", ClassData::CONST_Integer, { .intValue = C_RTLD_NOW } },
        { "RTLD_GLOBAL", ClassData::CONST_Integer, { .intValue = C_RTLD_GLOBAL } },
        { "RTLD_LOCAL", ClassData::CONST_Integer, { .intValue = C_RTLD_LOCAL } },
        { "E2BIG", ClassData::CONST_Integer, { .intValue = C_E2BIG } },
        { "EACCES", ClassData::CONST_Integer, { .intValue = C_EACCES } },
        { "EADDRINUSE", ClassData::CONST_Integer, { .intValue = C_EADDRINUSE } },
        { "EADDRNOTAVAIL", ClassData::CONST_Integer, { .intValue = C_EADDRNOTAVAIL } },
        { "EAFNOSUPPORT", ClassData::CONST_Integer, { .intValue = C_EAFNOSUPPORT } },
        { "EAGAIN", ClassData::CONST_Integer, { .intValue = C_EAGAIN } },
        { "EALREADY", ClassData::CONST_Integer, { .intValue = C_EALREADY } },
        { "EBADF", ClassData::CONST_Integer, { .intValue = C_EBADF } },
        { "EBADMSG", ClassData::CONST_Integer, { .intValue = C_EBADMSG } },
        { "EBUSY", ClassData::CONST_Integer, { .intValue = C_EBUSY } },
        { "ECANCELED", ClassData::CONST_Integer, { .intValue = C_ECANCELED } },
        { "ECHILD", ClassData::CONST_Integer, { .intValue = C_ECHILD } },
        { "ECONNABORTED", ClassData::CONST_Integer, { .intValue = C_ECONNABORTED } },
        { "ECONNREFUSED", ClassData::CONST_Integer, { .intValue = C_ECONNREFUSED } },
        { "ECONNRESET", ClassData::CONST_Integer, { .intValue = C_ECONNRESET } },
        { "EDEADLK", ClassData::CONST_Integer, { .intValue = C_EDEADLK } },
        { "EDESTADDRREQ", ClassData::CONST_Integer, { .intValue = C_EDESTADDRREQ } },
        { "EDOM", ClassData::CONST_Integer, { .intValue = C_EDOM } },
        { "EDQUOT", ClassData::CONST_Integer, { .intValue = C_EDQUOT } },
        { "EEXIST", ClassData::CONST_Integer, { .intValue = C_EEXIST } },
        { "EFAULT", ClassData::CONST_Integer, { .intValue = C_EFAULT } },
        { "EFBIG", ClassData::CONST_Integer, { .intValue = C_EFBIG } },
        { "EHOSTUNREACH", ClassData::CONST_Integer, { .intValue = C_EHOSTUNREACH } },
        { "EIDRM", ClassData::CONST_Integer, { .intValue = C_EIDRM } },
        { "EILSEQ", ClassData::CONST_Integer, { .intValue = C_EILSEQ } },
        { "EINPROGRESS", ClassData::CONST_Integer, { .intValue = C_EINPROGRESS } },
        { "EINTR", ClassData::CONST_Integer, { .intValue = C_EINTR } },
        { "EINVAL", ClassData::CONST_Integer, { .intValue = C_EINVAL } },
        { "EIO", ClassData::CONST_Integer, { .intValue = C_EIO } },
        { "EISCONN", ClassData::CONST_Integer, { .intValue = C_EISCONN } },
        { "EISDIR", ClassData::CONST_Integer, { .intValue = C_EISDIR } },
        { "ELOOP", ClassData::CONST_Integer, { .intValue = C_ELOOP } },
        { "EMFILE", ClassData::CONST_Integer, { .intValue = C_EMFILE } },
        { "EMLINK", ClassData::CONST_Integer, { .intValue = C_EMLINK } },
        { "EMSGSIZE", ClassData::CONST_Integer, { .intValue = C_EMSGSIZE } },
        { "EMULTIHOP", ClassData::CONST_Integer, { .intValue = C_EMULTIHOP } },
        { "ENAMETOOLONG", ClassData::CONST_Integer, { .intValue = C_ENAMETOOLONG } },
        { "ENETDOWN", ClassData::CONST_Integer, { .intValue = C_ENETDOWN } },
        { "ENETRESET", ClassData::CONST_Integer, { .intValue = C_ENETRESET } },
        { "ENETUNREACH", ClassData::CONST_Integer, { .intValue = C_ENETUNREACH } },
        { "ENFILE", ClassData::CONST_Integer, { .intValue = C_ENFILE } },
        { "ENOBUFS", ClassData::CONST_Integer, { .intValue = C_ENOBUFS } },
        { "ENODATA", ClassData::CONST_Integer, { .intValue = C_ENODATA } },
        { "ENODEV", ClassData::CONST_Integer, { .intValue = C_ENODEV } },
        { "ENOENT", ClassData::CONST_Integer, { .intValue = C_ENOENT } },
        { "ENOEXEC", ClassData::CONST_Integer, { .intValue = C_ENOEXEC } },
        { "ENOLCK", ClassData::CONST_Integer, { .intValue = C_ENOLCK } },
        { "ENOLINK", ClassData::CONST_Integer, { .intValue = C_ENOLINK } },
        { "ENOMEM", ClassData::CONST_Integer, { .intValue = C_ENOMEM } },
        { "ENOMSG", ClassData::CONST_Integer, { .intValue = C_ENOMSG } },
        { "ENOPROTOOPT", ClassData::CONST_Integer, { .intValue = C_ENOPROTOOPT } },
        { "ENOSPC", ClassData::CONST_Integer, { .intValue = C_ENOSPC } },
        { "ENOSR", ClassData::CONST_Integer, { .intValue = C_ENOSR } },
        { "ENOSTR", ClassData::CONST_Integer, { .intValue = C_ENOSTR } },
        { "ENOSYS", ClassData::CONST_Integer, { .intValue = C_ENOSYS } },
        { "ENOTCONN", ClassData::CONST_Integer, { .intValue = C_ENOTCONN } },
        { "ENOTDIR", ClassData::CONST_Integer, { .intValue = C_ENOTDIR } },
        { "ENOTEMPTY", ClassData::CONST_Integer, { .intValue = C_ENOTEMPTY } },
        { "ENOTSOCK", ClassData::CONST_Integer, { .intValue = C_ENOTSOCK } },
        { "ENOTSUP", ClassData::CONST_Integer, { .intValue = C_ENOTSUP } },
        { "ENOTTY", ClassData::CONST_Integer, { .intValue = C_ENOTTY } },
        { "ENXIO", ClassData::CONST_Integer, { .intValue = C_ENXIO } },
        { "EOPNOTSUPP", ClassData::CONST_Integer, { .intValue = C_EOPNOTSUPP } },
        { "EOVERFLOW", ClassData::CONST_Integer, { .intValue = C_EOVERFLOW } },
        { "EPERM", ClassData::CONST_Integer, { .intValue = C_EPERM } },
        { "EPIPE", ClassData::CONST_Integer, { .intValue = C_EPIPE } },
        { "EPROTO", ClassData::CONST_Integer, { .intValue = C_EPROTO } },
        { "EPROTONOSUPPORT", ClassData::CONST_Integer, { .intValue = C_EPROTONOSUPPORT } },
        { "EPROTOTYPE", ClassData::CONST_Integer, { .intValue = C_EPROTOTYPE } },
        { "ERANGE", ClassData::CONST_Integer, { .intValue = C_ERANGE } },
        { "EROFS", ClassData::CONST_Integer, { .intValue = C_EROFS } },
        { "ESPIPE", ClassData::CONST_Integer, { .intValue = C_ESPIPE } },
        { "ESRCH", ClassData::CONST_Integer, { .intValue = C_ESRCH } },
        { "ESTALE", ClassData::CONST_Integer, { .intValue = C_ESTALE } },
        { "ETIME", ClassData::CONST_Integer, { .intValue = C_ETIME } },
        { "ETIMEDOUT", ClassData::CONST_Integer, { .intValue = C_ETIMEDOUT } },
        { "ETXTBSY", ClassData::CONST_Integer, { .intValue = C_ETXTBSY } },
        { "EWOULDBLOCK", ClassData::CONST_Integer, { .intValue = C_EWOULDBLOCK } },
        { "EXDEV", ClassData::CONST_Integer, { .intValue = C_EXDEV } },
        { "PRIORITY_LOW", ClassData::CONST_Integer, { .intValue = C_PRIORITY_LOW } },
        { "PRIORITY_BELOW_NORMAL", ClassData::CONST_Integer, { .intValue = C_PRIORITY_BELOW_NORMAL } },
        { "PRIORITY_NORMAL", ClassData::CONST_Integer, { .intValue = C_PRIORITY_NORMAL } },
        { "PRIORITY_ABOVE_NORMAL", ClassData::CONST_Integer, { .intValue = C_PRIORITY_ABOVE_NORMAL } },
        { "PRIORITY_HIGH", ClassData::CONST_Integer, { .intValue = C_PRIORITY_HIGH } },
        { "PRIORITY_HIGHEST", ClassData::CONST_Integer, { .intValue = C_PRIORITY_HIGHEST } },
        { "SIGHUP", ClassData::CONST_Integer, { .intValue = C_SIGHUP } },
        { "SIGINT", ClassData::CONST_Integer, { .intValue = C_SIGINT } },
        { "SIGQUIT", ClassData::CONST_Integer, { .intValue = C_SIGQUIT } },
        { "SIGILL", ClassData::CONST_Integer, { .intValue = C_SIGILL } },
        { "SIGTRAP", ClassData::CONST_Integer, { .intValue = C_SIGTRAP } },
        { "SIGABRT", ClassData::CONST_Integer, { .intValue = C_SIGABRT } },
        { "SIGIOT", ClassData::CONST_Integer, { .intValue = C_SIGIOT } },
        { "SIGBUS", ClassData::CONST_Integer, { .intValue = C_SIGBUS } },
        { "SIGFPE", ClassData::CONST_Integer, { .intValue = C_SIGFPE } },
        { "SIGKILL", ClassData::CONST_Integer, { .intValue = C_SIGKILL } },
        { "SIGUSR1", ClassData::CONST_Integer, { .intValue = C_SIGUSR1 } },
        { "SIGSEGV", ClassData::CONST_Integer, { .intValue = C_SIGSEGV } },
        { "SIGUSR2", ClassData::CONST_Integer, { .intValue = C_SIGUSR2 } },
        { "SIGPIPE", ClassData::CONST_Integer, { .intValue = C_SIGPIPE } },
        { "SIGALRM", ClassData::CONST_Integer, { .intValue = C_SIGALRM } },
        { "SIGTERM", ClassData::CONST_Integer, { .intValue = C_SIGTERM } },
        { "SIGCHLD", ClassData::CONST_Integer, { .intValue = C_SIGCHLD } },
        { "SIGCONT", ClassData::CONST_Integer, { .intValue = C_SIGCONT } },
        { "SIGSTOP", ClassData::CONST_Integer, { .intValue = C_SIGSTOP } },
        { "SIGTSTP", ClassData::CONST_Integer, { .intValue = C_SIGTSTP } },
        { "SIGTTIN", ClassData::CONST_Integer, { .intValue = C_SIGTTIN } },
        { "SIGTTOU", ClassData::CONST_Integer, { .intValue = C_SIGTTOU } },
        { "SIGURG", ClassData::CONST_Integer, { .intValue = C_SIGURG } },
        { "SIGXCPU", ClassData::CONST_Integer, { .intValue = C_SIGXCPU } },
        { "SIGXFSZ", ClassData::CONST_Integer, { .intValue = C_SIGXFSZ } },
        { "SIGVTALRM", ClassData::CONST_Integer, { .intValue = C_SIGVTALRM } },
        { "SIGPROF", ClassData::CONST_Integer, { .intValue = C_SIGPROF } },
        { "SIGWINCH", ClassData::CONST_Integer, { .intValue = C_SIGWINCH } },
        { "SIGIO", ClassData::CONST_Integer, { .intValue = C_SIGIO } },
        { "SIGINFO", ClassData::CONST_Integer, { .intValue = C_SIGINFO } },
        { "SIGSYS", ClassData::CONST_Integer, { .intValue = C_SIGSYS } },
        { "UV_FS_SYMLINK_DIR", ClassData::CONST_Integer, { .intValue = C_UV_FS_SYMLINK_DIR } },
        { "UV_FS_SYMLINK_JUNCTION", ClassData::CONST_Integer, { .intValue = C_UV_FS_SYMLINK_JUNCTION } },
        { "O_RDONLY", ClassData::CONST_Integer, { .intValue = C_O_RDONLY } },
        { "O_WRONLY", ClassData::CONST_Integer, { .intValue = C_O_WRONLY } },
        { "O_RDWR", ClassData::CONST_Integer, { .intValue = C_O_RDWR } },
        { "UV_DIRENT_UNKNOWN", ClassData::CONST_Integer, { .intValue = C_UV_DIRENT_UNKNOWN } },
        { "UV_DIRENT_FILE", ClassData::CONST_Integer, { .intValue = C_UV_DIRENT_FILE } },
        { "UV_DIRENT_DIR", ClassData::CONST_Integer, { .intValue = C_UV_DIRENT_DIR } },
        { "UV_DIRENT_LINK", ClassData::CONST_Integer, { .intValue = C_UV_DIRENT_LINK } },
        { "UV_DIRENT_FIFO", ClassData::CONST_Integer, { .intValue = C_UV_DIRENT_FIFO } },
        { "UV_DIRENT_SOCKET", ClassData::CONST_Integer, { .intValue = C_UV_DIRENT_SOCKET } },
        { "UV_DIRENT_CHAR", ClassData::CONST_Integer, { .intValue = C_UV_DIRENT_CHAR } },
        { "UV_DIRENT_BLOCK", ClassData::CONST_Integer, { .intValue = C_UV_DIRENT_BLOCK } },
        { "S_IFMT", ClassData::CONST_Integer, { .intValue = C_S_IFMT } },
        { "S_IFREG", ClassData::CONST_Integer, { .intValue = C_S_IFREG } },
        { "S_IFDIR", ClassData::CONST_Integer, { .intValue = C_S_IFDIR } },
        { "S_IFCHR", ClassData::CONST_Integer, { .intValue = C_S_IFCHR } },
        { "S_IFBLK", ClassData::CONST_Integer, { .intValue = C_S_IFBLK } },
        { "S_IFIFO", ClassData::CONST_Integer, { .intValue = C_S_IFIFO } },
        { "S_IFLNK", ClassData::CONST_Integer, { .intValue = C_S_IFLNK } },
        { "S_IFSOCK", ClassData::CONST_Integer, { .intValue = C_S_IFSOCK } },
        { "O_CREAT", ClassData::CONST_Integer, { .intValue = C_O_CREAT } },
        { "O_EXCL", ClassData::CONST_Integer, { .intValue = C_O_EXCL } },
        { "UV_FS_O_FILEMAP", ClassData::CONST_Integer, { .intValue = C_UV_FS_O_FILEMAP } },
        { "O_NOCTTY", ClassData::CONST_Integer, { .intValue = C_O_NOCTTY } },
        { "O_TRUNC", ClassData::CONST_Integer, { .intValue = C_O_TRUNC } },
        { "O_APPEND", ClassData::CONST_Integer, { .intValue = C_O_APPEND } },
        { "O_DIRECTORY", ClassData::CONST_Integer, { .intValue = C_O_DIRECTORY } },
        { "O_NOFOLLOW", ClassData::CONST_Integer, { .intValue = C_O_NOFOLLOW } },
        { "O_SYNC", ClassData::CONST_Integer, { .intValue = C_O_SYNC } },
        { "O_DSYNC", ClassData::CONST_Integer, { .intValue = C_O_DSYNC } },
        { "O_SYMLINK", ClassData::CONST_Integer, { .intValue = C_O_SYMLINK } },
        { "O_NONBLOCK", ClassData::CONST_Integer, { .intValue = C_O_NONBLOCK } },
        { "S_IRWXU", ClassData::CONST_Integer, { .intValue = C_S_IRWXU } },
        { "S_IRUSR", ClassData::CONST_Integer, { .intValue = C_S_IRUSR } },
        { "S_IWUSR", ClassData::CONST_Integer, { .intValue = C_S_IWUSR } },
        { "S_IXUSR", ClassData::CONST_Integer, { .intValue = C_S_IXUSR } },
        { "S_IRWXG", ClassData::CONST_Integer, { .intValue = C_S_IRWXG } },
        { "S_IRGRP", ClassData::CONST_Integer, { .intValue = C_S_IRGRP } },
        { "S_IWGRP", ClassData::CONST_Integer, { .intValue = C_S_IWGRP } },
        { "S_IXGRP", ClassData::CONST_Integer, { .intValue = C_S_IXGRP } },
        { "S_IRWXO", ClassData::CONST_Integer, { .intValue = C_S_IRWXO } },
        { "S_IROTH", ClassData::CONST_Integer, { .intValue = C_S_IROTH } },
        { "S_IWOTH", ClassData::CONST_Integer, { .intValue = C_S_IWOTH } },
        { "S_IXOTH", ClassData::CONST_Integer, { .intValue = C_S_IXOTH } },
        { "F_OK", ClassData::CONST_Integer, { .intValue = C_F_OK } },
        { "R_OK", ClassData::CONST_Integer, { .intValue = C_R_OK } },
        { "W_OK", ClassData::CONST_Integer, { .intValue = C_W_OK } },
        { "X_OK", ClassData::CONST_Integer, { .intValue = C_X_OK } },
        { "UV_FS_COPYFILE_EXCL", ClassData::CONST_Integer, { .intValue = C_UV_FS_COPYFILE_EXCL } },
        { "COPYFILE_EXCL", ClassData::CONST_Integer, { .intValue = C_COPYFILE_EXCL } },
        { "UV_FS_COPYFILE_FICLONE", ClassData::CONST_Integer, { .intValue = C_UV_FS_COPYFILE_FICLONE } },
        { "COPYFILE_FICLONE", ClassData::CONST_Integer, { .intValue = C_COPYFILE_FICLONE } },
        { "UV_FS_COPYFILE_FICLONE_FORCE", ClassData::CONST_Integer, { .intValue = C_UV_FS_COPYFILE_FICLONE_FORCE } },
        { "COPYFILE_FICLONE_FORCE", ClassData::CONST_Integer, { .intValue = C_COPYFILE_FICLONE_FORCE } }
    };

    static ClassData s_cd = {
        "constants", true, s__new, NULL,
        0, NULL, 0, NULL, 0, NULL, ARRAYSIZE(s_const), s_const, NULL, NULL,
        &object_base::class_info(),
        false
    };

    static ClassInfo s_ci(s_cd);
    return s_ci;
}
}
