
/*! @brief 事件触发对象，可用于建立观察者模式，支持事件触发的对象均继承于此
 *
 * Event 对象可独立创建，以用于组建自定义的事件系统：
 * @code
 * var e = new Event();
 * @endcode
 */
class EventObject : object
{
	EventObject();
	on(String ev, Function func);
	once(String ev, Function func);
	off(String ev, Function func);
	trigger(String ev, ...);
};

