/*! @brief 文件操作对象，用于二进制文件读写

 文件操作对象用于对二进制文件进行操作，可使用 fs 模块打开和创建文件：
 @code
 var f = fs.open('test.txt');
 @endcode
 */
interface File : SeekableStream
{
    /*! @brief 查询当前文件名 */
    readonly String name;

    /*! @brief 查询当前文件的访问权限，Windows 不支持此方法
     @param mode 指定设定的访问权限
     */
    chmod(Integer mode) async;
};
