/*! @brief 输入输出处理模块

使用方法：
```JavaScript
var gui = require('gui');
```
 */
module gui
{
    /*! @brief WebView ie 模拟版本，指定 ie7 */
    const IE7 = 7000;

    /*! @brief WebView ie 模拟版本，指定 ie8 */
    const IE8 = 8000;

    /*! @brief WebView ie 模拟版本，指定 ie9 */
    const IE9 = 9000;

    /*! @brief WebView ie 模拟版本，指定 ie10 */
    const IE10 = 10000;

    /*! @brief WebView ie 模拟版本，指定 ie11 */
    const IE11 = 11000;

    /*! @brief WebView ie 模拟版本，指定 edge */
    const EDGE = 11001;

    /* 设置 WebView 内 ie 模拟版本 */
    static setVersion(Integer ver);

    /*! @brief 打开一个窗口并访问指定网址
	 @param url 指定的网址，，可以使用 fs:path 访问本地文件系统
	 @return 返回打开的窗口对象
	 */
    static WebView open(String url) async;

    /*! @brief 打开一个窗口并访问指定网址

     支持以下参数:
     ```JavaScript
     {
         "left": 100, // 窗口左上角 x，缺省系统自动设定
         "right": 100, // 窗口左上角 y，缺省系统自动设定
         "width": 100, // 窗口宽度，缺省系统自动设定
         "height": 100, // 窗口高度，缺省系统自动设定
         "border": true, // 是否有边框，缺省有边框
         "caption": true, // 是否有标题栏，缺省有标题栏
         "resizable": true, // 是否可改变尺寸，缺省可以改变
         "maximize": false, // 是否最大化显示，缺省不最大化
         "visible": true, // 是否显示，缺省显示
         "debug": false // 是否提示页面错误，缺省不提示
     }
     ```
     当设定 width 和 height，而未设定 left 或 right 时，窗口将自动居中
     @param url 指定的网址，，可以使用 fs:path 访问本地文件系统
     @param opt 打开窗口参数
     @return 返回打开的窗口对象
	*/
    static WebView open(String url, Map opt) async;
};
