
/*! @brief 超文本传输协议模块，用以支持 http 协议处理 */
class http : module
{
	/*! @brief 创建一个 http 请求对象，参见 HttpRequest */
	static HttpRequest new Request();

	/*! @brief 创建一个 http 响应对象，参见 HttpResponse */
	static HttpResponse new Response();

	/*! @brief 创建一个 http 协议处理器对象，参见 HttpResponse */
	static HttpHandler new Handler();
};
