/***************************************************************************
 *                                                                         *
 *   This file was automatically generated using idlc.js                   *
 *   PLEASE DO NOT EDIT!!!!                                                *
 *                                                                         *
 ***************************************************************************/

#pragma once

/**
 @author Leo Hoo <lion@9465.net>
 */

#include "../object.h"

namespace fibjs {

class http2_constants_base : public object_base {
    DECLARE_CLASS(http2_constants_base);

public:
    enum {
        C_DEFAULT_SETTINGS_ENABLE_CONNECT_PROTOCOL = 0,
        C_DEFAULT_SETTINGS_ENABLE_PUSH = 1,
        C_DEFAULT_SETTINGS_HEADER_TABLE_SIZE = 4096,
        C_DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE = 65535,
        C_DEFAULT_SETTINGS_MAX_FRAME_SIZE = 16384,
        C_DEFAULT_SETTINGS_MAX_HEADER_LIST_SIZE = 65535,
        C_HTTP_STATUS_CONTINUE = 100,
        C_HTTP_STATUS_SWITCHING_PROTOCOLS = 101,
        C_HTTP_STATUS_PROCESSING = 102,
        C_HTTP_STATUS_EARLY_HINTS = 103,
        C_HTTP_STATUS_OK = 200,
        C_HTTP_STATUS_CREATED = 201,
        C_HTTP_STATUS_ACCEPTED = 202,
        C_HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION = 203,
        C_HTTP_STATUS_NO_CONTENT = 204,
        C_HTTP_STATUS_RESET_CONTENT = 205,
        C_HTTP_STATUS_PARTIAL_CONTENT = 206,
        C_HTTP_STATUS_MULTI_STATUS = 207,
        C_HTTP_STATUS_ALREADY_REPORTED = 208,
        C_HTTP_STATUS_IM_USED = 226,
        C_HTTP_STATUS_MULTIPLE_CHOICES = 300,
        C_HTTP_STATUS_MOVED_PERMANENTLY = 301,
        C_HTTP_STATUS_FOUND = 302,
        C_HTTP_STATUS_SEE_OTHER = 303,
        C_HTTP_STATUS_NOT_MODIFIED = 304,
        C_HTTP_STATUS_USE_PROXY = 305,
        C_HTTP_STATUS_TEMPORARY_REDIRECT = 307,
        C_HTTP_STATUS_PERMANENT_REDIRECT = 308,
        C_HTTP_STATUS_BAD_REQUEST = 400,
        C_HTTP_STATUS_UNAUTHORIZED = 401,
        C_HTTP_STATUS_PAYMENT_REQUIRED = 402,
        C_HTTP_STATUS_FORBIDDEN = 403,
        C_HTTP_STATUS_NOT_FOUND = 404,
        C_HTTP_STATUS_METHOD_NOT_ALLOWED = 405,
        C_HTTP_STATUS_NOT_ACCEPTABLE = 406,
        C_HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED = 407,
        C_HTTP_STATUS_REQUEST_TIMEOUT = 408,
        C_HTTP_STATUS_CONFLICT = 409,
        C_HTTP_STATUS_GONE = 410,
        C_HTTP_STATUS_LENGTH_REQUIRED = 411,
        C_HTTP_STATUS_PRECONDITION_FAILED = 412,
        C_HTTP_STATUS_PAYLOAD_TOO_LARGE = 413,
        C_HTTP_STATUS_URI_TOO_LONG = 414,
        C_HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415,
        C_HTTP_STATUS_RANGE_NOT_SATISFIABLE = 416,
        C_HTTP_STATUS_EXPECTATION_FAILED = 417,
        C_HTTP_STATUS_TEAPOT = 418,
        C_HTTP_STATUS_MISDIRECTED_REQUEST = 421,
        C_HTTP_STATUS_UNPROCESSABLE_ENTITY = 422,
        C_HTTP_STATUS_LOCKED = 423,
        C_HTTP_STATUS_FAILED_DEPENDENCY = 424,
        C_HTTP_STATUS_TOO_EARLY = 425,
        C_HTTP_STATUS_UPGRADE_REQUIRED = 426,
        C_HTTP_STATUS_PRECONDITION_REQUIRED = 428,
        C_HTTP_STATUS_TOO_MANY_REQUESTS = 429,
        C_HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
        C_HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = 451,
        C_HTTP_STATUS_INTERNAL_SERVER_ERROR = 500,
        C_HTTP_STATUS_NOT_IMPLEMENTED = 501,
        C_HTTP_STATUS_BAD_GATEWAY = 502,
        C_HTTP_STATUS_SERVICE_UNAVAILABLE = 503,
        C_HTTP_STATUS_GATEWAY_TIMEOUT = 504,
        C_HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED = 505,
        C_HTTP_STATUS_VARIANT_ALSO_NEGOTIATES = 506,
        C_HTTP_STATUS_INSUFFICIENT_STORAGE = 507,
        C_HTTP_STATUS_LOOP_DETECTED = 508,
        C_HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED = 509,
        C_HTTP_STATUS_NOT_EXTENDED = 510,
        C_HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED = 511,
        C_MAX_INITIAL_WINDOW_SIZE = 2147483647,
        C_MAX_MAX_FRAME_SIZE = 16777215,
        C_MIN_MAX_FRAME_SIZE = 16384,
        C_NGHTTP2_NO_ERROR = 0,
        C_NGHTTP2_PROTOCOL_ERROR = 1,
        C_NGHTTP2_INTERNAL_ERROR = 2,
        C_NGHTTP2_FLOW_CONTROL_ERROR = 3,
        C_NGHTTP2_STREAM_CLOSED = 5,
        C_NGHTTP2_FRAME_SIZE_ERROR = 6,
        C_NGHTTP2_REFUSED_STREAM = 7,
        C_NGHTTP2_CANCEL = 8,
        C_NGHTTP2_COMPRESSION_ERROR = 9,
        C_NGHTTP2_CONNECT_ERROR = 10,
        C_NGHTTP2_ENHANCE_YOUR_CALM = 11,
        C_NGHTTP2_INADEQUATE_SECURITY = 12,
        C_NGHTTP2_HTTP_1_1_REQUIRED = 13,
        C_NGHTTP2_ERR_FRAME_SIZE_ERROR = -522,
        C_NGHTTP2_FLAG_NONE = 0,
        C_NGHTTP2_FLAG_ACK = 1,
        C_NGHTTP2_FLAG_END_STREAM = 1,
        C_NGHTTP2_FLAG_END_HEADERS = 4,
        C_NGHTTP2_FLAG_PADDED = 8,
        C_NGHTTP2_FLAG_PRIORITY = 32,
        C_NGHTTP2_DEFAULT_WEIGHT = 16,
        C_NGHTTP2_SESSION_SERVER = 0,
        C_NGHTTP2_SESSION_CLIENT = 1,
        C_NGHTTP2_SETTINGS_HEADER_TABLE_SIZE = 1,
        C_NGHTTP2_SETTINGS_ENABLE_PUSH = 2,
        C_NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS = 3,
        C_NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE = 4,
        C_NGHTTP2_SETTINGS_TIMEOUT = 4,
        C_NGHTTP2_SETTINGS_MAX_FRAME_SIZE = 5,
        C_NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE = 6,
        C_NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL = 8,
        C_NGHTTP2_STREAM_STATE_IDLE = 1,
        C_NGHTTP2_STREAM_STATE_OPEN = 2,
        C_NGHTTP2_STREAM_STATE_RESERVED_LOCAL = 3,
        C_NGHTTP2_STREAM_STATE_RESERVED_REMOTE = 4,
        C_NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL = 5,
        C_NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE = 6,
        C_NGHTTP2_STREAM_STATE_CLOSED = 7,
        C_PADDING_STRATEGY_NONE = 0,
        C_PADDING_STRATEGY_ALIGNED = 1,
        C_PADDING_STRATEGY_CALLBACK = 1,
        C_PADDING_STRATEGY_MAX = 2
    };

public:
    static const int64_t C_DEFAULT_SETTINGS_MAX_CONCURRENT_STREAMS = 4294967295LL;

public:
    static void s__new(const v8::FunctionCallbackInfo<v8::Value>& args)
    {
        CONSTRUCT_INIT();

        ThrowTypeError("not a constructor");
    }

    static result_t load(v8::Local<v8::Value> v, obj_ptr<http2_constants_base>& retVal)
    { return CALL_E_TYPEMISMATCH; }
};
}

namespace fibjs {
inline ClassInfo& http2_constants_base::class_info()
{
    static ClassData::ClassConst s_const[] = {
        { "DEFAULT_SETTINGS_ENABLE_CONNECT_PROTOCOL", ClassData::CONST_Integer, { .intValue = C_DEFAULT_SETTINGS_ENABLE_CONNECT_PROTOCOL } },
        { "DEFAULT_SETTINGS_ENABLE_PUSH", ClassData::CONST_Integer, { .intValue = C_DEFAULT_SETTINGS_ENABLE_PUSH } },
        { "DEFAULT_SETTINGS_HEADER_TABLE_SIZE", ClassData::CONST_Integer, { .intValue = C_DEFAULT_SETTINGS_HEADER_TABLE_SIZE } },
        { "DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE", ClassData::CONST_Integer, { .intValue = C_DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE } },
        { "DEFAULT_SETTINGS_MAX_CONCURRENT_STREAMS", ClassData::CONST_Long, { .longValue = C_DEFAULT_SETTINGS_MAX_CONCURRENT_STREAMS } },
        { "DEFAULT_SETTINGS_MAX_FRAME_SIZE", ClassData::CONST_Integer, { .intValue = C_DEFAULT_SETTINGS_MAX_FRAME_SIZE } },
        { "DEFAULT_SETTINGS_MAX_HEADER_LIST_SIZE", ClassData::CONST_Integer, { .intValue = C_DEFAULT_SETTINGS_MAX_HEADER_LIST_SIZE } },
        { "HTTP_STATUS_CONTINUE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_CONTINUE } },
        { "HTTP_STATUS_SWITCHING_PROTOCOLS", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_SWITCHING_PROTOCOLS } },
        { "HTTP_STATUS_PROCESSING", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_PROCESSING } },
        { "HTTP_STATUS_EARLY_HINTS", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_EARLY_HINTS } },
        { "HTTP_STATUS_OK", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_OK } },
        { "HTTP_STATUS_CREATED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_CREATED } },
        { "HTTP_STATUS_ACCEPTED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_ACCEPTED } },
        { "HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION } },
        { "HTTP_STATUS_NO_CONTENT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_NO_CONTENT } },
        { "HTTP_STATUS_RESET_CONTENT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_RESET_CONTENT } },
        { "HTTP_STATUS_PARTIAL_CONTENT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_PARTIAL_CONTENT } },
        { "HTTP_STATUS_MULTI_STATUS", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_MULTI_STATUS } },
        { "HTTP_STATUS_ALREADY_REPORTED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_ALREADY_REPORTED } },
        { "HTTP_STATUS_IM_USED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_IM_USED } },
        { "HTTP_STATUS_MULTIPLE_CHOICES", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_MULTIPLE_CHOICES } },
        { "HTTP_STATUS_MOVED_PERMANENTLY", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_MOVED_PERMANENTLY } },
        { "HTTP_STATUS_FOUND", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_FOUND } },
        { "HTTP_STATUS_SEE_OTHER", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_SEE_OTHER } },
        { "HTTP_STATUS_NOT_MODIFIED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_NOT_MODIFIED } },
        { "HTTP_STATUS_USE_PROXY", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_USE_PROXY } },
        { "HTTP_STATUS_TEMPORARY_REDIRECT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_TEMPORARY_REDIRECT } },
        { "HTTP_STATUS_PERMANENT_REDIRECT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_PERMANENT_REDIRECT } },
        { "HTTP_STATUS_BAD_REQUEST", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_BAD_REQUEST } },
        { "HTTP_STATUS_UNAUTHORIZED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_UNAUTHORIZED } },
        { "HTTP_STATUS_PAYMENT_REQUIRED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_PAYMENT_REQUIRED } },
        { "HTTP_STATUS_FORBIDDEN", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_FORBIDDEN } },
        { "HTTP_STATUS_NOT_FOUND", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_NOT_FOUND } },
        { "HTTP_STATUS_METHOD_NOT_ALLOWED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_METHOD_NOT_ALLOWED } },
        { "HTTP_STATUS_NOT_ACCEPTABLE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_NOT_ACCEPTABLE } },
        { "HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED } },
        { "HTTP_STATUS_REQUEST_TIMEOUT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_REQUEST_TIMEOUT } },
        { "HTTP_STATUS_CONFLICT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_CONFLICT } },
        { "HTTP_STATUS_GONE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_GONE } },
        { "HTTP_STATUS_LENGTH_REQUIRED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_LENGTH_REQUIRED } },
        { "HTTP_STATUS_PRECONDITION_FAILED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_PRECONDITION_FAILED } },
        { "HTTP_STATUS_PAYLOAD_TOO_LARGE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_PAYLOAD_TOO_LARGE } },
        { "HTTP_STATUS_URI_TOO_LONG", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_URI_TOO_LONG } },
        { "HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE } },
        { "HTTP_STATUS_RANGE_NOT_SATISFIABLE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_RANGE_NOT_SATISFIABLE } },
        { "HTTP_STATUS_EXPECTATION_FAILED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_EXPECTATION_FAILED } },
        { "HTTP_STATUS_TEAPOT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_TEAPOT } },
        { "HTTP_STATUS_MISDIRECTED_REQUEST", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_MISDIRECTED_REQUEST } },
        { "HTTP_STATUS_UNPROCESSABLE_ENTITY", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_UNPROCESSABLE_ENTITY } },
        { "HTTP_STATUS_LOCKED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_LOCKED } },
        { "HTTP_STATUS_FAILED_DEPENDENCY", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_FAILED_DEPENDENCY } },
        { "HTTP_STATUS_TOO_EARLY", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_TOO_EARLY } },
        { "HTTP_STATUS_UPGRADE_REQUIRED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_UPGRADE_REQUIRED } },
        { "HTTP_STATUS_PRECONDITION_REQUIRED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_PRECONDITION_REQUIRED } },
        { "HTTP_STATUS_TOO_MANY_REQUESTS", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_TOO_MANY_REQUESTS } },
        { "HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE } },
        { "HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS } },
        { "HTTP_STATUS_INTERNAL_SERVER_ERROR", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_INTERNAL_SERVER_ERROR } },
        { "HTTP_STATUS_NOT_IMPLEMENTED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_NOT_IMPLEMENTED } },
        { "HTTP_STATUS_BAD_GATEWAY", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_BAD_GATEWAY } },
        { "HTTP_STATUS_SERVICE_UNAVAILABLE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_SERVICE_UNAVAILABLE } },
        { "HTTP_STATUS_GATEWAY_TIMEOUT", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_GATEWAY_TIMEOUT } },
        { "HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED } },
        { "HTTP_STATUS_VARIANT_ALSO_NEGOTIATES", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_VARIANT_ALSO_NEGOTIATES } },
        { "HTTP_STATUS_INSUFFICIENT_STORAGE", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_INSUFFICIENT_STORAGE } },
        { "HTTP_STATUS_LOOP_DETECTED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_LOOP_DETECTED } },
        { "HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED } },
        { "HTTP_STATUS_NOT_EXTENDED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_NOT_EXTENDED } },
        { "HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED", ClassData::CONST_Integer, { .intValue = C_HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED } },
        { "HTTP2_HEADER_AUTHORITY", ClassData::CONST_String, { .stringValue = ":authority" } },
        { "HTTP2_HEADER_ACCEPT", ClassData::CONST_String, { .stringValue = "accept" } },
        { "HTTP2_HEADER_ACCEPT_CHARSET", ClassData::CONST_String, { .stringValue = "accept-charset" } },
        { "HTTP2_HEADER_ACCEPT_ENCODING", ClassData::CONST_String, { .stringValue = "accept-encoding" } },
        { "HTTP2_HEADER_ACCEPT_LANGUAGE", ClassData::CONST_String, { .stringValue = "accept-language" } },
        { "HTTP2_HEADER_ACCEPT_RANGES", ClassData::CONST_String, { .stringValue = "accept-ranges" } },
        { "HTTP2_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS", ClassData::CONST_String, { .stringValue = "access-control-allow-credentials" } },
        { "HTTP2_HEADER_ACCESS_CONTROL_ALLOW_HEADERS", ClassData::CONST_String, { .stringValue = "access-control-allow-headers" } },
        { "HTTP2_HEADER_ACCESS_CONTROL_ALLOW_METHODS", ClassData::CONST_String, { .stringValue = "access-control-allow-methods" } },
        { "HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN", ClassData::CONST_String, { .stringValue = "access-control-allow-origin" } },
        { "HTTP2_HEADER_ACCESS_CONTROL_EXPOSE_HEADERS", ClassData::CONST_String, { .stringValue = "access-control-expose-headers" } },
        { "HTTP2_HEADER_ACCESS_CONTROL_MAX_AGE", ClassData::CONST_String, { .stringValue = "access-control-max-age" } },
        { "HTTP2_HEADER_ACCESS_CONTROL_REQUEST_HEADERS", ClassData::CONST_String, { .stringValue = "access-control-request-headers" } },
        { "HTTP2_HEADER_ACCESS_CONTROL_REQUEST_METHOD", ClassData::CONST_String, { .stringValue = "access-control-request-method" } },
        { "HTTP2_HEADER_AGE", ClassData::CONST_String, { .stringValue = "age" } },
        { "HTTP2_HEADER_ALLOW", ClassData::CONST_String, { .stringValue = "allow" } },
        { "HTTP2_HEADER_ALT_SVC", ClassData::CONST_String, { .stringValue = "alt-svc" } },
        { "HTTP2_HEADER_AUTHORIZATION", ClassData::CONST_String, { .stringValue = "authorization" } },
        { "HTTP2_HEADER_CACHE_CONTROL", ClassData::CONST_String, { .stringValue = "cache-control" } },
        { "HTTP2_HEADER_CONNECTION", ClassData::CONST_String, { .stringValue = "connection" } },
        { "HTTP2_HEADER_CONTENT_DISPOSITION", ClassData::CONST_String, { .stringValue = "content-disposition" } },
        { "HTTP2_HEADER_CONTENT_ENCODING", ClassData::CONST_String, { .stringValue = "content-encoding" } },
        { "HTTP2_HEADER_CONTENT_LANGUAGE", ClassData::CONST_String, { .stringValue = "content-language" } },
        { "HTTP2_HEADER_CONTENT_LENGTH", ClassData::CONST_String, { .stringValue = "content-length" } },
        { "HTTP2_HEADER_CONTENT_LOCATION", ClassData::CONST_String, { .stringValue = "content-location" } },
        { "HTTP2_HEADER_CONTENT_MD5", ClassData::CONST_String, { .stringValue = "content-md5" } },
        { "HTTP2_HEADER_CONTENT_RANGE", ClassData::CONST_String, { .stringValue = "content-range" } },
        { "HTTP2_HEADER_CONTENT_SECURITY_POLICY", ClassData::CONST_String, { .stringValue = "content-security-policy" } },
        { "HTTP2_HEADER_CONTENT_TYPE", ClassData::CONST_String, { .stringValue = "content-type" } },
        { "HTTP2_HEADER_COOKIE", ClassData::CONST_String, { .stringValue = "cookie" } },
        { "HTTP2_HEADER_DATE", ClassData::CONST_String, { .stringValue = "date" } },
        { "HTTP2_HEADER_DNT", ClassData::CONST_String, { .stringValue = "dnt" } },
        { "HTTP2_HEADER_EARLY_DATA", ClassData::CONST_String, { .stringValue = "early-data" } },
        { "HTTP2_HEADER_ETAG", ClassData::CONST_String, { .stringValue = "etag" } },
        { "HTTP2_HEADER_METHOD", ClassData::CONST_String, { .stringValue = ":method" } },
        { "HTTP2_HEADER_EXPECT", ClassData::CONST_String, { .stringValue = "expect" } },
        { "HTTP2_HEADER_EXPECT_CT", ClassData::CONST_String, { .stringValue = "expect-ct" } },
        { "HTTP2_HEADER_EXPIRES", ClassData::CONST_String, { .stringValue = "expires" } },
        { "HTTP2_HEADER_FORWARDED", ClassData::CONST_String, { .stringValue = "forwarded" } },
        { "HTTP2_HEADER_FROM", ClassData::CONST_String, { .stringValue = "from" } },
        { "HTTP2_HEADER_HOST", ClassData::CONST_String, { .stringValue = "host" } },
        { "HTTP2_HEADER_HTTP2_SETTINGS", ClassData::CONST_String, { .stringValue = "http2-settings" } },
        { "HTTP2_HEADER_IF_MATCH", ClassData::CONST_String, { .stringValue = "if-match" } },
        { "HTTP2_HEADER_IF_MODIFIED_SINCE", ClassData::CONST_String, { .stringValue = "if-modified-since" } },
        { "HTTP2_HEADER_IF_NONE_MATCH", ClassData::CONST_String, { .stringValue = "if-none-match" } },
        { "HTTP2_HEADER_IF_RANGE", ClassData::CONST_String, { .stringValue = "if-range" } },
        { "HTTP2_HEADER_IF_UNMODIFIED_SINCE", ClassData::CONST_String, { .stringValue = "if-unmodified-since" } },
        { "HTTP2_HEADER_KEEP_ALIVE", ClassData::CONST_String, { .stringValue = "keep-alive" } },
        { "HTTP2_HEADER_LAST_MODIFIED", ClassData::CONST_String, { .stringValue = "last-modified" } },
        { "HTTP2_HEADER_LINK", ClassData::CONST_String, { .stringValue = "link" } },
        { "HTTP2_HEADER_LOCATION", ClassData::CONST_String, { .stringValue = "location" } },
        { "HTTP2_HEADER_MAX_FORWARDS", ClassData::CONST_String, { .stringValue = "max-forwards" } },
        { "HTTP2_HEADER_ORIGIN", ClassData::CONST_String, { .stringValue = "origin" } },
        { "HTTP2_HEADER_PATH", ClassData::CONST_String, { .stringValue = ":path" } },
        { "HTTP2_HEADER_PREFER", ClassData::CONST_String, { .stringValue = "prefer" } },
        { "HTTP2_HEADER_PRIORITY", ClassData::CONST_String, { .stringValue = "priority" } },
        { "HTTP2_HEADER_PROTOCOL", ClassData::CONST_String, { .stringValue = ":protocol" } },
        { "HTTP2_HEADER_PROXY_AUTHENTICATE", ClassData::CONST_String, { .stringValue = "proxy-authenticate" } },
        { "HTTP2_HEADER_PROXY_AUTHORIZATION", ClassData::CONST_String, { .stringValue = "proxy-authorization" } },
        { "HTTP2_HEADER_PROXY_CONNECTION", ClassData::CONST_String, { .stringValue = "proxy-connection" } },
        { "HTTP2_HEADER_PURPOSE", ClassData::CONST_String, { .stringValue = "purpose" } },
        { "HTTP2_HEADER_RANGE", ClassData::CONST_String, { .stringValue = "range" } },
        { "HTTP2_HEADER_REFERER", ClassData::CONST_String, { .stringValue = "referer" } },
        { "HTTP2_HEADER_REFRESH", ClassData::CONST_String, { .stringValue = "refresh" } },
        { "HTTP2_HEADER_RETRY_AFTER", ClassData::CONST_String, { .stringValue = "retry-after" } },
        { "HTTP2_HEADER_SCHEME", ClassData::CONST_String, { .stringValue = ":scheme" } },
        { "HTTP2_HEADER_SERVER", ClassData::CONST_String, { .stringValue = "server" } },
        { "HTTP2_HEADER_SET_COOKIE", ClassData::CONST_String, { .stringValue = "set-cookie" } },
        { "HTTP2_HEADER_STATUS", ClassData::CONST_String, { .stringValue = ":status" } },
        { "HTTP2_HEADER_STRICT_TRANSPORT_SECURITY", ClassData::CONST_String, { .stringValue = "strict-transport-security" } },
        { "HTTP2_HEADER_TE", ClassData::CONST_String, { .stringValue = "te" } },
        { "HTTP2_HEADER_TIMING_ALLOW_ORIGIN", ClassData::CONST_String, { .stringValue = "timing-allow-origin" } },
        { "HTTP2_HEADER_TK", ClassData::CONST_String, { .stringValue = "tk" } },
        { "HTTP2_HEADER_TRAILER", ClassData::CONST_String, { .stringValue = "trailer" } },
        { "HTTP2_HEADER_TRANSFER_ENCODING", ClassData::CONST_String, { .stringValue = "transfer-encoding" } },
        { "HTTP2_HEADER_UPGRADE", ClassData::CONST_String, { .stringValue = "upgrade" } },
        { "HTTP2_HEADER_UPGRADE_INSECURE_REQUESTS", ClassData::CONST_String, { .stringValue = "upgrade-insecure-requests" } },
        { "HTTP2_HEADER_USER_AGENT", ClassData::CONST_String, { .stringValue = "user-agent" } },
        { "HTTP2_HEADER_VARY", ClassData::CONST_String, { .stringValue = "vary" } },
        { "HTTP2_HEADER_VIA", ClassData::CONST_String, { .stringValue = "via" } },
        { "HTTP2_HEADER_WARNING", ClassData::CONST_String, { .stringValue = "warning" } },
        { "HTTP2_HEADER_WWW_AUTHENTICATE", ClassData::CONST_String, { .stringValue = "www-authenticate" } },
        { "HTTP2_HEADER_X_CONTENT_TYPE_OPTIONS", ClassData::CONST_String, { .stringValue = "x-content-type-options" } },
        { "HTTP2_HEADER_X_FORWARDED_FOR", ClassData::CONST_String, { .stringValue = "x-forwarded-for" } },
        { "HTTP2_HEADER_X_FRAME_OPTIONS", ClassData::CONST_String, { .stringValue = "x-frame-options" } },
        { "HTTP2_HEADER_X_XSS_PROTECTION", ClassData::CONST_String, { .stringValue = "x-xss-protection" } },
        { "HTTP2_METHOD_ACL", ClassData::CONST_String, { .stringValue = "ACL" } },
        { "HTTP2_METHOD_BASELINE_CONTROL", ClassData::CONST_String, { .stringValue = "BASELINE-CONTROL" } },
        { "HTTP2_METHOD_BIND", ClassData::CONST_String, { .stringValue = "BIND" } },
        { "HTTP2_METHOD_CHECKIN", ClassData::CONST_String, { .stringValue = "CHECKIN" } },
        { "HTTP2_METHOD_CHECKOUT", ClassData::CONST_String, { .stringValue = "CHECKOUT" } },
        { "HTTP2_METHOD_CONNECT", ClassData::CONST_String, { .stringValue = "CONNECT" } },
        { "HTTP2_METHOD_COPY", ClassData::CONST_String, { .stringValue = "COPY" } },
        { "HTTP2_METHOD_DELETE", ClassData::CONST_String, { .stringValue = "DELETE" } },
        { "HTTP2_METHOD_GET", ClassData::CONST_String, { .stringValue = "GET" } },
        { "HTTP2_METHOD_HEAD", ClassData::CONST_String, { .stringValue = "HEAD" } },
        { "HTTP2_METHOD_LABEL", ClassData::CONST_String, { .stringValue = "LABEL" } },
        { "HTTP2_METHOD_LINK", ClassData::CONST_String, { .stringValue = "LINK" } },
        { "HTTP2_METHOD_LOCK", ClassData::CONST_String, { .stringValue = "LOCK" } },
        { "HTTP2_METHOD_MERGE", ClassData::CONST_String, { .stringValue = "MERGE" } },
        { "HTTP2_METHOD_MKACTIVITY", ClassData::CONST_String, { .stringValue = "MKACTIVITY" } },
        { "HTTP2_METHOD_MKCALENDAR", ClassData::CONST_String, { .stringValue = "MKCALENDAR" } },
        { "HTTP2_METHOD_MKCOL", ClassData::CONST_String, { .stringValue = "MKCOL" } },
        { "HTTP2_METHOD_MKREDIRECTREF", ClassData::CONST_String, { .stringValue = "MKREDIRECTREF" } },
        { "HTTP2_METHOD_MKWORKSPACE", ClassData::CONST_String, { .stringValue = "MKWORKSPACE" } },
        { "HTTP2_METHOD_MOVE", ClassData::CONST_String, { .stringValue = "MOVE" } },
        { "HTTP2_METHOD_OPTIONS", ClassData::CONST_String, { .stringValue = "OPTIONS" } },
        { "HTTP2_METHOD_ORDERPATCH", ClassData::CONST_String, { .stringValue = "ORDERPATCH" } },
        { "HTTP2_METHOD_PATCH", ClassData::CONST_String, { .stringValue = "PATCH" } },
        { "HTTP2_METHOD_POST", ClassData::CONST_String, { .stringValue = "POST" } },
        { "HTTP2_METHOD_PRI", ClassData::CONST_String, { .stringValue = "PRI" } },
        { "HTTP2_METHOD_PROPFIND", ClassData::CONST_String, { .stringValue = "PROPFIND" } },
        { "HTTP2_METHOD_PROPPATCH", ClassData::CONST_String, { .stringValue = "PROPPATCH" } },
        { "HTTP2_METHOD_PUT", ClassData::CONST_String, { .stringValue = "PUT" } },
        { "HTTP2_METHOD_REBIND", ClassData::CONST_String, { .stringValue = "REBIND" } },
        { "HTTP2_METHOD_REPORT", ClassData::CONST_String, { .stringValue = "REPORT" } },
        { "HTTP2_METHOD_SEARCH", ClassData::CONST_String, { .stringValue = "SEARCH" } },
        { "HTTP2_METHOD_TRACE", ClassData::CONST_String, { .stringValue = "TRACE" } },
        { "HTTP2_METHOD_UNBIND", ClassData::CONST_String, { .stringValue = "UNBIND" } },
        { "HTTP2_METHOD_UNCHECKOUT", ClassData::CONST_String, { .stringValue = "UNCHECKOUT" } },
        { "HTTP2_METHOD_UNLINK", ClassData::CONST_String, { .stringValue = "UNLINK" } },
        { "HTTP2_METHOD_UNLOCK", ClassData::CONST_String, { .stringValue = "UNLOCK" } },
        { "HTTP2_METHOD_UPDATE", ClassData::CONST_String, { .stringValue = "UPDATE" } },
        { "HTTP2_METHOD_UPDATEREDIRECTREF", ClassData::CONST_String, { .stringValue = "UPDATEREDIRECTREF" } },
        { "HTTP2_METHOD_VERSION_CONTROL", ClassData::CONST_String, { .stringValue = "VERSION-CONTROL" } },
        { "MAX_INITIAL_WINDOW_SIZE", ClassData::CONST_Integer, { .intValue = C_MAX_INITIAL_WINDOW_SIZE } },
        { "MAX_MAX_FRAME_SIZE", ClassData::CONST_Integer, { .intValue = C_MAX_MAX_FRAME_SIZE } },
        { "MIN_MAX_FRAME_SIZE", ClassData::CONST_Integer, { .intValue = C_MIN_MAX_FRAME_SIZE } },
        { "NGHTTP2_NO_ERROR", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_NO_ERROR } },
        { "NGHTTP2_PROTOCOL_ERROR", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_PROTOCOL_ERROR } },
        { "NGHTTP2_INTERNAL_ERROR", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_INTERNAL_ERROR } },
        { "NGHTTP2_FLOW_CONTROL_ERROR", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_FLOW_CONTROL_ERROR } },
        { "NGHTTP2_STREAM_CLOSED", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_STREAM_CLOSED } },
        { "NGHTTP2_FRAME_SIZE_ERROR", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_FRAME_SIZE_ERROR } },
        { "NGHTTP2_REFUSED_STREAM", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_REFUSED_STREAM } },
        { "NGHTTP2_CANCEL", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_CANCEL } },
        { "NGHTTP2_COMPRESSION_ERROR", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_COMPRESSION_ERROR } },
        { "NGHTTP2_CONNECT_ERROR", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_CONNECT_ERROR } },
        { "NGHTTP2_ENHANCE_YOUR_CALM", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_ENHANCE_YOUR_CALM } },
        { "NGHTTP2_INADEQUATE_SECURITY", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_INADEQUATE_SECURITY } },
        { "NGHTTP2_HTTP_1_1_REQUIRED", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_HTTP_1_1_REQUIRED } },
        { "NGHTTP2_ERR_FRAME_SIZE_ERROR", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_ERR_FRAME_SIZE_ERROR } },
        { "NGHTTP2_FLAG_NONE", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_FLAG_NONE } },
        { "NGHTTP2_FLAG_ACK", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_FLAG_ACK } },
        { "NGHTTP2_FLAG_END_STREAM", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_FLAG_END_STREAM } },
        { "NGHTTP2_FLAG_END_HEADERS", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_FLAG_END_HEADERS } },
        { "NGHTTP2_FLAG_PADDED", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_FLAG_PADDED } },
        { "NGHTTP2_FLAG_PRIORITY", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_FLAG_PRIORITY } },
        { "NGHTTP2_DEFAULT_WEIGHT", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_DEFAULT_WEIGHT } },
        { "NGHTTP2_SESSION_SERVER", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SESSION_SERVER } },
        { "NGHTTP2_SESSION_CLIENT", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SESSION_CLIENT } },
        { "NGHTTP2_SETTINGS_HEADER_TABLE_SIZE", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SETTINGS_HEADER_TABLE_SIZE } },
        { "NGHTTP2_SETTINGS_ENABLE_PUSH", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SETTINGS_ENABLE_PUSH } },
        { "NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS } },
        { "NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE } },
        { "NGHTTP2_SETTINGS_TIMEOUT", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SETTINGS_TIMEOUT } },
        { "NGHTTP2_SETTINGS_MAX_FRAME_SIZE", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SETTINGS_MAX_FRAME_SIZE } },
        { "NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE } },
        { "NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL } },
        { "NGHTTP2_STREAM_STATE_IDLE", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_STREAM_STATE_IDLE } },
        { "NGHTTP2_STREAM_STATE_OPEN", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_STREAM_STATE_OPEN } },
        { "NGHTTP2_STREAM_STATE_RESERVED_LOCAL", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_STREAM_STATE_RESERVED_LOCAL } },
        { "NGHTTP2_STREAM_STATE_RESERVED_REMOTE", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_STREAM_STATE_RESERVED_REMOTE } },
        { "NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL } },
        { "NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE } },
        { "NGHTTP2_STREAM_STATE_CLOSED", ClassData::CONST_Integer, { .intValue = C_NGHTTP2_STREAM_STATE_CLOSED } },
        { "PADDING_STRATEGY_NONE", ClassData::CONST_Integer, { .intValue = C_PADDING_STRATEGY_NONE } },
        { "PADDING_STRATEGY_ALIGNED", ClassData::CONST_Integer, { .intValue = C_PADDING_STRATEGY_ALIGNED } },
        { "PADDING_STRATEGY_CALLBACK", ClassData::CONST_Integer, { .intValue = C_PADDING_STRATEGY_CALLBACK } },
        { "PADDING_STRATEGY_MAX", ClassData::CONST_Integer, { .intValue = C_PADDING_STRATEGY_MAX } }
    };

    static ClassData s_cd = {
        "http2_constants", true, s__new, NULL,
        0, NULL, 0, NULL, 0, NULL, ARRAYSIZE(s_const), s_const, NULL, NULL,
        &object_base::class_info(),
        false
    };

    static ClassInfo s_ci(s_cd);
    return s_ci;
}
}
