
/*! @brief 超文本传输协议模块，用以支持 http 协议处理 */
class http : module
{
	/*! @brief 创建一个 http 请求对象，参见 HttpRequest */
	static HttpRequest new Request();

	/*! @brief 创建一个 http 响应对象，参见 HttpResponse */
	static HttpResponse new Response();

	/*! @brief 创建一个 http 协议处理器对象，将流对象的数据转变为 http 消息对象
	 * @param hdlr http 消息处理器
	 * @return 返回一个可以将流对象数据转变为 http 消息的处理器
	 */
	static HttpHandler handler(Handler hdlr);

	/*! @brief 创建一个 http 协议处理器对象，将流对象的数据转变为 http 消息对象
	 * @param hdlr http 消息处理函数
	 * @return 返回一个可以将流对象数据转变为 http 消息的处理器
	 */
	static HttpHandler handler(Function hdlr);

	/*! @brief 创建一个 http 静态文件处理器，用以用静态文件响应 http 消息
	 * @param root 文件跟路径
	 * @return 返回一个静态文件处理器用于处理 http 消息
	 */
	static Handler fileHandler(String root);
};
