
/*! @brief http Cookie 对象，用于添加和处理 cookie */
class HttpCookie : object
{
    /*! @brief HttpCookie 构造函数，创建一个新的 HttpCookie 对象 */
    HttpCookie();

    /*! @brief HttpCookie 构造函数，创建一个新的 HttpCookie 对象
     @param name 指定创建的 cookie 名称
     @param value 指定创建的 cookie 值
    */
    HttpCookie(String name, String value = "");

    /*! @brief 解析给定的字符串，填充 cookie 对象
     @param header 指定需要解析的 header 字符串
    */
    parse(String header);

    /*! @brief 查询和设置 cookie 名称 */
    String name;

    /*! @brief 查询和设置 cookie 的值 */
    String value;

    /*! @brief 查询和设置 cookie 的域名范围 */
    String domain;

    /*! @brief 查询和设置 cookie 的路径范围 */
    String path;

    /*! @brief 查询和设置 cookie 的过期时间 */
    Date expires;

    /*! @brief 查询和设置 cookie 是否仅允许 http 请求，缺省 false */
    Boolean httpOnly;

    /*! @brief 查询和设置 cookie 是否仅通过 https 传递，缺省 false */
    Boolean secure;
};
