class HttpMessage: Trigger
{
	String protocol;
	readonly HttpCollection headers;
	SeekableStream body;
	String contentType;
	readonly Long contentLength;
	Boolean keepAlive;

	clear();
	send(Stream stm) async;
	asyncSend(Stream stm);
	onsend(Function func);
	read(BufferedStream stm) async;
	asyncRead(BufferedStream stm);
	onread(Function func);
};
