
/*! @brief 输入输出处理模块

 使用方法：
 @code
 var io = require('io');
 @endcode
 */
interface io : module
{
    /*! @brief 创建一个内存流对象，参见 MemoryStream */
    static MemoryStream new MemoryStream();

    /*! @brief 创建一个缓存流读取对象，参见 BufferedStream */
    static BufferedStream new BufferedStream();
};
