/*! @brief json 编码与解码模块
 引用方式：
 @code
 var encoding = require('encoding');
 var json = encoding.json;
 @endcode
 或者
 @code
 var json = require('json');
 @endcode
 */
module json
{
	/*! @brief 以 json 格式编码变量
	 @param data 要编码的变量
	 @return 返回编码的字符串
	 */
	static String encode(Value data);

	/*! @brief 以 json 方式解码字符串为一个变量
	 @param data 要解码的字符串
	 @return 返回解码的变量
	 */
	static Value decode(String data);
};
