
/*! @brief Variant 数组对象，一般用以返回一组 Variant 数据 */
class List : object
{
	/*! @brief List 对象构造函数*/
	List();

	/*! @brief 对象数组可使用下标直接访问 Variant 数据*/
	Variant operator[];

	/*! @brief 获取缓存对象的尺寸 */
	readonly Integer length;

	/*! @brief 修改缓存对象尺寸 */
	resize(Integer sz);

	/*! @brief 在数组结尾添加一个元素 */
	append(Variant v);

	/*! @brief 返回一个新对象数组，包含指定范围的数据，若范围超出缓存，则只返回有效部分数据
	 * @param start 指定范围的起始，缺省从头开始
	 * @param end 指定范围的结束，缺省到缓存结尾
	 * @return 返回新的对象数组
	 */
	List slice(Integer start = 0, Integer end = -1);
};
