
/*! @brief Variant 数组对象，一般用以返回一组 Variant 数据

 用以创建和管理数组对象，创建方法：
 @code
 var collection = require("collection");
 var a = new collection.List();
 @endcode
 */
interface List : object
{
    /*! @brief List 对象构造函数*/
    List();

    /*! @brief List 对象构造函数
     @param data 初始化的一组元素
    */
    List(Array data);

    /*! @brief 数组可使用下标直接访问 Variant 数据*/
    Variant operator[];

    /*! @brief 冻结数组内容，禁止一些修改操作 */
    freeze();

    /*! @brief 获取数组的尺寸 */
    readonly Integer length;

    /*! @brief 修改数组尺寸
     @param sz 指定新尺寸
     */
    resize(Integer sz);

    /*! @brief 在数组结尾添加一个元素
      @param v 指定添加的元素
     */
    push(Variant v);

    /*! @brief 在数组结尾添加一个元素
      @param ... 指定添加的多个元素
     */
    push(...);

    /*! @brief 在数组结尾添加一组元素
      @param data 添加的一组元素
     */
    pushArray(Array data);

    /*! @brief 返回数组结尾的一个元素
      @return 结尾的元素
     */
    Variant pop();

    /*! @brief 返回一个新数组，包含指定范围的数据，若范围超出缓存，则只返回有效部分数据
     @param start 指定范围的起始，缺省从头开始
     @param end 指定范围的结束，缺省到缓存结尾
     @return 返回新的数组
     */
    List slice(Integer start = 0, Integer end = -1);

    /*! @brief 将当前数组与给定的一个或者多个数组合并
     @param ... 给定的一个或多个数组
     @return 返回合并的数组
     */
    List concat(...);

    /*! @brief 检测全部数据是否通过测试函数
     @param func 测试函数
     @param thisArg 调用测试函数的参数，可省略
     @return 全部通过测试则返回 true
     */
    Boolean every(Function func, Value thisArg = undefined);

    /*! @brief 检测一些数据是否通过测试函数
     @param func 测试函数
     @param thisArg 调用测试函数的参数，可省略
     @return 全部不通过测试则返回 false，否则返回true
     */
    Boolean some(Function func, Value thisArg = undefined);

    /*! @brief 过滤通过测试的数据成为一个新的数组
     @param func 测试函数
     @param thisArg 调用过滤函数的参数，可省略
     @return 经过过滤的新数组
     */
    List filter(Function func, Value thisArg = undefined);

    /*! @brief 遍历处理全部数据
     @param func 处理函数
     @param thisArg 调用处理函数的参数，可省略
     */
    forEach(Function func, Value thisArg = undefined);

    /*! @brief 遍历处理全部数据并返回结果
     @param func 处理函数
     @param thisArg 调用处理函数的参数，可省略
     @return 处理结果数组
     */
    List map(Function func, Value thisArg = undefined);

    /*! @brief 排序全部数据并返回列表本身
     @param func 比较处理函数
     @return 列表本身
     */
    List sort(Function func);

    /*! @brief 排序全部数据并返回列表本身
     @return 列表本身
     */
    List sort();

    /*! @brief 返回列表的 js 数组
      @return 包含数据的 js 数组
     */
    Array toArray();
};
