/*! @brief mongodb 数据库数据集对象 */
class MongoCollection: object
{
	MongoCursor find(Object query = {}, Object projection = {});

	Object findOne(Object query = {}, Object projection = {});

	Object findAndModify(Object query);

	insert(Array documents);
	insert(Object document);

	save(Object document);

	update(Object query, Object document, Boolean upsert = false, Boolean multi = false);
	update(Object query, Object document, Object options);

	Object runCommand(Object cmd);
	Object runCommand(String cmd, Object arg = {});

	drop();
	ensureIndex(Object keys, Object options = {});
	Object reIndex();
	Object dropIndex(String name);
	Object dropIndexes();
	Array getIndexes();

	MongoID oid(String hexStr = "");
};
