/*! @brief mongodb 数据库数据集对象
 *
 * 使用 MongoDB.getCollection 创建：
 * @code
 * var col = mdb.test;
 * var col1 = mdb.getCollection('test');
 * @endcode
 */
class MongoCollection: object
{
	MongoCursor find(Object query = {}, Object projection = {});

	Object findOne(Object query = {}, Object projection = {});

	Object findAndModify(Object query);

	insert(Array documents);
	insert(Object document);

	save(Object document);

	update(Object query, Object document, Boolean upsert = false, Boolean multi = false);
	update(Object query, Object document, Object options);

	remove(Object query);

	Object runCommand(Object cmd);
	Object runCommand(String cmd, Object arg = {});

	drop();
	ensureIndex(Object keys, Object options = {});
	Object reIndex();
	Object dropIndex(String name);
	Object dropIndexes();
	Array getIndexes();

	MongoCollection getCollection(String name);
	readonly MongoCollection operator[String];

	MongoID oid(String hexStr = "");
};
