
/*! @brief mongodb 数据库连接对象 */
class MongoDB : object
{

	MongoCollection getCollection(String name);

	Object runCommand(Object cmd);
	Object runCommand(String cmd, Value arg);

	readonly MongoCollection operator[String];
};
