
/*! @brief 网络访问模块
 *
 * 基础模块。可用于创建和操作网络资源，引用方式：
 * \code
 * var net = require('net');
 * \endcode
 */
class net : module
{

	/*! @brief 地址集常量，指定 ipv4*/
	const Integer AF_INET = 2;
	/*! @brief 地址集常量，指定 ipv6*/
	const Integer AF_INET6 = 10;

	const Integer SOCK_STREAM = 1;
	const Integer SOCK_DGRAM = 2;
};
