
/*! @brief 内存 profiler 模块

 使用方法：
 @code
 var profiler = require('profiler');
 @endcode
 */
module profiler
{
	/*! @brief 获取当前时间节点的堆快照，堆快照记录了当前时刻JS堆的状态
	 @return 返回获取到的堆信息快照
	 */
	static HeapSnapshot takeSnapshot();

	/*! @brief 执行给定的函数，并对比执行前后 v8 堆的变化
	 @param test 给定要测试的函数
	 @return 返回对比的结果
	 */
	static Object diff(Function test);
};
