
/*! @brief 正则表达式对象
 */
interface Regex : object
{
    /*! @brief 检索字符串中的正则表达式的匹配
     @param str 要检索的字符串
     @return 返回一个数组，其中存放匹配的结果。如果未找到匹配，则返回值为 null
     */
    Array exec(String str);

    /*! @brief 检测一个字符串是否匹配某个模式
     @param str     要检索的字符串
     @return 如果字符串 str 中含有匹配的文本，则返回 true，否则返回 false
     */
    Boolean test(String str);

    /*! @brief 查询和设置下次匹配的起始位置 */
    Integer lastIndex;

    /*! @brief 查询正则表达式是否具有标志 "g"。它声明了给定的正则表达式是否执行全局匹配。如果 g 标志被设置，则该属性为 true，否则为 false */
    readonly Boolean global;

    /*! @brief 查询正则表达式是否设置 "i" 标志。如果设置了 "i" 标志，则返回 true，否则返回 false */
    readonly Boolean ignoreCase;

    /*! @brief 查询正则表达式正则表达式是否具有标志 m。它声明了给定的正则表达式是否以多行模式执行模式匹配。在这种模式中，如果要检索的字符串中含有换行符，^ 和 $ 锚除了匹配字符串的开头和结尾外还匹配每行的开头和结尾 */
    readonly Boolean multiline;
};
