
/*! @brief 远程过程调用消息转换模块

 使用方法：
 @code
 var rpc = require('rpc');
 @endcode
 */
module rpc
{
	/*! @brief 创建 rpc 任务代理，参见 RpcTask
	 @param id 指定要添加的模块名称，名称不支持相对路径
	 @return 返回 RpcTask 代理对象
	 */
	static RpcTask open(String id);
};
