/*! @brief 安全沙箱对象，用于管理一个独立的运行空间

  所有的代码都运行在自己的沙箱中，全局的 require 会调用当前沙箱加载模块，沙箱会通过 require 传递给加载的沙箱。下面的示例创建一个沙箱，限制只允许访问全局基础模块中的 assert 模块，并添加 a 和 b 两个定制模块：
 @code
 var vm = require('vm');
 var sbox = new vm.SandBox({
   a: 100,
   b: 200,
   assert: require('assert')
 });

 var mod_in_sbox = sbox.require('./path/to/mod');
 @endcode
 */
class SandBox: object
{
    /*! @brief 构造一个新的安全沙箱对象，并初始化基础模块
     @param mods 指定要添加的模块对象字典
     @param name 沙箱名称，命名沙箱会在抛出错误时回报所在沙箱
     */
    SandBox(Object mods, String name = "");

    /*! @brief 构造一个新的安全沙箱对象，并初始化基础模块
     @param mods 指定要添加的模块对象字典
     @param require 自定义 require 函数，当模块不存在时，先调用自定义函数，无返回再从文件中加载
     @param name 沙箱名称，命名沙箱会在抛出错误时回报所在沙箱
     */
    SandBox(Object mods, Function require, String name = "");

    /*! @brief 向沙箱中添加一个基础模块
     @param id 指定要添加的模块名称
     @param mod 指定要添加的模块对象
     */
    add(String id, Value mod);

    /*! @brief 向沙箱中添加一组基础模块
     @param mods 指定要添加的模块对象字典，添加的 javascript 模块将会生成一份复制，以避免沙箱修改对象产生互相干扰
     */
    add(Object mods);

    /*! @brief 向沙箱中添加一个脚本模块
     @param srcname 指定要添加的脚本名称
     @param script 指定要添加的脚本代码
     @return 返回加载的模块对象
     */
    Value addScript(String srcname, String script);

    /*! @brief 从沙箱中删除指定的基础模块
     @param id 指定要删除的模块名称
     */
    remove(String id);

    /*! @brief 运行一个脚本
     @param fname 指定要运行的脚本路径
     */
    run(String fname);

    /*! @brief 加载一个模块并返回模块对象，更多信息参阅 @ref module

     require 可用于加载基础模块，文件模块。

     基础模块是沙箱创建时初始化的模块，引用时只需传递相应的 id，比如 require("net")。

     文件模块是用户自定义模块，引用时需传递以 ./ 或 ../ 开头的相对路径。文件模块支持 .js 和 .json 文件。

     文件模块也支持 package.json 格式，当模块为目录结构时，require 会先查询 package.json 中的 main，未发现则尝试加载路径下的 index.js 或 index.json。

     若引用路径不是 ./ 或 ../ 开头，并且非基础模块，require 则先在启动路径查找，然后从当前模块所在路径下的 .modules 查找，并上级目录递归。

     @param id 指定要加载的模块名称
     @return 返回加载的模块对象
     */
    Value require(String id);
};
