
/*! @brief 可移动当前指针的流对象接口 */
class SeekableStream : Stream
{
	/*! @brief 移动文件当前操作位置
	  @param offset 指定新的位置
	  @param whence 指定位置基准，允许的值为：SEEK_SET, SEEK_CUR, SEEK_END
	 */
	seek(Long offset, Integer whence);

	/*! @brief 查询流当前位置
	 @return 返回流当前位置
	 */
	Long tell();

	/*! @brief 移动当前位置到流开头 */
	rewind();

	/*! @brief 查询流尺寸
	 @return 返回流尺寸
	 */
	Long size();

	/*! @brief 从流内读取剩余的全部数据
	 @return 返回从流内读取的数据，若无数据可读，或者连接中断，则返回 null
	 */
	Buffer readAll() async;

	/*! @brief 查询当前文件的基础信息
	 @return 返回 Stat 对象描述文件信息
	 */
	Stat stat() async;
};
