
/*! @brief 网络套接口对象
 */
class Socket : Stream
{
	readonly Integer family;
	readonly Integer type;

	connect(String addr, Integer port) async;
	bind(Integer port, Boolean onlyIPv6 = false);
	bind(String addr, Integer port, Boolean onlyIPv6 = false);
	listen(Integer backlog = 20);
	Socket accept() async;
	Buffer recv(Integer bytes = -1) async;
	Buffer recvFrom(Integer bytes = -1) async;
	send(Buffer data) async;
	sendto(Buffer data, String host, Integer port) async;
};
