
/*! @brief 网络套接口对象
 */
class Socket : Stream
{
	readonly Integer family;
	readonly Integer type;

	connect(String host, Integer port);
	bind(String addr, Integer port);
	bind(Integer port);
	listen();
	Socket accept();
	Buffer recv(Integer size = -1);
	Buffer recvFrom(Integer size = -1);
	send(Buffer data);
	sendto(Buffer data, String host, Integer port);
};
