
/*! @brief 网络套接口对象
 */
class Socket : Stream
{
	readonly Integer family;
	readonly Integer type;

	readonly String remoteAddress;
	readonly Integer remotePort;
	readonly String localAddress;
	readonly Integer localPort;

	connect(String addr, Integer port) async;
	bind(Integer port, Boolean allowIPv4 = true);
	bind(String addr, Integer port, Boolean allowIPv4 = true);
	listen(Integer backlog = 20);
	Socket accept() async;
	Buffer recv(Integer bytes = -1);
	Buffer recv(Function cb);
	Buffer recv(Integer bytes, Function cb);
	Buffer recvFrom(Integer bytes = -1);
	send(Buffer data);
	send(Buffer data, Function cb);
	sendto(Buffer data, String host, Integer port);
};
