
/*! @brief SQL Server 数据库连接对象

 使用 db.open 或 db.openMySQL 创建，创建方式：
 @code
 var sql = db.openMSSQL("mssql://user:pass@host/db");
 @endcode
*/
interface MSSQL : DbConnection
{
	/*! @brief 选择当前数据库连接的缺省数据库
	 @param dbName 指定数据库名
	 */
	use(String dbName) async;
};
