
/*! @brief 终端输出颜色配置对象
 */
class TextColor : object
{
	/*! @brief 指定 notice 颜色 */
	String notice;

	/*! @brief 指定 notic 颜色 */
	String warn;

	/*! @brief 指定 notic 颜色 */
	String error;

	/*! @brief 指定 highLight 颜色 */
	String highLight;
};
