/*! @brief 浏览器窗口对象 */
interface WebView : EventEmitter
{
	/*! @brief 关闭当前窗口 */
	close() async;

	/*! @brief 等待当前窗口关闭 */
	wait() async;

	/*! @brief 向 webview 内发送消息
	 @param msg 要发送的消息
	 */
	postMessage(String msg) async;

	/*! @brief 查询和设置窗口是否显示 */
	Boolean visible;

	/*! @brief 查询和绑定加载成功事件，相当于 on("load", func); */
	Function onload;

	/*! @brief 查询和绑定窗口移动事件，相当于 on("move", func); */
	Function onmove;

	/*! @brief 查询和绑定窗口尺寸改变事件，相当于 on("size", func); */
	Function onsize;

	/*! @brief 查询和绑定窗口关闭事件，相当于 on("close", func); */
	Function onclose;

	/*! @brief 查询和绑定接受 webview 内 postMessage 消息事件，相当于 on("message", func); */
	Function onmessage;
};
