
/*! @brief websocket 支持模块

 使用方法：
 @code
 var ws = require('ws');
 @endcode
 */
module ws
{
    /*! @brief 指定 websocket 消息类型 0，代表一个继续帧 */
    const CONTINUE = 0;

    /*! @brief 指定 websocket 消息类型 1，代表一个文本帧 */
    const TEXT = 1;

    /*! @brief 指定 websocket 消息类型 2，代表一个二进制帧 */
    const BINARY = 2;

    /*! @brief 指定 websocket 消息类型 8，连接关闭 */
    const CLOSE = 8;

    /*! @brief 指定 websocket 消息类型 9，代表一个 ping 帧 */
    const PING = 9;

    /*! @brief 指定 websocket 消息类型 10，代表一个 pong 帧 */
    const PONG = 10;

    /*! @brief 创建一个 websocket 消息对象，参见 WebSocketMessage */
    static WebSocketMessage new Message();

    /*! @brief 创建一个 websocket 包协议转换处理器，参见 WebSocketHandler */
    static WebSocketHandler new Handler();

    /*! @brief 创建一个 websocket 连接，并返回握手成功的 Stream 对象
     @param url 指定连接的 url，支持 ws:// 和 wss:// 协议
     @param origin 指定连接的授权域名
     @return 返回连接成功的 Stream 对象，可能为 Socket 或者 SslSocket
     */
    static Stream connect(String url, String origin = "") async;
};
