
/*! @brief XmlDocumentType 对象用于访问 XML 所定义的实体
*/
interface XmlDocumentType : XmlNode
{
    /*! @brief 返回 DTD 的名称
    */
    readonly String name;

    /*! @brief 可返回外部 DTD 的系统识别符
    */
    readonly String systemId;
};