
/*! @brief XmlProcessingInstruction 对象表示 xml 处理指令
 */
interface XmlProcessingInstruction : XmlNode
{
	/*! @brief 返回此处理指令的目标
	*/
	readonly XString target;

	/*! @brief 设置或返回此处理指令的内容
	*/
	XString data;
};