
/*! @brief zlib 压缩解压模块
 *
 * 使用方法：
 * @code
 * var zlib = require('zlib');
 * @endcode
 */
class zlib : module
{
	/*! @brief deflate 压缩级别，设定不压缩 */
	const Integer NO_COMPRESSION = 0;

	/*! @brief deflate 压缩级别，设定最快压缩 */
	const Integer BEST_SPEED = 1;

	/*! @brief deflate 压缩级别，设定最高压缩 */
	const Integer BEST_COMPRESSION = 9;

	/*! @brief deflate 压缩级别，设定缺省设置 */
	const Integer DEFAULT_COMPRESSION = -1;

	/*! @brief 使用 deflate 算法压缩数据
	 * @param data 给定要压缩的数据
	 * @param level 指定压缩级别，缺省为 DEFAULT_COMPRESSION
	 * @return 返回压缩后的二进制数据
	 */
	static Buffer deflate(Buffer data, Integer level = DEFAULT_COMPRESSION) async;

	/*! @brief 使用 deflate 算法压缩数据到流对象中
	 * @param data 给定要压缩的数据
	 * @param stm 指定存储压缩数据的流
	 * @param level 指定压缩级别，缺省为 DEFAULT_COMPRESSION
	 */
	static deflateTo(Buffer data, Stream stm, Integer level = DEFAULT_COMPRESSION) async;

	/*! @brief 使用 deflate 算法压缩源流中的数据到流对象中
	 * @param src 给定要压缩的数据所在的流
	 * @param stm 指定存储压缩数据的流
	 * @param level 指定压缩级别，缺省为 DEFAULT_COMPRESSION
	 */
	static deflateTo(Stream src, Stream stm, Integer level = DEFAULT_COMPRESSION) async;

	/*! @brief 解压缩 deflate 算法压缩的数据
	 * @param data 给定压缩后的数据
	 * @return 返回解压缩后的二进制数据
	 */
	static Buffer inflate(Buffer data) async;

	/*! @brief 解压缩 deflate 算法压缩的数据到流对象中
	 * @param data 给定要解压缩的数据
	 * @param stm 指定存储解压缩数据的流
	 */
	static inflateTo(Buffer data, Stream stm) async;

	/*! @brief 解压缩源流中 deflate 算法压缩的数据到流对象中
	 * @param src 给定要解压缩的数据所在的流
	 * @param stm 指定存储解压缩数据的流
	 */
	static inflateTo(Stream src, Stream stm) async;

	/*! @brief 使用 gzip 算法压缩数据
	 * @param data 给定要压缩的数据
	 * @return 返回压缩后的二进制数据
	 */
	static Buffer gzip(Buffer data) async;

	/*! @brief 使用 gzip 算法压缩数据到流对象中
	 * @param data 给定要压缩的数据
	 * @param stm 指定存储压缩数据的流
	 */
	static gzipTo(Buffer data, Stream stm) async;

	/*! @brief 使用 gzip 算法压缩源流中的数据到流对象中
	 * @param src 给定要压缩的数据所在的流
	 * @param stm 指定存储压缩数据的流
	 */
	static gzipTo(Stream src, Stream stm) async;

	/*! @brief 解压缩 gzip 算法压缩的数据
	 * @param data 给定压缩后的数据
	 * @return 返回解压缩后的二进制数据
	 */
	static Buffer gunzip(Buffer data) async;

	/*! @brief 解压缩 gzip 算法压缩的数据到流对象中
	 * @param data 给定要解压缩的数据
	 * @param stm 指定存储解压缩数据的流
	 */
	static gunzipTo(Buffer data, Stream stm) async;

	/*! @brief 解压缩源流中 gzip 算法压缩的数据到流对象中
	 * @param src 给定要解压缩的数据所在的流
	 * @param stm 指定存储解压缩数据的流
	 */
	static gunzipTo(Stream src, Stream stm) async;
};
