
/*! @brief 网络套接口对象
 */
class zmq_Socket : Trigger
{
	zmq_Socket(Integer type = zmq.PAIR);
	bind(String addr);
	connect(String addr);
	Buffer recv() async;
	send(Buffer data);
	close();
	readonly Integer type;
};
