/*! @brief Symmetric encryption algorithm object */
interface Cipher : object
{
    /*! @brief Sets the authentication tag
     buffer may be a Buffer, or a string decoded with encoding.
     @param buffer the authentication tag data
     @param encoding the encoding of a string authentication tag data, default "utf8"
     @return returns the current Cipher object
     */
    Cipher setAuthTag(Buffer|String buffer, String encoding = "utf8");

    /*! @brief Queries the authentication tag 
      @return returns the authentication tag data
    */
    Buffer getAuthTag();

    /*! @brief Sets additional authenticated data
     buffer may be a Buffer, or a string decoded with the encoding option.
     @param buffer the additional authenticated data
     @param options the additional authenticated data options to use
     @return returns the current Cipher object
    */
    Cipher setAAD(Buffer|String buffer, Object options = {});

    /*! @brief Sets automatic padding
     @param autoPadding specifies whether to pad automatically
     @return returns the current Cipher object
    */
    Cipher setAutoPadding(Boolean autoPadding = true);

    /*! @brief Updates the data
      data may be a Buffer, or a string decoded with inputEncoding.
      @param data the data to update
      @param inputEncoding the encoding of the input data, default "utf8"
      @param outputEncoding the encoding of the output data
      @return returns the updated data
    */
    Value update(Buffer|String data, String inputEncoding = "utf8", String outputEncoding = "buffer");

    /*! @brief Finalizes the data
      @param outputEncoding the encoding of the output data
      @return returns the updated data
    */
    Value final(String outputEncoding = "buffer");
};
