/*! @brief InflateRaw decompression codec, decompresses data compressed with the deflate algorithm (raw format) */
interface InflateRaw : ZlibCodec
{
    /*! @brief InflateRaw constructor
     @param opts decompression options
     */
    InflateRaw(Object opts = {});
};
