/*! @brief Basic object; all objects inherit from it*/
interface object
{
    /*! @brief Returns the string representation of the object, which is generally "[Native Object]"; objects can reimplement this according to their own characteristics
     @return returns the string representation of the object
    */
    String toString();

    /*! @brief Returns the JSON representation of the object, which is generally the set of readable properties defined by the object
     @param key unused
     @return returns the JSON-serializable value
     */
    Value toJSON(String key = "");
};
