/**
 * @description Type-check the generated d.ts corpus (R4 of
 * plans/idl-event-types-2026-10-03.md).
 *
 * `fibjs --check` attaches the built-in types as root files and suppresses
 * their diagnostics unconditionally (tools/gen_tsc.js patches
 * skipTypeCheckingWorker to skip every built-in type file), so the
 * declarations generated from the IDL are never checked themselves. This tool
 * drives the same bundled tsc over `npm/types/dts/**` with `skipLibCheck`
 * disabled and reports what it finds, so declaration-level defects
 * (incompatible member overrides, required parameters after optional ones,
 * unparameterized generics, ...) surface in the repository instead of being
 * frozen into the embedded types.
 *
 * Run it after `fibjs tools/idlc.js`:
 *
 *   fibjs tools/check_dts.js              # summary, non-zero exit on diagnostics
 *   fibjs tools/check_dts.js --list       # print every diagnostic
 *   fibjs tools/check_dts.js --report-only   # never fail (used as a baseline run)
 *
 * The checker bundle is generated by tools/gen_tsc.js; when it is missing the
 * tool says so instead of pretending the corpus is clean.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const child_process = require('child_process');

const root = path.resolve(__dirname, '..');
const checker = path.join(root, 'fibjs/scripts/opt_tools/check.js');
const dtsDir = path.join(root, 'npm/types/dts');

const args = process.argv.slice(2);
const listAll = args.indexOf('--list') >= 0;
const reportOnly = args.indexOf('--report-only') >= 0;

if (!fs.existsSync(checker)) {
    console.error('check bundle not found: ' + checker);
    console.error('run `fibjs tools/gen_tsc.js` first (it bundles the pinned TypeScript).');
    process.exit(reportOnly ? 0 : 1);
}

if (!fs.existsSync(path.join(dtsDir, 'interface'))) {
    console.error('generated types not found: ' + dtsDir);
    console.error('run `fibjs tools/idlc.js` first.');
    process.exit(reportOnly ? 0 : 1);
}

// tsc refuses to combine a tsconfig with files on the command line (TS5112)
// and resolves relative paths against its own cwd, so drive it through a
// throw-away tsconfig that includes the whole corpus.
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'fibjs-check-dts-'));

try {
    fs.writeFileSync(path.join(scratch, 'tsconfig.json'), JSON.stringify({
        compilerOptions: {
            target: 'es2020',
            module: 'commonjs',
            strict: false,
            noEmit: true,
            skipLibCheck: false,
            types: [],
        },
        include: [path.join(dtsDir, '**/*.d.ts').replace(/\\/g, '/')],
    }, null, 2));

    const r = child_process.spawnSync(process.execPath, [checker, '--no-builtin-types'], {
        cwd: scratch,
        encoding: 'utf8',
    });

    const output = (r.stdout || '') + (r.stderr || '');
    const lines = output.split('\n');
    const diagnostics = [];

    lines.forEach((line) => {
        const m = line.match(/^(.*?)\((\d+),(\d+)\): error (TS\d+): (.*)$/);
        if (!m)
            return;

        // tsc reports paths relative to its own cwd, sometimes through a chain
        // of `../`; keep the corpus-relative part only
        const marker = 'npm/types/dts/';
        const raw = m[1].split(marker);
        const file = raw.length > 1 ? marker + raw[raw.length - 1] : m[1];

        diagnostics.push({
            file,
            line: +m[2],
            code: m[4],
            message: m[5],
        });
    });

    // tsc keeps printing the message body on the following lines until the
    // next diagnostic; the summary only needs the first line of each.
    const byCode = {};
    const byFile = {};
    diagnostics.forEach((d) => {
        byCode[d.code] = (byCode[d.code] || 0) + 1;
        byFile[d.file] = (byFile[d.file] || 0) + 1;
    });

    if (listAll) {
        diagnostics.forEach((d) => {
            console.log(`${d.file}(${d.line}): ${d.code}: ${d.message}`);
        });
        console.log('');
    }

    console.log(`check_dts: ${diagnostics.length} diagnostic(s) in npm/types/dts`);

    Object.keys(byCode).sort().forEach((code) => {
        console.log(`  ${code}: ${byCode[code]}`);
    });

    const files = Object.keys(byFile).sort();
    if (files.length) {
        console.log(`  files: ${files.length}`);
        files.slice(0, 20).forEach((f) => console.log(`    ${byFile[f]}  ${f}`));
        if (files.length > 20)
            console.log(`    ... and ${files.length - 20} more`);
    }

    if (r.error) {
        console.error('check_dts: the checker failed to run: ' + r.error.message);
        process.exit(1);
    }

    // process.exitCode defaults to 0 in fibjs, so it must be assigned even
    // when the run is clean — `if (process.exitCode === undefined)` never fires
    process.exitCode = (!reportOnly && diagnostics.length) ? 1 : 0;
} finally {
    fs.rmSync(scratch, { recursive: true, force: true });
}
