/**
 * Generate bundled tsc check script with embedded lib.d.ts files
 * 
 * Downloads TypeScript directly from npm registry - no local installation needed.
 * 
 * Run: fibjs tools/gen_tsc.js
 */

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');
const http = require('http');

const outputFile = path.join(__dirname, '../fibjs/scripts/opt_tools/check.js');

// Download and extract TypeScript from npm
async function downloadTypeScript() {
    console.log('Fetching TypeScript package info from npm...');
    
    // Get package info
    const res = await http.get('https://registry.npmjs.org/typescript/latest');
    const pkgInfo = res.json();
    const version = pkgInfo.version;
    const tarballUrl = pkgInfo.dist.tarball;
    
    console.log(`Latest TypeScript version: ${version}`);
    console.log(`Downloading from: ${tarballUrl}`);
    
    // Download tarball
    const tarRes = await http.get(tarballUrl);
    const tarGz = tarRes.body.readAll();
    
    console.log(`Downloaded ${tarGz.length} bytes`);
    
    // Extract tarball (tar.gz format)
    const tar = zlib.gunzip(tarGz);
    
    // Parse tar and extract needed files
    const files = {};
    let pos = 0;
    
    while (pos < tar.length) {
        // Tar header is 512 bytes
        if (pos + 512 > tar.length) break;
        
        const header = tar.slice(pos, pos + 512);
        const name = header.slice(0, 100).toString().replace(/\0/g, '').trim();
        
        if (!name) break;
        
        // File size is at offset 124, 12 bytes, octal
        const sizeStr = header.slice(124, 136).toString().replace(/\0/g, '').trim();
        const size = parseInt(sizeStr, 8) || 0;
        
        pos += 512; // Skip header
        
        if (size > 0) {
            const content = tar.slice(pos, pos + size);
            
            // Extract lib/*.d.ts and lib/_tsc.js
            const relativePath = name.replace(/^package\//, '');
            if (relativePath === 'lib/_tsc.js' || 
                (relativePath.startsWith('lib/lib.') && relativePath.endsWith('.d.ts'))) {
                const fileName = path.basename(relativePath);
                files[fileName] = content.toString();
                console.log(`  Extracted: ${fileName} (${content.length} bytes)`);
            }
            
            // Skip to next 512-byte boundary
            pos += Math.ceil(size / 512) * 512;
        }
    }
    
    return { version, files };
}

async function main() {
    const { version, files } = await downloadTypeScript();
    
    let tscCode = files['_tsc.js'];
    if (!tscCode) {
        throw new Error('_tsc.js not found in package');
    }
    
    // Collect lib.d.ts files
    const libFiles = {};
    for (const [name, content] of Object.entries(files)) {
        if (name.startsWith('lib.') && name.endsWith('.d.ts')) {
            libFiles[name] = content;
        }
    }
    
    console.log(`\nPacked ${Object.keys(libFiles).length} lib.d.ts files`);
    
    // Embed lib files as JSON (will be compressed by gen_scripts.js)
    const libJson = JSON.stringify(libFiles);
    console.log(`Lib files total: ${libJson.length} bytes`);

    // Generate the check.js file with header that patches fs module
    const header = `#!/usr/bin/env fibjs
/**
 * TypeScript type checker for fibjs
 * 
 * Bundled TypeScript version: ${version}
 * Generated by fibjs/scripts/opt_tools/build_check.js
 * 
 * TypeScript is licensed under Apache License 2.0
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * 
 * Usage: fibjs check [options] <files...>
 */

(function() {
"use strict";

const process = require('process');
const fs = require('fs');

// Embedded lib.d.ts files
const libFiles = ${libJson};

// Helper to extract basename
function getBasename(p) {
    return p.replace(/\\\\/g, '/').split('/').pop();
}

// Patch fs.readFileSync to check embedded lib files first
const originalReadFileSync = fs.readFileSync.bind(fs);
fs.readFileSync = function(path, options) {
    const basename = getBasename(path);
    if (basename && libFiles[basename]) {
        return Buffer.from(libFiles[basename]);
    }
    return originalReadFileSync(path, options);
};

// Patch fs.existsSync to check embedded lib files first  
const originalExistsSync = fs.existsSync.bind(fs);
fs.existsSync = function(path) {
    const basename = getBasename(path);
    if (basename && libFiles[basename]) {
        return true;
    }
    return originalExistsSync(path);
};

// Patch fs.statSync to handle embedded lib files and options parameter
const originalStatSync = fs.statSync.bind(fs);
fs.statSync = function(path, options) {
    const basename = getBasename(path);
    if (basename && libFiles[basename]) {
        // Return a fake stat object for lib files
        return {
            isFile: () => true,
            isDirectory: () => false,
            isSymbolicLink: () => false,
            size: libFiles[basename].length,
            mtime: new Date(),
            mode: 0o644
        };
    }
    // fibjs doesn't support options parameter, handle throwIfNoEntry
    try {
        return originalStatSync(path);
    } catch (e) {
        if (options && options.throwIfNoEntry === false) {
            return undefined;
        }
        throw e;
    }
};

// Modify argv: add --noEmit by default for type-check only mode
const args = process.argv.slice(2);
const hasNoEmit = args.some(a => a === '--noEmit' || a.startsWith('--noEmit='));

process.argv.length = 2;
if (!hasNoEmit) {
    process.argv.push('--noEmit');
}
process.argv.push(...args);

})();

// ============== TypeScript Compiler ==============
// The code below is from Microsoft TypeScript, licensed under Apache License 2.0
// https://github.com/microsoft/TypeScript

`;

    const checkJs = header + tscCode;
    fs.writeTextFile(outputFile, checkJs);
    console.log(`\nGenerated ${outputFile}`);
    console.log(`Total size: ${checkJs.length} bytes`);
}

main();